### ISSUE TITLE
[🐛] Couldn't compile with RN 0.66

### ISSUE THREAD

**Issue by tarouboy** [invertase/react-native-google-mobile-ads#101]
```
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > The minCompileSdk (31) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
     is greater than this module's compileSdkVersion (android-30).
     Dependency: androidx.work:work-runtime:2.7.0.
```
First of all, thanks for the package!

I found that the target SDK is 31 so I tried to install with an older version ( react-native-google-mobile-ads@3.4.0 ) which is targeting SDK 30. But npm and yarn said version not found, I guess it's depreciated for some reasons. 

So does it mean this package only compatible with RN 0.67+? Is there any way to use it with RN 0.66?

P.S. Not exactly a bug, maybe a suggestion to add the dependencies on the installation guide.

**Comment by mikehardy** [comment]
targetSdkVersion and compileSdkVersion are distinct.

You can set compileSdkVersion to 31 (and then use JDK11 - using compileSdkVersion 31 requires JDK11 but that's fine it works)

You can keep targetSdkVersion at 30, no problem.

Did you try that?

**Comment by tarouboy** [comment]
Thank you @mikehardy !

After reading your tips I found that in the build.gradle I have the following script so after changing it to compileSDK = 30 it works now :)

```
subprojects {
    afterEvaluate {subproject ->

       if (subproject.hasProperty("android") || names.contains("reactNative60") ) {
            android {
                compileSdkVersion = **31**
                targetSdkVersion = 30
                buildToolsVersion = "30.0.2"
            }
       }
    }
}
```
