### ISSUE TITLE
AppOpenAd is launched after interstitial is closed

### ISSUE THREAD

**Issue by scaralfred** [invertase/react-native-google-mobile-ads#102]
The recommended way to launch an AppOpenAd is through the app state when the app comes from the background.
However, when an Interstitial Ad is closed, that is also recognized as an app state change, and it triggers the AppOpenAd.
Has anyone found a good workaround?

**Comment by dylancom** [comment]
Check if the previous state was "background".

**Comment by scaralfred** [comment]
On Android It's always considered background, whether you close a modal or
open the app from background.

**Comment by mikehardy** [comment]
True, a modal is actually a system window and is separate from the app, so I guess it is mis-diagnosing even "mild backgrounding" (being overlayed by a system modal) as full background.
Android has multiple lifecycle steps in activities, not foreground/background - it has a sequence of pre-start/start/post-start for the application and the MainActivity, then it has pre-resume/resume/post-resume, on the way up. On the way down it's pre-/pause/post- then pre-/stop/post- hooks

https://developer.android.com/reference/android/app/Application.ActivityLifecycleCallbacks.html

This package is just one that turned up in search and looks abandoned but I wonder if something like it listening in MainActivity for the pause vs the stop might be able to differentiate? https://github.com/jaysoo/react-native-activity-android

I can only suggest careful experimentation, I have a lot of Android experience personally but have never played in this area with react-native to see how it reacts to these sort of state changes and what lifecycle observer events are emitted or what lifecycle state changes it goes through - they aren't exposed by AppState API though, I just checked

**Comment by dylancom** [comment]
Seems related to: https://github.com/googleads/googleads-mobile-flutter/issues/404

**Comment by mikehardy** [comment]
Oh that's really interesting @dylancom ! If I understand correctly I can summarize that issue as:
- currently an interstitial (perhaps any full screen) ad is part of our *application* but it is not part of the *activity*
- when the *activity* goes into the background (Android onPause maybe onStop) to show the ad then the ad finishes and onStart/onResume lifecycle stuff happens, that triggers AppState in a way that the AppOpen ad shows?

So the solution here for App Open ads is to listen to Application lifecycle events, not Activity lifecycle events?

If so, that is actually really easy believe it or not. The infrastructure to expose them to JS (if needed) via an event emitter is somewhat more complex but I think the code from react-native-firebase common which we ingested here may even make that easy ?

**Comment by quan2nd** [comment]
@wjaykim I hope you can make an AppOpen Provider similar to the Admob library you did. This will make it simple for those with little experience to implement AppOpen.
Thanks.

**Comment by wjaykim** [comment]
@mikehardy In previous library (@react-native-admob/admob) there was code listening for application lifecycle events:
https://github.com/react-native-admob/admob/blob/4b24e57308aa2dd0e28a6eab1d90ae81576e69b2/android/src/main/java/com/rnadmob/admob/ads/fullscreen/RNAdMobAppOpenAdModule.java#L115-131

But should the part be implemented in this library? I think it should be implemented in different library(that sends event for application lifecycle event).

**Comment by mikehardy** [comment]
I think we should implement them here, my reasoning:

- the app lifecycle events are trivial to implement, it's simple native code
- how we handle them is so tightly coupled to this library
- we don't need JS bindings I don't think? Even in the code you link it's not a ReactMethod, which means we don't really need a react-native package we just need to hook the Android APIs and respond.

That's my analysis of it anyway - I'd be excited to merge a PR that was basically java-only and listened to Android lifecycle events in order for AppOpen to behave well. But I could be wrong! I'm open to any other thoughts

**Comment by dylancom** [comment]
I agree that we should implement it here as it's very tightly coupled.
They also did that in the official flutter package last year: https://github.com/googleads/googleads-mobile-flutter/issues/404

**Comment by ammarahm-ed** [comment]
I faced a similar issue and this is how I fixed it.

We know that everytime an interstitial ad is closed, `AppOpenAd` will show as soon as `AppState` listener fires.
```js
const AdState = {
  canShowAppOpenAd:true
};

// In some useEffect hook
InterstitialAd.addAdEventListener(AdEventType.CLOSED, () => {
       // Do not allow AppOpenAd to show right after InterstitialAd is closed.
        AdState.canShowAppOpenAd = false;
});

// Showing AppOpenAd 
AppState.addEventListener("change", async (state) => {
        if (state === "active") {
          if (
            AppOpenAd.loaded &&
            AdState.canShowAppOpenAd
          ) {
            AppOpenAd.show();
          } else {
            //Reset AdState so next time user enters from the true background state, the AppOpenAd shows.
            AdState.canShowAppOpenAd = true;
          }
        }
})

```
I hope this helps someone. It works perfectly fine.

**Comment by mikehardy** [comment]
Oh that's funny - but in a good way! I mean of course (not that I thought of it) that's a perfect workaround. We should still handle what I think of as an error in state detection correctly in the library for real though. Until then, very nice workaround, thanks for posting that

**Comment by quan2nd** [comment]
As a TEMPORARY fix, I created a module for android, it worked fine instead of AppState
[react-native-activity-state](https://github.com/quan2nd/react-native-activity-state)
But I'm not done for IOS yet

**Comment by mikehardy** [comment]
Fantastic @quan2nd I'm not sure that iOS has the same issues, does it? For Android though, the code looks good - we could take a PR here if you wanted, or I suppose it could be a separate module (perhaps others have this same need?) although that would complicate our install a little bit by having this module depend on another one being installed

**Comment by dylancom** [comment]
@quan2nd on iOS we can just rely on if the previous appState was "background".

**Comment by HashimTheArab** [comment]
So did yall get an actual solution for this?

**Comment by AftabUfaq** [comment]
> I faced a similar issue and this is how I fixed it.
> 
> We know that everytime an interstitial ad is closed, `AppOpenAd` will show as soon as `AppState` event fires.
> 
> ```js
> const AdState = {
>   canShowAppOpenAd:true
> };
> 
> // In some useEffect hook
> InterstitialAd.addAdEventListener(AdEventType.CLOSED, () => {
>        // Do not allow AppOpenAd to show right after InterstitialAd is closed.
>       // We can depend on this as it's called soon enough before AppState event fires.
>         AdState.canShowAppOpenAd = false;
> });
> 
> // Showing AppOpenAd 
> AppState.addEventListener("change", async (state) => {
>         if (state === "active") {
>           if (
>             AppOpenAd.loaded &&
>             AdState.canShowAppOpenAd
>           ) {
>             AppOpenAd.show();
>           } else {
>             //Reset AdState so next time user enters from the true background state, the AppOpenAd shows.
>             AdState.canShowAppOpenAd = true;
>           }
>         }
> })
> ```
> 
> I hope this helps someone. It works perfectly fine.

this works only some time and for one screen. but not working for full app

**Comment by rajatvermaiam** [comment]
this is real problem here , is there any soultion?

**Comment by SumitR9910** [comment]
any updates on this issue?

**Comment by mikehardy** [comment]
@SumitR9910 a closed issue from 2024, nope - no updates, just your comment generating a notification. Do you have any testing results or new knowledge to move it forward?

**Comment by SumitR9910** [comment]
currently trying out @ammarahm-ed 's solution. Experimenting with storing the local state in a React Context so user can load the interstitial using a provider from any point in the app which will set isClosed to false whenever an interstitial is closed thus solving @AftabUfaq 's problem of it only working in a single screen. No luck till now but will update if i find a solution 😄

**Comment by SumitR9910** [comment]
Sorry for taking a long time to get back to this. I have found a solution that will probably work for all cases (no matter from which screen the interstitial is triggered). This solution is much similar to @ammarahm-ed's solution.

Setup a context that will be concerned with handling loading and storing the events and states of the interstitial ad :

```
import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useState,
} from "react";

import { TestIds, useInterstitialAd } from "react-native-google-mobile-ads";
import { adUnitID } from "../constants/adUnitID";

const InterstitialADContext = createContext();

function InterstitialADContextProvider({ children }) {
  const { isLoaded, isClosed, load, show } = useInterstitialAd(
    __DEV__ ? TestIds.INTERSTITIAL : adUnitID.mainInterstitial,
  );

  const [canShowAppOpenAd, setCanShowAppOpenAd] = useState(true);

  useEffect(() => {
    if (isClosed) {
      setCanShowAppOpenAd(false);
    }
  }, [isClosed]);

  const loadAD = useCallback(() => !isLoaded && load(), [isLoaded, load]);

  return (
    <InterstitialADContext.Provider
      value={{
        isLoaded,
        isClosed,
        show,
        canShowAppOpenAd,
        setCanShowAppOpenAd,
        loadAD,
      }}


    >
      {children}
    </InterstitialADContext.Provider>
  );
}

export function useInterstitialADContext() {
  const context = useContext(InterstitialADContext);
  if (context === undefined)
    throw new Error(
      "InterstitialADContext was used outside of the InterstitialADContextProvider",
    );
  return context;
}

export default InterstitialADContextProvider;
```

This will make sure app open ads are only shown when the app is brought back to the foreground from the background.Hope this helps.

Now use this context in your root layout (or anywhere you load and show the App open) to track if app open should be shown or not: 

```
const appState = useRef(AppState.currentState);

  const { isLoaded, load, show, isShowing, isOpened } = useAppOpenAd(
    __DEV__ ? TestIds.APP_OPEN : adUnitID.appOpen,
  );

  const { canShowAppOpenAd, setCanShowAppOpenAd } = useInterstitialADContext();

  useEffect(() => {
    const subscription = AppState.addEventListener("change", (nextAppState) => {
      if (
        appState.current.match(/inactive|background/) &&
        nextAppState === "active" &&
        canShowAppOpenAd
      ) {
        load();
        isLoaded && show();
      } else {
        setCanShowAppOpenAd(true);
      }

      appState.current = nextAppState;
    });

    return () => {
      subscription.remove();
    };
  }, [
    isLoaded,
    show,
    isShowing,
    isOpened,
    load,
    canShowAppOpenAd,
    setCanShowAppOpenAd,
  ]);
```

**Comment by cyberchester** [comment]
final Set<AppLifecycleState> _previousAppLifecycleStates = {};

@override
void didChangeAppLifecycleState(AppLifecycleState state) {
  _previousAppLifecycleStates.add(state);
  if (state == AppLifecycleState.resumed &&
      _previousAppLifecycleStates.contains(AppLifecycleState.hidden)) {
    showAppOpenAdIfAvailable();
    _previousAppLifecycleStates.clear(); // reset after showing
  }
}

try this.
