### ISSUE TITLE
[🐛] 🔥 Version > 5.0 crashes on iOS 13

### ISSUE THREAD

**Issue by ccorneliusHsv** [invertase/react-native-google-mobile-ads#111]
## Issue

Attempting to run React Native GoogleMobile Ads version > 5,  on iOS with OS version 13 results in a crash. I have recreated this issue on multiple apps, including the example app provided by the project.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `admob.json`:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

```ruby
# N/A
```

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by ccorneliusHsv** [comment]
I did not provide the files requested in the template..because I was able to repeat this with the example project provided.  So all files requested can be found in the example project. If there are files or additional information I can provide that are not in the example app..I would be glad to provide them.

**Comment by mikehardy** [comment]
Oh no! I do have an io13 emulator on hand let me check it. Sorry for the hassle.

**Comment by mikehardy** [comment]
@ccorneliusHsv I reproduce a crash - perhaps I can confirm it's the same? If you launch your app from Xcode you should see it plain as day since it's right on launch, it's a dyld error because it doesn't have the AppTrackingTransparency library linked, when it crashes for me. I'll be pursuing that, but if you have a different crash please do let me know and we may need to pursue a reproduction from your side

**Comment by mikehardy** [comment]
PR #112 has the tiny (but important) change that fixes the crash I reproduced on iOS13 simulator

You can either reach in and apply the same change in node_modules to verify it yourself locally (it's just [switching 'frameworks' for 'weak_frameworks' in the module [](podspec](https://github.com/invertase/react-native-google-mobile-ads/pull/112/files)) for the AppTrackingTransparency framework) or you can grab the patch-package formatted patch that does the same from our CI action:

https://github.com/invertase/react-native-google-mobile-ads/actions/runs/2186477201 --> [patches.zip](https://github.com/invertase/react-native-google-mobile-ads/suites/6165585577/artifacts/216054265)

I'll release it as soon as I hear back that this fixes you. Thanks for reporting it!

**Comment by ccorneliusHsv** [comment]
@mikehardy Yes, that is the bug I found and yes, can confirm that the patch did fix the issue. Thanks so much for the quick action!

Cheers!

**Comment by mikehardy** [comment]
Happy to help - crash bugs will *not* sit, they'll get fixed immediately. This library is new as a standalone thing but the core code has been around forever. The crash snuck in as we work to ingest nearly 2 years of underlying library / platform updates (the whole ATT thing!), but anyway - not crashing should be a bedrock guarantee :sweat_smile:  Cheers - will do the release in a moment
