### ISSUE TITLE
Extend AdSize support to handle size=FLUID

### ISSUE THREAD

**Issue by wjaykim** [invertase/react-native-google-mobile-ads#120]
Extend AdSize support to handle size=FLUID

_Originally posted by @mikehardy in https://github.com/invertase/react-native-google-mobile-ads/pull/105#discussion_r858917392_

**Comment by mikehardy** [comment]
Best way to help is to work with us directly here and propose a PR, you can see by the collaboration on previous PRs how quickly things can go in and release

Bonus - just by *proposing* a PR, even without maintainer attention, you get a clean set of test patches you can apply against the current public release, for integration via [patch-package](https://github.com/ds300/patch-package/issues) - https://github.com/invertase/react-native-google-mobile-ads/actions/workflows/create_test_patches.yml - so you can throw a PR up and immediately (well, a few minutes) integrate the patch in an app to see how it works for you

**Comment by mikehardy** [comment]
These are the lines that drive local development:

https://github.com/invertase/react-native-google-mobile-ads/blob/bdd66dea5d8bee522222aeb3968c5e44c8856628/package.json#L83-L99

Along with adding a new test case here and adding it to the list of test cases so you may interact with the new code:
https://github.com/invertase/react-native-google-mobile-ads/blob/main/RNGoogleMobileAdsExample/App.tsx

**Comment by djMax** [comment]
There is no question this is wrong, but just as a start: https://github.com/invertase/react-native-google-mobile-ads/pull/130
