### ISSUE TITLE
[Error: [googleMobileAds/no-fill] No ad config.]

### ISSUE THREAD

**Issue by supershik** [invertase/react-native-google-mobile-ads#127]
Hello
My android app is already published on Goolge Play Store. now I am trying to add the new Admob
I set up all ads config on the Admob dashboard and the app-adx.txt file is also crawled successfully

Even I tried to test with test id but it always return "[Error: [googleMobileAds/no-fill] No ad config.]"
Even if I try with unitID, the result is the same.
Interstitial unit id is ca-app-pub-1402510818771952/6523204801

but after creating a new project with another package name or package name is changed, it works well.

who can help me?

**Comment by mikehardy** [comment]
Hi there! 

With apologies I'm going to close this as it's a pretty low-quality issue, doesn't have any steps to reproduce or information on environment or anything that you would need if someone came to you with this problem and asked for your help, yes?

https://hackernoon.com/i-thought-i-understood-open-source-i-was-wrong-cf54999c097b
https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/minimal-reproducible-example

You should try our example app, it demonstrates how to do everything and works. 
https://github.com/invertase/react-native-google-mobile-ads/tree/main/RNGoogleMobileAdsExample

https://github.com/invertase/react-native-google-mobile-ads/blob/bdd66dea5d8bee522222aeb3968c5e44c8856628/package.json#L83-L99
