### ISSUE TITLE
🔥[🐛] Misleading TypeScript types

### ISSUE THREAD

**Issue by Bartozzz** [invertase/react-native-google-mobile-ads#137]
e## Issue

In [`RequestConfiguration` interface](https://github.com/invertase/react-native-google-mobile-ads/blob/469b3be4197545c0c6f1da248539d94b864d9be9/src/types/RequestConfiguration.ts) every property is optional, so in theory the following piece of code is considered correct:

```tsx
await mobileAds().setRequestConfiguration({
  // Update all future requests suitable for parental guidance:
  maxAdContentRating: MaxAdContentRating.PG,

  // An array of test device IDs to allow:
  testDeviceIdentifiers: isDev ? ["EMULATOR"] : undefined,
});
```

In practice, it will throw an error on the production release:

```
googleMobileAds.setRequestConfiguration(*) 'requestConfiguration.testDeviceIdentifiers' expected an array value
```

This is because this library performs [`hasOwnProperty` check](https://github.com/invertase/react-native-google-mobile-ads/blob/469b3be4197545c0c6f1da248539d94b864d9be9/src/validateAdRequestConfiguration.ts#L62=) which returns `true` if a given property exists even if its value is `undefined`. This can lead to unexpected, sometimes hard to spot bugs. In my case, some assets were not loading properly because of the piece of code above (as you can see, `testDeviceIdentifiers` value is invalid only for production release).

I'd recommend either updating the TypeScript types or update the check with something like:

```tsx
import { isUndefined, isNull } from "./validate";

function isPropertySet(target: unknown, property: PropertyKey) {
  return hasOwnProperty(target, property) && !isUndefined(target[property]) && !isNull(target[property]);
}
```

LMK If this solutions suites you, I can open a PR.

## Environment

<details><summary>Click To Expand</summary>
<p>

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **Are you using `TypeScript`?**
  - `~4.3.5`

</p>
</details>

**Comment by mikehardy** [comment]
Interesting! I'd like for this library to still be useful even for those that don't use typescript, so it seems the javascript check should be updated.

That said, I'm a typescript person so it should "feel" correct in typescript usage - in that case since your proposed javascript update check would allow the undefined (without crashing) it seems the optional spec for that property would then be working as expected.

If that analysis matches your thinking - a PR would be great!
