### ISSUE TITLE
[📚] Ads Not loading in release mode!

### ISSUE THREAD

**Issue by chzappsinc** [invertase/react-native-google-mobile-ads#142]
## Ads not loading in the release version

Why are Ads not showing in the release version?

Everything works fine on debug mode

**Comment by mikehardy** [comment]
Second time I need to mention it is a warning @chzappsinc - come on, help us help you.

https://github.com/invertase/react-native-google-mobile-ads/issues/135#issuecomment-1120504460

**Comment by mikehardy** [comment]
Also from your previous under-spec'ed-to-start issue:

> Have you tried implementing the ad inspector feature ? (check our API, you'll see it, a recent feature addition). When I use that on iOS it says we no-fill and that's that as far as I know. We have a troubleshooting section for no-fills also, in the docs, you might examine it.
