### ISSUE TITLE
[🐛] BUILD ERROR only Android

### ISSUE THREAD

**Issue by lottemarines** [invertase/react-native-google-mobile-ads#143]
## FYI
https://github.com/invertase/react-native-google-mobile-ads/issues/140

## ISSUE
I found android problems..
Could you give me some advice?

```
$ expo init

-> select a bare work flow

$ yarn add react-native-google-mobile-ads
$ pod install
$ code app.json
{
  expo : {
       my expo settings
  },
// added settings.
  "react-native-google-mobile-ads": {
    "android_app_id": "*******",
    "ios_app_id": "*******",
  }
}
$ yarn ios
=> it works.

$ yarn android
=>error code is bellow.
```

```
yarn run v1.22.17
$ expo run:android
› Building app...
Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/ken/test/android/app/build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin 'com.android.internal.application'.
   > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.
     You can try some of the following options:
       - changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.
```

`> Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.`

Already I tryed this,

$ brew tap homebrew/cask-versions
$ brew install --cask zulu11
$ yarn android
=> same error.

**Comment by mikehardy** [comment]
You need android 11 to actually be in your PATH
I don't know how the expo toolchain works but I must be clear: you are having toolchain problems, this will not result in a change to this module

If there will be no change in the module, then it is not actionable, which means we close the issue
You may find advice for "how to use java 11 with expo" on stackoverflow I think

Once you get that sorted, it should work. I forgot prior (on your "I'm using android sdk 30 but it requires 31" issue that 31 implies java 11. You're mostly there, I promise :-)
