### ISSUE TITLE
[📚] 500 Error in European Consent page

### ISSUE THREAD

**Issue by DanielYapiko** [invertase/react-native-google-mobile-ads#144]
## Documentation Feedback

There is an 500 error in: https://docs.page/invertase/react-native-google-mobile-ads/european-user-consent 

Not sure if there's a backup doc site to take a look but I am integrating this library to my app and I get stuck in this point.

Thanks a lot,
Regards.

---

- 👉 Check out [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Thanks for pointing that out @DanielYapiko ! Until it's showing up, the docs are actually here in the source tree so you may navigate in via github as well and it won't be as pretty but the content's the same: https://github.com/invertase/react-native-google-mobile-ads/blob/main/docs/european-user-consent.mdx

**Comment by mikehardy** [comment]
just realized the docs.page feature to handle html comments is already merged, shipped, and now the URL is working live :-) - fantastic!
