### ISSUE TITLE
[🐛] scriptPhases Issue with RN 69.0

### ISSUE THREAD

**Issue by wjaykim** [invertase/react-native-google-mobile-ads#151]
## Issue

With RN 69.0-rc.0, it looks like something changed with react-native.config.js.
When I tries to build app in ios, following message comes up:
```
Package react-native-google-mobile-ads has been ignored because it contains invalid configuration. Reason: "dependency.platforms.ios.scriptPhases[0]" must be a string
```
And this makes lots of errors in runtime, too.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `admob.json`:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

```ruby
# N/A
```

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **Are you using `TypeScript`?**
  - `Y` & `4.6.4`

</p>
</details>

---

- 👉 Check out [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by wjaykim** [comment]
Seems like this line is the problem:
https://github.com/react-native-community/cli/blob/25eec7c695f09aea0ace7c0b591844fe8828ccc5/packages/cli-config/src/schema.ts#L72
The validation type was object before the commit: 
https://github.com/react-native-community/cli/blob/5530cfc4bdcb8c525f9fde82fb843a3c3e42c514/packages/cli-config/src/schema.ts#L68

**Comment by wjaykim** [comment]
Looks like lots of things removed related to react-native.config.js, maybe we need to find another way to add script phases?

**Comment by mikehardy** [comment]
I'm on this - I am literally in the middle of release testing 0.69 with react-native-firebase part of release testers group and *just* got to this point in the process last night believe it or not :-)

https://github.com/reactwg/react-native-releases/discussions/21#discussioncomment-2657085

I mention react-native-firebase just because we use the exact same configuration machinery, the infra here for config came from there... will update as I have news but hopefully it's in form of a PR today

**Comment by mikehardy** [comment]
PR started here but it's not functional yet, I begged for help from the CLI crew
https://github.com/react-native-community/cli/pull/1611

It's noted on the 0.69 release discussion as a blocker https://github.com/reactwg/react-native-releases/discussions/21#discussioncomment-2779048

**Comment by mikehardy** [comment]
Fix landed on CLI branch, it will need a new react-native 0.69 RC release cut with new release of react-native CLI to use it (may make it to 0.69.0-rc.2, unsure), but there is no longer an action here

**Comment by wjaykim** [comment]
Nice job 👍

**Comment by mikehardy** [comment]
In the end it was just your solution really (moving back to validating as object) plus changes to test fixtures. But we all learned a lot ;-) - thank you for the research above
