### ISSUE TITLE
[🐛] BannerAdSize Conflict

### ISSUE THREAD

**Issue by vo-ngoc-anh-thi** [invertase/react-native-google-mobile-ads#156]
![Screen Shot 2022-06-01 at 2 02 57 PM](https://user-images.githubusercontent.com/99387233/171346859-efb79f2b-e7f3-4cc2-9965-59cfbe6f6dca.png)

When I show two ads: BannerAdSize.BANNER and BannerAdSize.MEDIUM_RECTANGLE at the same time error as shown.

I am using
"react-native-google-mobile-ads": "^5.1.1"

**Comment by wjaykim** [comment]
Hello, Thank you for reporting.
You are using old version of our library, so could you update your library to latest version and see if the bug still exists?

**Comment by wjaykim** [comment]
What React Native version are you using?

**Comment by vo-ngoc-anh-thi** [comment]
> 

`"react": "16.8.6",`
`"react-native": "0.60.4",`

I tried changing the version "react-native": "0.60.5" but the result is the same

**Comment by wjaykim** [comment]
The version of react native you are using is pretty old. The recent release of react native is 0.68 and version 0.60 is released in Aug 2019. I don't know how many apis changed during the period, so we recommend using latest react native version in order to expect perfect functionality. Is there any things blocking you to upgrade the react native version?

**Comment by wjaykim** [comment]
If this issue still exists after upgrading your RN versions, please reopen this issue.

**Comment by chungtvdev** [comment]
> ![Screen Shot 2022-06-01 at 2 02 57 PM](https://user-images.githubusercontent.com/99387233/171346859-efb79f2b-e7f3-4cc2-9965-59cfbe6f6dca.png)
> 
> When I show two ads: BannerAdSize.BANNER and BannerAdSize.MEDIUM_RECTANGLE at the same time error as shown.
> 
> I am using "react-native-google-mobile-ads": "^5.1.1"

Hi. Bạn fix được chưa? cho mình xin code mẫu hiển thị Banner này với
