### ISSUE TITLE
For European User Consent, user approval is requested again after user approval is obtained.

### ISSUE THREAD

**Issue by bloggerklik** [invertase/react-native-google-mobile-ads#157]
## Issue

I am working on European User Consent. I get the user confirmation and when I close and open the application, the confirmation popup appears again. consentInfo.status always returns REQUIRED. Am I doing something wrong?

`React.useEffect(() => {
        asyncUserConsent();
    }, []);

    async function asyncUserConsent() {

        try {
            const consentInfo = await AdsConsent.requestInfoUpdate({
                debugGeography: AdsConsentDebugGeography.EEA,
                testDeviceIdentifiers: ['TEST-DEVICE-HASHED-ID'],
            });

            console.log("STATUS " + consentInfo.status);

            if (consentInfo.isConsentFormAvailable && consentInfo.status === AdsConsentStatus.REQUIRED) {
                const { status } = await AdsConsent.showForm();
            }

        } catch (error) { console.log(error); }

    }`

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `admob.json`:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

```ruby
# N/A
```

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`
N
</p>
</details>

---

- 👉 Check out [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by RoccoDocco** [comment]
Same here, consentInfo.status always returns REQUIRED on both iOS and Android.
Tried it several times by restarting the app after consenting but it still returns REQUIRED every time.

**Comment by mikehardy** [comment]
Sorry for the lack of response on this one, I suppose all the maintainers (and there are 5 of us at the moment!) are swamped for some reason. I know I have been and have not been able to verify this. @birgernass was the original implementer, I would be surprised if they had not gotten it to work in their implementation / testing, perhaps they have an idea?

**Comment by birgernass** [comment]
My best guess is that it's related to Expo, as I haven't tested with it yet. The TC String is stored in the device's shared preferences. You could inspect those and see if the value changes accordingly.

Sadly I am currently hospitalized and won't be able to look into any issues for a few weeks, I'm sorry about that.

**Comment by mikehardy** [comment]
Oh my goodness - I'm so sorry to hear that @birgernass - forget software, take care of your hardware. Best wishes for good health

@RoccoDocco / @bloggerklik in case you are not familiar, easiest way to inspect shared prefs of an android app is likely to plug the device in and connect to it via android simulator, you may browse the device filesystem that way in order to find the prefs file and open it up for a look

**Comment by Hknzbyn** [comment]
+1
