### ISSUE TITLE
Inspecting consent choices - Which of the approval selections must be true for Google to show ads?

### ISSUE THREAD

**Issue by bloggerklik** [invertase/react-native-google-mobile-ads#160]
Which of the approval selections must be true for Google to show ads?

https://docs.page/invertase/react-native-google-mobile-ads/european-user-consent

`const {
  activelyScanDeviceCharacteristicsForIdentification,
  applyMarketResearchToGenerateAudienceInsights,
  createAPersonalisedAdsProfile,
  createAPersonalisedContentProfile,
  developAndImproveProducts,
  measureAdPerformance,
  measureContentPerformance,
  selectBasicAds,
  selectPersonalisedAds,
  selectPersonalisedContent,
  storeAndAccessInformationOnDevice,
  usePreciseGeolocationData,
} = await AdsConsent.getUserChoices();`

**Comment by wjaykim** [comment]
It depends on countries(where your app is servicing)' laws. It is your responsibility to find them and ensure your app is legally following them. Since it's not related to this library's maintaining issue, we're closing this.
