### ISSUE TITLE
Unhandled promise rejection: Error: InterstitialAd.show() The requested InterstitialAd has not loaded and could not be shown

### ISSUE THREAD

**Issue by DoneDeal0** [invertase/react-native-google-mobile-ads#161]
## Issue

I display a list of addresses. Each time the user clicks on an address, an ad must be shown. Once the ad is closed, the user is automatically redirected to a sub screen where the address is shown on a map.

I've used the `useInterstitialAd` and `useRewardedAd` hooks. It always works fine the first time the user clicks on an address. 

But when he comes back from the `Map` screen to the `AddressesList` screen, the ad never shows up again when he clicks on a new address. It's like the ad is only loaded once, and can never be shown again afterwards.

The error is:

> Unhandled promise rejection: Error: InterstitialAd.show() The requested InterstitialAd has not loaded and could not be shown

I would like to show an ad each time the user clicks on an address.

Here is the wrapper I've written around these hook:

```js
import { useEffect, useState } from "react";
import { NavigationProp } from "@react-navigation/native";
import { TestIds, useInterstitialAd } from "react-native-google-mobile-ads";
import { Routes } from "routes";

const adsId = __DEV__
  ? TestIds.INTERSTITIAL
  : "ca-app-pub-blabla";

export default function useAds( navigation: NavigationProp<any> ) {
  const { isLoaded, isClosed, load, show } = useInterstitialAd(adsId, {
    requestNonPersonalizedAdsOnly: true,
  });
  const [navData, setNavData] = useState<string>("");

  useEffect(() => {
    load();
  }, [load]);

  useEffect(() => {
    if (isClosed) {
      navigation.navigate(Routes.Map, { address: navData.address });
    }
  }, [address, isClosed, navigation]);

  const onPress = async (address: string) => {
    if (isLoaded) {
      setNavData( address);
      return show();
    } else {
      return navigation.navigate(Routes.Map, { address });
    }
  };

  return {
    onPress,
  };
}

```

How to fix this?

**Comment by wjaykim** [comment]
Try wrapping onPress with `useCallback`.

**Comment by DoctorJohn** [comment]
To me it looks like the ad is actualy just loaded once and thus can only be shown once. Maybe adding something like the following could work?

```js
  React.useEffect(() => {
    if (isClosed) {
      load();
    }
  }, [isClosed, load]);
```

**Comment by DoneDeal0** [comment]
Indeed, the ad is only loaded once. The loaded state is never reset after the promise resolves. This should be fixed in a pull request. Another option would be to expose a function that could reset the state programatically.

I eventually juste added the condition isLoaded && isOpened, so I make sure not to load the ad more than once.

**Comment by VishnuBhanderi** [comment]
@DoneDeal0  I am facing same issue with Rewarded Ads and RewardedInterstitial Ads.

**Comment by wjaykim** [comment]
> Indeed, the ad is only loaded once. The loaded state is never reset after the promise resolves.

This is intended behavior. You need to load ad again using `load` function after the ad is used(opened and closed). If the hook programmatically reloads the ad right after the ad is closed, the states(such as `isClosed`) will be reset right after the ad is closed, thus developers cannot handle ad's state after the ad is closed(`isClosed` never becomes to `true`).

**Comment by wjaykim** [comment]
Also, the `isOpened` state is remained `true` even after the ad is closed unless new ad is requested. It is documented in [documentation](https://docs.page/invertase/react-native-google-mobile-ads/displaying-ads-hook#show-the-ad).
So `isOpened` does not means if the ad is opened currently, but means if the ad had been opened.

**Comment by wjaykim** [comment]
If you want to load ad again, you can do like this:
```js
useEffect(() => {
    if (isClosed) {
      navigation.navigate(Routes.Map, { address: navData.address });
      load();
    }
  }, [address, isClosed, load, navigation]);
```

**Comment by monti-python** [comment]
Facing the same issue here... 

It seems ad objects cannot be reused (i.e. re-loaded): https://github.com/invertase/react-native-google-mobile-ads/blob/5d2048b530b798740c9fed392772568f909dd6b2/src/ads/MobileAd.ts#L176

Even if the state within the hook gets reset, the ad object itself won't load more than once, so you need to create a new ad instance...

**Comment by wjaykim** [comment]
> Facing the same issue here... 
> 
> 
> 
> It seems ad objects cannot be reused (i.e. re-loaded): https://github.com/invertase/react-native-google-mobile-ads/blob/5d2048b530b798740c9fed392772568f909dd6b2/src/ads/MobileAd.ts#L176
> 
> 
> 
> Even if the state within the hook resets, the ad object itself won't load more than once, so you need to create a new ad instance...

Please, try my solution I commented above. The hook won't reload ad for you. You have to load the ad again manually after the ad is used.

**Comment by ManhVuAmela** [comment]
@wjaykim I can reload the ads manually after the previous ad is used, But I can't relead the new ad if the previous one is an error? Do you have any suggestion, thanks

**Comment by monti-python** [comment]
Hi @wjaykim, Thanks a lot for your reply. Indeed your solution works when triggering the `load`, `show` functions imperatively (e.g. via `Button` component). However, when passing them within a callback the behavior is not as expected and the ads won't show neither load. To illustrate it, below is an example of what I'm trying to achieve. The ads are shown and reload properly when using the buttons. However, they don't show up when the app comes back from the background, which would be the expected behavior as part of the `handleAppStateChange`.

``` js
import React, { useEffect, useRef } from 'react';
import {AppState, StyleSheet, StatusBar, View, Button} from "react-native";
import { MobileAds, useInterstitialAd, TestIds } from 'react-native-google-mobile-ads';

const adUnit = TestIds.INTERSTITIAL;
const requestOptions = {};


export default function App() {

    const { isLoaded, isClosed, load, show } = useInterstitialAd(adUnit, requestOptions)
    const appState = useRef(AppState.currentState);
    
    const handleAppStateChange = async (nextAppState) => {
        if (appState.current.match(/inactive|background/) && nextAppState === 'active') {
            console.log('App has come to the foreground! Loading ad...');
            show();
            console.log('Ad should have been shown.');
        }
        else if (nextAppState === 'background') {
            console.log('App is going to the background')
        }
        else {
            console.log('inactive-state transition (iOS)')
        }
        appState.current = nextAppState;
    };


    initApp = async () => {
        StatusBar.setBarStyle('light-content');
        await MobileAds().initialize();
        load();

    }

    useEffect(() => {
      initApp();
      const sub = AppState.addEventListener('change', handleAppStateChange);
      return () => {sub.remove();}
    }, []);
  
    useEffect(() => {
      if (isClosed) {
        console.log("Reloading ad...");
        load();
      }
    }, [isClosed])

    return (
        <View 
            style={styles.app}
        >
            <View style={styles.container}>
                <Button 
                    title="Show Ad!"
                    color="#0ff233"
                    onPress={show}
                />
                <Button 
                    title="Load Ad!"
                    color="#0ff233"
                    onPress={load}
                />                        
            </View>

        </View>
    );
}

const styles = StyleSheet.create({
    app: {
        flex: 1,
        backgroundColor: '#646464',
    },
    container: {
        flex: 1,
        justifyContent: 'center',
        marginHorizontal: 16,
    },
});

```

**Comment by monti-python** [comment]
I could make it work by making the effect listen to change in the show function, however this is somehow surprising. I'd expect the `show`, `load` functions to be instantiated just once...

``` js
import React, { useEffect, useRef } from 'react';
import {AppState, StyleSheet, StatusBar, View, Button} from "react-native";
import { MobileAds, useInterstitialAd, TestIds } from 'react-native-google-mobile-ads';

const adUnit = TestIds.INTERSTITIAL;
const requestOptions = {};


export default function App() {

    const { isLoaded, isClosed, load, show } = useInterstitialAd(adUnit, requestOptions)
    const appState = useRef(AppState.currentState);
    
    const handleAppStateChange = async (nextAppState) => {
        if (appState.current.match(/inactive|background/) && nextAppState === 'active') {
            console.log('App has come to the foreground! Loading ad...');
            show();
            console.log('Ad should have been shown.');
        }
        else if (nextAppState === 'background') {
            console.log('App is going to the background')
        }
        else {
            console.log('inactive-state transition (iOS)')
        }
        appState.current = nextAppState;
    };


    initApp = async () => {
        StatusBar.setBarStyle('light-content');
        await MobileAds().initialize();
        load();

    }

    useEffect(() => {
      initApp();
      const sub = AppState.addEventListener('change', handleAppStateChange);
      return () => {sub.remove();}
    }, [show]);
  
    useEffect(() => {
      if (isClosed) {
        load();
        console.log("Reloading ad...");
      }
    }, [isClosed])

    return (
        <View 
            style={styles.app}
        >
            <View style={styles.container}>
                <Button 
                    title="Show Ad!"
                    color="#0ff233"
                    onPress={show}
                />
                <Button 
                    title="Load Ad!"
                    color="#0ff233"
                    onPress={load}
                />                        
            </View>

        </View>
    );
}

const styles = StyleSheet.create({
    app: {
        flex: 1,
        backgroundColor: '#646464',
    },
    container: {
        flex: 1,
        justifyContent: 'center',
        marginHorizontal: 16,
    },
});

```

**Comment by wjaykim** [comment]
@monti-python Always follow hook rules of react. You can lessen the human errors like those case by using [eslint-plugin-react-hooks](https://www.npmjs.com/package/eslint-plugin-react-hooks)(The plugin is included in [react native's default eslint rule](@react-native-community/eslint-config)).

Also, if you want to display ad when user get back to foreground, you can use app open ad type, FYI.

**Comment by birdofpreyru** [comment]
There is no need at all to mess-up with the state to reload interstitials, you can do just
```js
if (interstitial.loaded) await interstitial.show();
else {
  // It might be a good idea to show a fallback ad here,
  // e.g. in my case if no AdMob interstitial ad is loaded,
  // I fallback to show a dummy fully screen ad, inviting users
  // to subscribe for ads-free use of my app.
}

// In my code there is always 1 sec interval between ".show()" and the next line, but probably no need for extra wait here.
interstitial.load();
```

**Comment by deggertsen** [comment]
> There is no need at all to mess-up with the state to reload interstitials, you can do just
> 
> ```js
> if (interstitial.loaded) await interstitial.show();
> else {
>   // It might be a good idea to show a fallback ad here,
>   // e.g. in my case if no AdMob interstitial ad is loaded,
>   // I fallback to show a dummy full screen ad, inviting users
>   // to subscribe for ads-free use of my app.
> }
> 
> // In my code there is always 1 sec interval between ".show()" and the next line,
> // but probably no need for extra wait here, and then no need for "if" on the next line.
> if (!interstitial.loaded) interstitial.load();
> ```

I didn't know that `loaded` is a method that we can use. I really wish this had been in the readme documentation. Would have saved us a lot of problems! Thanks so much for sharing!

**Comment by birdofpreyru** [comment]
Hmm... no idea how do I know about `loaded` prop. Probably it was in older docs, got lost on the way, and should be re-added to the docs? @mikehardy 

Though, as of the current implementation, that prop is available for all ads that inherit to `MobileAd`, thus these classes have it:
- AppOpenAd
- InterstitialAd
- RewardedAd
- RewardedInterstitialAd

**Comment by mikehardy** [comment]
I'm traveling so this is really delayed, but I actually looked at it a few days ago when it first went through. I actually had trouble locating it in the source! So, it's hard to find. And near as I can tell it is not in our example either. @wjaykim is `loaded` property of MobileAd super class an intended way to program this stuff? :thinking: if so a PR to the docs + example showing it might be useful

**Comment by mikehardy** [comment]
Had a chance to roll through some release mode issues and I can verify that in android on release mode at least (maybe other cases), the ad events are for some reason not coming through to the listener, which is related to this.

I've added some code to the example in a PR #244

**Comment by jbravo94** [comment]
Hi,
since i stumbled across the same error message and i had also troubles finding a solution, i share my working one - maybe somebody can use it:

`
  const showAd = () => {
    const rewarded = RewardedAd.createForAdRequest(adUnitId, {
      requestNonPersonalizedAdsOnly: true,
      keywords: ['fashion', 'clothing'],
    });

    const unsubscribeLoaded = rewarded.addAdEventListener(RewardedAdEventType.LOADED, () => {
      rewarded.show();
    });

    const unsubscribeEarned = rewarded.addAdEventListener(
      RewardedAdEventType.EARNED_REWARD,
      reward => {
          console.log("Callback called!");
      },
    );

    rewarded.load();
  }
`

**Comment by victorroatt** [comment]
Has anyone found a solution? For me, the ad never loads and therefore never displays.

**Comment by DoctorJohn** [comment]
> Has anyone found a solution? For me, the ad never loads and therefore never displays.

The related underlying code has changed since this issue was reported. I would recommend filling a new issue with all the relevant information (especially relevant code snippets and the library version you're using) or at least provide that information here.

**Comment by dprajapati1179** [comment]
Anyone can please share the code for showing multiple ads with the click of a button
I am having the same issue first ad lodes perfectly but other ads not loading and while calling shows my app is crashing

**Comment by kusche12** [comment]
+1

**Comment by pkyipab** [comment]
`
const interstitial = InterstitialAd.createForAdRequest(adUnitId, {
  requestNonPersonalizedAdsOnly: true,
  keywords: ["fashion", "clothing"],
});

export default function useAds() {
  useEffect(() => {
    const unsubscribe = interstitial.addAdEventListener(AdEventType.CLOSED, () => {
      interstitial.load();
    });

    interstitial.load();

    return unsubscribe;
  }, []);

  const onShowInterstitial = () => {
    if (interstitial.loaded) {
      interstitial.show();
    }
  };

  return { onShowInterstitial };
}
`

**Comment by pkyipab** [comment]
`
const interstitial = InterstitialAd.createForAdRequest(adUnitId, {
  requestNonPersonalizedAdsOnly: true,
  keywords: ["fashion", "clothing"],
});

export default function useAds() {
  useEffect(() => {
    const unsubscribe = interstitial.addAdEventListener(AdEventType.CLOSED, () => {
      interstitial.load();
    });

    interstitial.load();

    return unsubscribe;
  }, []);

  const onShowInterstitial = () => {
    if (interstitial.loaded) {
      interstitial.show();
    }
  };

  return { onShowInterstitial };
}
`

**Comment by usmanr626** [comment]
> Hi, since i stumbled across the same error message and i had also troubles finding a solution, i share my working one - maybe somebody can use it:
> 
> ```
> const showAd = () => {
>     const rewarded = RewardedAd.createForAdRequest(adUnitId, {
>         requestNonPersonalizedAdsOnly: true,
>         keywords: ['fashion', 'clothing'],
>     });
> 
>     const unsubscribeLoaded = rewarded.addAdEventListener(RewardedAdEventType.LOADED, () => {
>         rewarded.show();
>     });
> 
>     const unsubscribeEarned = rewarded.addAdEventListener(
>         RewardedAdEventType.EARNED_REWARD,
>         reward => {
>             console.log("Callback called!");
>         },
>     );
> 
>     rewarded.load();
> }
> ```

Worked,  Thanks a lot :)

**Comment by A7medKhalifa** [comment]
Worked, Thanks a lot

**Comment by iriemomoka** [comment]
I solved it this way.

`
const rewardedInterstitial = RewardedInterstitialAd.createForAdRequest(adUnitId, {
  requestNonPersonalizedAdsOnly: true,
});

useEffect(() => {
    
    const unsubscribeLoaded = rewardedInterstitial.addAdEventListener(
      RewardedAdEventType.LOADED,
      () => {},
    );

    const unsubscribeEarned = rewardedInterstitial.addAdEventListener(
      RewardedAdEventType.EARNED_REWARD,
      reward => {},
    );

    rewardedInterstitial.load();

    return () => {
      unsubscribeLoaded();
      unsubscribeEarned();
    };

  }, []);

return (
  <Button
    title="Show Rewarded Interstitial Ad"
    onPress={() => {
      if (rewardedInterstitial.loaded) {
        rewardedInterstitial.show();
      } else {
        await rewardedInterstitial.load();

        let isLoaded = false;

        let interval = setInterval(async () => {
          if (rewardedInterstitial.loaded) {
            console.log('Reload Complete.');
            rewardedInterstitial.show();
            clearInterval(interval);
            isLoaded = true;
          } else {
            console.log('Still reloading.');
          }
        }, 1000);

        // Clear after 15 seconds.
        setTimeout(() => {
          clearInterval(interval);
          if (!isLoaded) {
            console.log('Timeout: 15 seconds elapsed');
          }
        }, 15000);

      }
    }}
  />
);

`

**Comment by iriemomoka** [comment]
`const rewardedInterstitial = RewardedInterstitialAd.createForAdRequest(adUnitId, {
  requestNonPersonalizedAdsOnly: true,
});

useEffect(() => {
    
    const unsubscribeLoaded = rewardedInterstitial.addAdEventListener(
      RewardedAdEventType.LOADED,
      () => {},
    );

    const unsubscribeEarned = rewardedInterstitial.addAdEventListener(
      RewardedAdEventType.EARNED_REWARD,
      reward => {},
    );

    rewardedInterstitial.load();

    return () => {
      unsubscribeLoaded();
      unsubscribeEarned();
    };

  }, []);

return (
  <Button
    title="Show Rewarded Interstitial Ad"
    onPress={() => {
      if (rewardedInterstitial.loaded) {
        rewardedInterstitial.show();
      } else {
        await rewardedInterstitial.load();

        let isLoaded = false;

        let interval = setInterval(async () => {
          if (rewardedInterstitial.loaded) {
            console.log('Reload Complete.');
            rewardedInterstitial.show();
            clearInterval(interval);
            isLoaded = true;
          } else {
            console.log('Still reloading.');
          }
        }, 1000);

        // Clear after 15 seconds.
        setTimeout(() => {
          clearInterval(interval);
          if (!isLoaded) {
            console.log('Timeout: 15 seconds elapsed');
          }
        }, 15000);

      }
    }}
  />
);`

**Comment by iriemomoka** [comment]
This solved the problem.

 `if (rewardedInterstitial.loaded) {
    rewardedInterstitial.show();
  } else {
    await rewardedInterstitial.load();
    let isLoaded = false;
    let interval = setInterval(async () => {
      if (rewardedInterstitial.loaded) {
        console.log('Reload Complete.');
        rewardedInterstitial.show();
        clearInterval(interval);
        isLoaded = true;
      } else {
        console.log('Still reloading.');
      }
    }, 1000);

  // Clear after 15 seconds.
    setTimeout(() => {
      clearInterval(interval);
      if (!isLoaded) {
        console.log('Timeout: 15 seconds elapsed');
      }
    }, 15000);
  }`

**Comment by EtvWinReactNative** [comment]
import React, { useEffect } from "react";
import {
  View,
  Text,
  SafeAreaView,
  StyleSheet,
  TouchableOpacity,
} from "react-native";

import admob, {
  MaxAdContentRating,
} from "react-native-google-mobile-ads";

import {
  InterstitialAd,
  RewardedAd,
  RewardedAdEventType,
  TestIds,
  AdEventType,
  BannerAd,
  BannerAdSize,
  
} from "react-native-google-mobile-ads";

admob()
  .setRequestConfiguration({
    // Update all future requests suitable for parental guidance
    maxAdContentRating: MaxAdContentRating.PG,

    // Indicates that you want your content treated as child-directed for purposes of COPPA.
    tagForChildDirectedTreatment: true,

    // Indicates that you want the ad request to be handled in a
    // manner suitable for users under the age of consent.
    tagForUnderAgeOfConsent: true,
  })
  .then(() => {
    // Request config successfully set!
  });

const interstialAdUnitId = __DEV__
  ? TestIds.INTERSTITIAL
  : "ca-app-pub-8363970344320746/2547838027";

const interstitial = InterstitialAd.createForAdRequest(
  interstialAdUnitId,
  {
    requestNonPersonalizedAdsOnly: true,
    keywords: ["fashion", "clothing"],
  }
);

const rewardedAdUnitId = __DEV__
  ? TestIds.REWARDED
  : "ca-app-pub-8363970344320746/7062917668";

const rewarded = RewardedAd.createForAdRequest(
  rewardedAdUnitId,
  {
    requestNonPersonalizedAdsOnly: true,
    keywords: ["fashion", "clothing"],
  }
);

const bannerAdUnitId = __DEV__
  ? TestIds.BANNER
  : "ca-app-pub-8363970344320746/9472339023";


  const App = () => {
    useEffect(() => {
      // Event listener for interstitial Ads
      const interstitialAdEventListener = () => {
        console.log("Interstitial Ad Loaded");
      };
  
      // Start loading the interstitial straight away
      interstitial.load();
  
      // Add event listener for interstitial ad loaded
      interstitial.addAdEventListener(AdEventType.LOADED, interstitialAdEventListener);
  
      // Event listener for rewarded Ads
      const rewardedAdEventListener = (type, error, reward) => {
        if (type === RewardedAdEventType.LOADED) {
          console.log("Rewarded Ad Loaded");
        }
  
        if (type === RewardedAdEventType.EARNED_REWARD) {
          console.log("User earned reward of ", reward);
        }
      };
  
      // Start loading the rewarded ad straight away
      rewarded.load();
  
      // Add event listener for rewarded ad loaded and reward earned
      rewarded.addAdEventListener(RewardedAdEventType.LOADED, rewardedAdEventListener);
      rewarded.addAdEventListener(RewardedAdEventType.EARNED_REWARD, rewardedAdEventListener);
  
      // Unsubscribe from events on unmount
      return () => {
        interstitial.removeEventListener(AdEventType.LOADED, interstitialAdEventListener);
        rewarded.removeEventListener(RewardedAdEventType.LOADED, rewardedAdEventListener);
        rewarded.removeEventListener(RewardedAdEventType.EARNED_REWARD, rewardedAdEventListener);
      };
    }, []);

  return (
    <SafeAreaView style={styles.container}>
      <Text style={styles.heading}>
        React Native + AdMob Integration{"\n\n"}
        www.aboutreact.com
      </Text>
      <View
        style={{
          flex: 1,
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <TouchableOpacity
          style={styles.buttonStyle}
          activeOpacity={0.5}
          onPress={() => interstitial.show()}
        >
          <Text style={styles.buttonTextStyle}>
            Show Interstitial Ad
          </Text>
        </TouchableOpacity>
        <TouchableOpacity
          style={styles.buttonStyle}
          activeOpacity={0.5}
          onPress={() => rewarded.show()}
        >
          <Text style={styles.buttonTextStyle}>
            Show Rewarded Ad
          </Text>
        </TouchableOpacity>
      </View>
      <BannerAd
        unitId={bannerAdUnitId}
        size={BannerAdSize.ANCHORED_ADAPTIVE_BANNER}
        requestOptions={{
          requestNonPersonalizedAdsOnly: true,
        }}
      />
    </SafeAreaView>
  );
};

export default App;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "white",
    padding: 16,
  },
  heading: {
    fontSize: 20,
    textAlign: "center",
    marginTop: 30,
  },
  buttonStyle: {
    minWidth: 300,
    backgroundColor: "#7DE24E",
    borderWidth: 0,
    color: "#FFFFFF",
    borderColor: "#7DE24E",
    height: 40,
    alignItems: "center",
    borderRadius: 30,
    marginLeft: 35,
    marginRight: 35,
    marginTop: 20,
    marginBottom: 25,
  },
  buttonTextStyle: {
    color: "#FFFFFF",
    paddingVertical: 10,
    fontSize: 16,
  },
});


Same issue iam facing iam unable to load the ads and its showing   Error: InterstitialAd.show() The requested InterstitialAd has not loaded and could not be shown., js engine: hermes

**Comment by Saliheen** [comment]
**Please try solution. It is working**

`import {View, StyleSheet, TouchableOpacity, Button} from 'react-native';
import {useEffect, useState} from 'react';
import {
  InterstitialAd,
  TestIds,
  AdEventType,
} from 'react-native-google-mobile-ads';

const TestAds = props => {
  const [isAdViewHidden, setIsAdViewHidden] = useState(false);

  useEffect(() => {
    setIsAdViewHidden(false);
  }, [isAdViewHidden]);

  return (
    <View style={styles.container}>
      {!isAdViewHidden && (
        <InterstitialAdComponent
          onShowCallback={() => setIsAdViewHidden(true)}
        />
      )}
    </View>
  );
};

const InterstitialAdComponent = ({onShowCallback}) => {
  const adUnitId = TestIds.INTERSTITIAL;
  const interstitial = InterstitialAd.createForAdRequest(adUnitId, {
    keywords: ['fashion', 'clothing'],
  });

  useEffect(() => {
    const unsubscribe = interstitial.addAdEventListener(
      AdEventType.LOADED,
      () => {
        console.log('Loaded');
      },
    );

    // Start loading the interstitial straight away
    interstitial.load();

    // Unsubscribe from events on unmount
    return unsubscribe;
  }, []);

  useEffect(() => {
    const unsubscribe = interstitial.addAdEventListener(
      AdEventType.CLOSED,
      () => {
        console.log('closed');
        onShowCallback();
      },
    );

    // Unsubscribe from events on unmount
    return unsubscribe;
  }, []);

  return (
    <View>
      <Button
        title="Show Interstitial"
        onPress={() => {
          try {
            interstitial.show();
          } catch (error) {
            console.log(error);
          }
        }}
      />
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingVertical: 200,
  },
});

export default TestAds;
`
