### ISSUE TITLE
[🐛] GDPR User consent update failed

### ISSUE THREAD

**Issue by DanielYapiko** [invertase/react-native-google-mobile-ads#162]
Hello all,

I am trying to implement the GDPR Consent form for my app and I am struggling with Android version. For iOS it works smoothly, and it shows the modal without any issue, however on android I am getting an error code on the AdsConsent.requestInfoUpdate() method.

I am using the latest version of the library and I am not sure what I am missing from the installation, I have followed everything and configured all what I think is needed. The error I get is:

{"nativeStackAndroid":[],"userInfo":{"message":"Invalid response from server.","code":"consent-update-failed"},"message":"Invalid response from server.","code":"consent-update-failed"}

`AdsConsent.requestInfoUpdate({
            debugGeography: AdsConsentDebugGeography.EEA
          })`

And that's the code that provoked the issue. I am not sure what is happening, the only thing that I could think is doing it is that I have not upload the app into Google Store yet, as it's under development... any ideas?

**Comment by flolege** [comment]
I get the same issue in my expo dev build. Did you figure it out?

**Comment by flolege** [comment]
For all the poor souls having the same error: In my case it was a pending verification status, visible in Google AdMob - Home:
![image](https://user-images.githubusercontent.com/42407173/191781492-e64ff910-6f60-4377-881c-06bb5b7591b8.png)

After it switched to verified:
![image](https://user-images.githubusercontent.com/42407173/191781638-899f8afb-8f92-4faa-807b-574ae76515b6.png)

It worked!

**Comment by mikehardy** [comment]
If this is still an issue for people, we can reopen but it appears to be stale / not actionable
