### ISSUE TITLE
[📚] Advertising ID permission on Android 13+

### ISSUE THREAD

**Issue by RodolfoGS** [invertase/react-native-google-mobile-ads#169]
## Documentation Feedback

Hi,

I'm not sure if I need to add the new permission for advertising ID on Android 13+ or if it was already added in the current SDK.

I didn't find any reference to this in the documentation.

I've this message in my Google Play Console:

> **New Advertising ID declaration form coming to Console**
> 
> Starting July, you'll need to tell us in Play Console if your app uses an advertising identifier. This will let us provide helpful feedback if your release is at risk of having an advertising identifier zeroed out. You will not be able to create releases targeting Android 13 until you complete the advertising ID declaration form.
> 
> As a reminder, apps that target API level 33 (Android 13) or later and use advertising ID must include the normal permission com.google.android.gms.permission.AD_ID in their AndroidManifest.xml. This will prevent your advertising identifier from zeroing out. If you do not declare the permission in your manifest file, or if you use an SDK that omits the permission from their library manifest, this may impact your advertising and analytics use cases.

Do I need to add the `com.google.android.gms.permission.AD_ID` to my `AndroidManifest.xml`? Or it was already declared in the SDK?

Thanks,

---

- 👉 Check out [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Interesting - I haven't gone through the Android 13 change list with an eye towards this module yet.
Here's the fastest way to determine it to your own satisfaction - either of two ways, both involve AndroidStudio

1- open the android folder in AndroidStudio, surf down to `app/src/main/AndroidManifest.xml` and with that open in the editor pane look near the bottom (I think) of the pane and check "Merged Manifest" - scan for the permission to see if the underlying SDK added it

2- same idea, different method, I believe after doing a command line build like `npx react-native run-android` you can use AndroidStudio to open `android/app/build/outputs/apk/debug/app-debug.apk` and surf around to find the fully-merged AndroidManifest.xml that way and can check it

The upstream documentation indicates it should not be necessary with underlying SDK >= 20.4.0:

https://developers.google.com/admob/android/quick-start (after expanding the optional 'Android 13' section)

> If your app uses the Google Mobile Ads SDK version 20.4.0 or higher, you can skip this step since the SDK automatically declares the com.google.android.gms.permission.AD_ID permission and is able to access the Advertising ID whenever it's available.

We meet that requirement 

https://github.com/invertase/react-native-google-mobile-ads/blob/5d2048b530b798740c9fed392772568f909dd6b2/package.json#L52

**Comment by RodolfoGS** [comment]
@mikehardy thank you so much for the clarification. I checked your methods and its right, the permission is added automatically by the SDK. Again, thank you so much for your help!
