### ISSUE TITLE
Sometimes has no-fill error on IOS

### ISSUE THREAD

**Issue by ManhVuTien** [invertase/react-native-google-mobile-ads#170]
## Issue

I use Rewarded Ads with TestIDs but sometimes I have an error no-fill on ios or no-config on android. I must re-open the app 2 - 3 times and it is ok.

Do I must add that device test or change app id "ca-app-pub-xxxx" to testID?

Thanks
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `admob.json`:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

```ruby
# N/A
```

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there - I am unsure, our best troubleshooting is here https://docs.page/invertase/react-native-google-mobile-ads/common-reasons-for-ads-not-showing

seems odd that you have a no-config sometimes but not all times. Not enough information to go on here though

You don't indicate what you've tried at all. Any logs. Any versions, nothing informative https://stackoverflow.com/help/how-to-ask
You don't show code that could reproduce it, that's a minimal App.js drop in or similar https://stackoverflow.com/help/minimal-reproducible-example
