### ISSUE TITLE
[🐛] Cannot read properties of undefined: eventsNotifyReady

### ISSUE THREAD

**Issue by brozz-io** [invertase/react-native-google-mobile-ads#171]
Hello,
I tried to use InterstitialAd, like in the example from documentation, but when I try to .load() in componentDidMount(), this error appears

```
TypeError: Cannot read properties of undefined (reading 'eventsNotifyReady')
at GANativeEventEmitter.addListener (C:\projects\onlife\node_modules\react-native-google-mobile-ads\src\internal\GoogleMobileAdsNativeEventEmitter.ts:36:19)
 at subscribeToNativeModuleEvent (C:\projects\onlife\node_modules\react-native-google-mobile-ads\src\internal\registry\nativeModule.ts:146:39)
at initialiseNativeModule (C:\projects\onlife\node_modules\react-native-google-mobile-ads\src\internal\registry\nativeModule.ts:124:7)
at getNativeModule (C:\projects\onlife\node_modules\react-native-google-mobile-ads\src\internal\registry\nativeModule.ts:203:10)
at MobileAdsModule.get (C:\projects\onlife\node_modules\react-native-google-mobile-ads\src\internal\Module.ts:52:26)
    at InterstitialAd.load (C:\projects\onlife\node_modules\react-native-google-mobile-ads\src\ads\MobileAd.ts:181:40)
    at MainRoutes.componentDidMount (C:\projects\onlife\src\components\main\MainRoutes.tsx:190:20)
    at commitLifeCycles (C:\projects\onlife\node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:16521:22)
    at commitLayoutEffects (C:\projects\onlife\node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:19216:7)
    at Object.invokeGuardedCallbackProd (C:\projects\onlife\node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:93:10)
```

Thank you

**Comment by mikehardy** [comment]
Smells like "I have installed the module but not rebuilt the native code, so the native module doesn't exist in my running app, and the javascript can't find it so throws an error on undefined"

**Comment by brozz-io** [comment]
I am sorry, may you give more informations about the issue? What do you advice me to do to solve it? I am using Expo. By rebuilding the native code, do you mean to rebuild the code of android?

**Comment by mikehardy** [comment]
only eas will work
i think prebuild is the step?
unsure i don't personally use expo

**Comment by brozz-io** [comment]
I tried it, but it gets me to another error, during the build

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file 'C:\projects\onlife\node_modules\react-native-google-mobile-ads\android\build.gradle' line: 59

* What went wrong:
A problem occurred evaluating project ':react-native-google-mobile-ads'.
> Cannot get property 'googleMobileAdsJson' on extra properties extension as it does not exist

I searched for this problem everywhere, but unfortunately, I can't find out where is the problem

**Comment by mikehardy** [comment]
Have you tried https://github.com/invertase/react-native-google-mobile-ads/issues/155#issuecomment-1142490214 ?

**Comment by brozz-io** [comment]
I've tried to build it, following the instructions of the person from the link above, but it gives me these error logs during the build

![image](https://user-images.githubusercontent.com/73560201/174281985-62ea501a-7283-463f-9a17-f99ae4d70011.png)

**Comment by mikehardy** [comment]
Unfamiliar with that error sorry (also the text is really really hard to read in an image - github is a text-first environment please post text inside triple-backticks whenever possible for us folks trying to assist while on mobile devices)

Looks to me like you've got a duplicate key in your AndroidManifest.xml and the error message is *extremely* prescriptive though. I advise following the error message's instructions and/or checking on stackoverflow for similar.

**Comment by brozz-io** [comment]
I will try to find out how to change the manifest. And yes, sorry for the image, here is the code in text

[stderr] 
/home/expo/workingdir/build/android/app/src/debug/AndroidManifest.xml:18:85-105 Error:
[stderr] 
	Attribute meta-data#com.google.android.gms.ads.DELAY_APP_MEASUREMENT_INIT@value value=(true) from AndroidManifest.xml:18:85-105
[stderr] 
	is also present at [:react-native-google-mobile-ads] AndroidManifest.xml:19:13-34 value=(false).
[stderr] 
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:18:5-107 to override.
[stderr] 
FAILURE: Build failed with an exception.
[stderr] 
* What went wrong:
[stderr] 
Execution failed for task ':app:processDebugMainManifest'.
[stderr] 
> Manifest merger failed : Attribute meta-data#com.google.android.gms.ads.DELAY_APP_MEASUREMENT_INIT@value value=(true) from AndroidManifest.xml:18:85-105
[stderr] 
  	is also present at [:react-native-google-mobile-ads] AndroidManifest.xml:19:13-34 value=(false).
[stderr] 
  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:18:5-107 to override.
[stderr] 
* Try:
[stderr] 
> Run with --stacktrace option to get the stack trace.
[stderr] 
> Run with --info or --debug option to get more log output.
[stderr] 
> Run with --scan to get full insights.
[stderr] 
* Get more help at https://help.gradle.org
[stderr] 
BUILD FAILED in 3m 40s
Unable to list file systems to check whether they can be watched. The whole state of the virtual file system has been discarded. Reason: Could not query file systems: could not open mount file (errno 2: No such file or directory)
Error: Gradle build failed with unknown error. Please see logs for the "Run gradlew" phase.

**Comment by mikehardy** [comment]
Remove this from your `android/app/src/main/AndroidManifest.xml`:

> Manifest merger failed : Attribute meta-data#com.google.android.gms.ads.DELAY_APP_MEASUREMENT_INIT@value value=(true) from AndroidManifest.xml:18:85-105

We include it already and allow you to toggle it on or off from app.json, in a way that works on ios and android

like so

https://github.com/invertase/react-native-google-mobile-ads/blob/abd8db61ab32cef3a6d5ded0c21248ff220606f0/RNGoogleMobileAdsExample/app.json#L7
