### ISSUE TITLE
[🐛] v7.0.0 breaks Android builds

### ISSUE THREAD

**Issue by birdofpreyru** [invertase/react-native-google-mobile-ads#180]
I believe, because in the commit fdd91f3703e597c445cafce87cd47eeb67106345 `android/build.gradle` got added the line
```
apply plugin: 'kotlin-android'
```
with
```
classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${safeExtGet('kotlinVersion', '1.6.10')}"
```
added inside `if (project == rootProject) {` block.

So, when a host project is build, it ends up with 
```
1: Task failed with an exception.
-----------
* Where:
Build file '/my/project/path/node_modules/react-native-google-mobile-ads/android/build.gradle' line: 23

* What went wrong:
A problem occurred evaluating project ':react-native-google-mobile-ads'.
> Plugin with id 'kotlin-android' not found.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

```
unless the classpath is added explicitly there.

So, I don't know what that plugin does, but I guess either the plugin should be applied under the same ``if (project == rootProject) {` condition, or the classpath for the plugin should be moved out of that `if` block.

**Comment by mikehardy** [comment]
Hmm that's unfortunate :thinking: - how does the example work then? This did not turn up when I was working on the example

There are other modules that use kotlin, specifically a reference might be https://github.com/react-native-webview/react-native-webview/blob/master/android/build.gradle and they also apply outside the if conditional but define inside the conditional

It appears to be a standard construction ?

**Comment by birdofpreyru** [comment]
Well, **rn-webview** also has `kotlin-gradle-plugin` declaration in the `else` block: https://github.com/react-native-webview/react-native-webview/blob/a2a2d0af92aec989a58b57a191c7c738b38517b9/android/build.gradle#L25 ;)

**Comment by birdofpreyru** [comment]
And the example also has that `classpath` declared explictly: https://github.com/invertase/react-native-google-mobile-ads/blob/abd8db61ab32cef3a6d5ded0c21248ff220606f0/RNGoogleMobileAdsExample/android/build.gradle#L30

**Comment by mikehardy** [comment]
Oh - I did not look closely enough at the react-native-webview conditional construction - I think you nailed it with

> or the classpath for the plugin should be moved out of thatif` block

Thanks for pointing this out since the example has it explicitly declared that's why it did not show up there

**Comment by mikehardy** [comment]
If you have a moment @birdofpreyru could you either try the patch-package set here https://github.com/invertase/react-native-google-mobile-ads/actions/runs/2565287171 or you could also just manually apply the new else block in the build.gradle to make sure it works for you? I can merge + release it basically immediately but I want to make sure it works for you since you're obviously reproducing it

**Comment by mikehardy** [comment]
I had a silly groovy error in my first attempt, just repushed after checking it locally, I updated the URL in comment above to patch-package set :point_up:

**Comment by birdofpreyru** [comment]
@mikehardy tested, it works! :)

**Comment by birdofpreyru** [comment]
@mikehardy On a separate thing, it seems to me that after updating to **v7.0.0** I started having problems with loading interstitial ads on Android. A bit weird, though. I have it configured to always show test ads on my test device. When I build the code in development variant, it seems to work just fine. When I build the code in release variant interstial ads just never load (I check it by testing `.loaded` field on the intestitial ad object). At the same time, the banner ads I also use work fine in both cases, showing test ads. I am still not sure what is going on, maybe I am missing something on my side.

Any chance it reminds you any changes in **v7.0.0** that may affect how interstitial ads are loaded (or how test device config is applied to them)?

**Comment by mikehardy** [comment]
That doesn't remind me of anything 🤔
Can you try the example app in release mode to see if it suffers same problem?
