### ISSUE TITLE
compileSdkVersion is not specified

### ISSUE THREAD

**Issue by neon010** [invertase/react-native-google-mobile-ads#184]
2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':react-native-google-mobile-ads'.
> com.android.builder.errors.EvalIssueException: compileSdkVersion is not specified. Please add it to build.gradle

I am getting this error while adding this to my projects

---

- 👉 Check out [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
No reproduction, sorry https://stackoverflow.com/help/how-to-ask / https://stackoverflow.com/help/mcve

Try the example, should work? Note the example is built dynamically so you can follow how to integrate things: https://github.com/invertase/react-native-google-mobile-ads/blob/main/refresh-example.sh

Given we have an automated demonstration of integration and there is no information here to reproduce, it's not actionable / won't result in a change --> closing

**Comment by neon010** [comment]
Thanks for helping me out. I was actually missing app-add id in app.json file.

**Comment by mikehardy** [comment]
Ah! That one is hopefully less subtle than it used to be, I just integrated a change that hopefully makes it a build warning #177 - did that not trigger a build failure with a good message? It really should have but the change was recent, perhaps it needs tuning
