### ISSUE TITLE
How to differentiate between IDFA and GDPR messages  

### ISSUE THREAD

**Issue by venurasasankaabeysinghe** [invertase/react-native-google-mobile-ads#185]
I need help with 2 issues
I have set up IDFA and GDPR messages in the Admob web portal. When I run the app on ios I get these values for 
const consentInfo = await AdsConsent.requestInfoUpdate()
{"isConsentFormAvailable": 1, "status": "REQUIRED"}

According to documentation above values means I have to display the consent form so I display it as below;

if (consentInfo.isConsentFormAvailable && consentInfo.status ===AdsConsentStatus.REQUIRED) {
const { status } = await AdsConsent.showForm();
}

On the ios on a non EEA region this shows the ATT message. The problem occurs after this. Then I check the choice values to display personalised ads, non personalised ads or ask users to purchase a subscription as below;

  const {
            activelyScanDeviceCharacteristicsForIdentification,
            applyMarketResearchToGenerateAudienceInsights,
            createAPersonalisedAdsProfile,
            createAPersonalisedContentProfile,
            developAndImproveProducts,
            measureAdPerformance,
            measureContentPerformance,
            selectBasicAds,
            selectPersonalisedAds,
            selectPersonalisedContent,
            storeAndAccessInformationOnDevice,
            usePreciseGeolocationData,
          } = await AdsConsent.getUserChoices();

First issue is when I call the above I always get “Failed to decode tcString undefined: [TypeError: undefined is not an object (evaluating 'e.split')]” warning.

How to get rid of this warning?

if (
storeAndAccessInformationOnDevice === true &&
createAPersonalisedAdsProfile === true &&
selectPersonalisedAds === true &&
selectBasicAds === true &&
measureAdPerformance === true &&
applyMarketResearchToGenerateAudienceInsights === true &&
developAndImproveProducts === true
          ) {
Display personalised ads
          } else if (
storeAndAccessInformationOnDevice === true &&
createAPersonalisedAdsProfile === false &&
selectPersonalisedAds === false &&
selectBasicAds === true &&
measureAdPerformance === true &&
applyMarketResearchToGenerateAudienceInsights === true &&
developAndImproveProducts === true
          ) {
Display non personalised ads
          } else {
Ask users to buy a subscription to disable ads
          }

Second issue

As mentioned before when ios displays ATT message all of those values comes as false which I think is correct because those values are for GDPR message not for ATT message. Now what happens is users are presented with in-app purchase screen to buy subscriptions which is wrong. Instead, I think users should have access to app and we can display non-personalised Ads. Correct me if I am wrong here.

Is my flow of asking for consent correct?
How do I find out which form is displayed whether it is IDFA/ATT message or GDPR?

**Comment by DoctorJohn** [comment]
I'm pretty sure the tcString is only set when GDPR consent is given (since the TCString is something specified by IAB and IAB is a GDPR consent framework spec). That also explains why your values are always false, they are also based on the TCString.

If you format your code correctly I might take a look to see whether your consent flow is correct, the current formatting makes my eyes hurt too much

**Comment by VictorioMolina** [comment]
@venurasasankaabeysinghe Same here. On iOS, I do not get the GDPR message displayed, only ATT.

Also, after granting the consent, all user GDPR choices are `false` (including `storeAndAccessInformationOnDevice`, from your conditional) so, your else-if statement will not be executed on iOS.

Did you find any workaround?

**Comment by StCyr** [comment]
> @venurasasankaabeysinghe Same here, also getting that warning. On iOS, I do not get the GDPR message displayed, only ATT.
> 
> Also, after granting the consent, all user GDPR choices are `false` (including `storeAndAccessInformationOnDevice`, from your conditional) so, your else-if block will not be executed on iOS.
> 
> Did you find any workaround?

Hello! did you?
