### ISSUE TITLE
[🐛] Error while updating property 'sizes' of a view managed by:RNGoogleMobileAdsBannerView

### ISSUE THREAD

**Issue by shadow-boy** [invertase/react-native-google-mobile-ads#187]
![Screenshot_1657071012](https://user-images.githubusercontent.com/15226194/177448021-898d64c5-85ac-41e8-a434-48ed026b56f7.png)
what's happening on android?the error was been throwed

**Comment by MarouaniALA** [comment]
any help here please

**Comment by tharakanwn2014** [comment]
@shadow-boy were you able to resolve this issue?

**Comment by dev-frid** [comment]
Has anyone fixed this? Hello??

**Comment by BhavsarKrutarth** [comment]
Please Use expo start --dev-client 
any query contact me this email Address : BhavsarKrutarth88@gmail.com
ping me and i will share sources code

**Comment by focux** [comment]
I'm experiencing this same problem, any idea about how to fix it?

**Comment by shadow-boy** [comment]
just use a real device can fix this bug，admob for android can not run with emulators

**Comment by focux** [comment]
Looks like you didn't read my answer, I fixed it by rounding the dimensions and not by using a real-device.

**Comment by jaure96** [comment]
Thx @focux, your solution works perfectly!

```
const windowWidth = Math.round(Dimensions.get('screen').width)
...
...
<BannerAd size={`${windowWidth}x50`} unitId="___" />
```

**Comment by PiotrSzlagura** [comment]
@focux I've encountered this issue as well, and rounding the width fixed it for me, thank you!
