### ISSUE TITLE
[🐛] [Android] Can not create dialog without Activity Context

### ISSUE THREAD

**Issue by wonderlul** [invertase/react-native-google-mobile-ads#188]
## Issue

Hello Everyone,

I'm experiencing an issue when I'm trying to open Creative Preview & Delivery Inspector using react-native-google-mobile-ads. It's being said here (https://support.google.com/admanager/answer/7180401) that using a gesture (touch and hold the ad with two fingers) I'll be able to open debug mode. Instead, nothing happens. I was able to read this message from Logcat:

`I/Ads: Can not create dialog without Activity Context`

Does someone know why is this happening? Is this even related to library itself? I'm using latest version.

I would be grateful for your help. If any additional informations are needed, please inform.

React Native 0.65.1
react-native-google-mobile-ads: 7.0.1 (but I also checked od ^6 and ^5)
targetSDK: 30
Component: GAMBannerAd (but same behavior with BannerAd)

Best regards.

**EDIT**
I tried `react-native-ad-manager` and same ads respond to this touch so I'm pretty sure it's related to the library now.

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both

</p>
</details>

---

- 👉 Check out [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
May be that the Context used is an ApplicationContext not an ActivityContext. Open to PRs that attempt to resolve this

**Comment by aidan-24com** [comment]
apologies for the back and forth with this, but I believe the new PR is a cleaner approach and also only handful of lines
