### ISSUE TITLE
[🐛] Build crash due to iOS app id missing (but it shouldn't) [solution - carefully carefully check Info.plist, put app id in app.json not app.config.js]

### ISSUE THREAD

**Issue by andreality92** [invertase/react-native-google-mobile-ads#189]
## Issue
Hello, I'm working on a bare React Native app after ejecting from Expo.
During the build I get this error:
_error: ios_appd_id key not found in react-native-google-mobile-ads key in app.json. App will crash without it._

I already injected the Google Admob application ids in the app.json as follow:
```
{
  "expo": {
    .... expo app.json stuff ....
  },
  "react-native-google-mobile-ads": {
    "ios_app_id": "ca-app-pub-....",
    "android_app_id": "ca-app-pub-...."
  }
}
```
I tried deleting node modules, Pods, Podfile.lock, build folder and reinstall everything, clean build with XCode too, but it didn't work.
I'm using version 7.0.0 but I also tried with 7.0.1, no luck:
```
"react-native": "0.68.2",
"react-native-google-mobile-ads": "^7.0.0",
```

I really can't understand what's going on here and your help would be appreciated.
Thank you so much

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "name": "myapp",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-community/netinfo": "8.2.0",
    "@react-native-google-signin/google-signin": "^8.0.0",
    "@react-native-voice/voice": "^3.2.3",
    "@react-navigation/bottom-tabs": "^6.0.9",
    "@react-navigation/drawer": "^6.3.1",
    "@react-navigation/elements": "^1.3.1",
    "@react-navigation/material-top-tabs": "^6.0.6",
    "@react-navigation/native": "^6.0.6",
    "@react-navigation/native-stack": "^6.2.5",
    "@reduxjs/toolkit": "^1.7.1",
    "core-js": "^3.21.0",
    "emoji-mart-native": "^0.6.4-beta",
    "expo": "^45.0.0",
    "expo-apple-authentication": "~4.2.1",
    "expo-asset": "~8.5.0",
    "expo-auth-session": "~3.6.1",
    "expo-av": "~11.2.3",
    "expo-crypto": "~10.2.0",
    "expo-device": "~4.2.0",
    "expo-image-picker": "~13.1.1",
    "expo-localization": "~13.0.0",
    "expo-location": "~14.2.2",
    "expo-notifications": "~0.15.4",
    "expo-random": "~12.2.0",
    "expo-splash-screen": "~0.15.1",
    "expo-status-bar": "~1.3.0",
    "expo-updates": "~0.13.2",
    "firebase": "^9.8.4",
    "i18n-js": "^3.8.0",
    "lottie-react-native": "5.0.1",
    "react": "17.0.2",
    "react-devtools": "^4.23.0",
    "react-dom": "17.0.2",
    "react-native": "0.68.2",
    "react-native-chart-kit": "^6.11.0",
    "react-native-circular-chart": "^1.0.8",
    "react-native-collapsible": "^1.6.0",
    "react-native-dotenv": "^3.3.1",
    "react-native-draggable-flatlist": "^3.0.5",
    "react-native-emoji-selector": "^0.2.0",
    "react-native-fbsdk-next": "^10.0.0",
    "react-native-gesture-handler": "~2.2.1",
    "react-native-google-mobile-ads": "^7.0.0",
    "react-native-modal": "^13.0.0",
    "react-native-pager-view": "5.4.15",
    "react-native-progress-circle-rtl": "^2.1.0",
    "react-native-reanimated": "~2.8.0",
    "react-native-safe-area-context": "4.2.4",
    "react-native-screens": "~3.11.1",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-sortable-list": "0.0.24",
    "react-native-svg": "12.3.0",
    "react-native-swipe-gestures": "^1.0.5",
    "react-native-swipe-list-view": "^3.2.9",
    "react-native-swiper": "^1.6.0-rc.3",
    "react-native-tab-view": "^3.1.1",
    "react-native-web": "0.17.7",
    "react-redux": "^7.2.6",
    "react-style-proptype": "^3.2.2",
    "request": "^2.79.0",
    "rn-emoji-keyboard": "^0.7.0",
    "use-count-up": "^3.0.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "babel-plugin-macros": "^3.1.0",
    "eslint-plugin-react-hooks": "^4.5.0"
  },
  "private": true
}

```

#### `admob.json`:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

```ruby
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
require File.join(File.dirname(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

platform :ios, podfile_properties['ios.deploymentTarget'] || '12.0'
install! 'cocoapods',
  :deterministic_uuids => false

target 'myapp' do
  use_expo_modules!
  config = use_native_modules!
  pod 'GoogleSignIn', '~> 6.2.2'
  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => flags[:hermes_enabled] || podfile_properties['expo.jsEngine'] == 'hermes',
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Dir.pwd}/.."
  )

  # Uncomment to opt-in to using Flipper
  # Note that if you have use_frameworks! enabled, Flipper will not work
  #
  # if !ENV['CI']
  #   use_flipper!()
  # end

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end

  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end

end

```

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 12.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 9.31 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.17.5 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.14 - /usr/local/bin/npm
    Watchman: 2022.07.04.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 16.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **Are you using `TypeScript`?**
  - NO

</p>
</details>

**Comment by DoctorJohn** [comment]
Just a guess, but maybe you have to run the `expo prebuild` command. The [expo documentation states](https://docs.expo.dev/workflow/customizing/):

> If you install a package with a Expo [config plugin](https://docs.expo.dev/guides/config-plugins/), you'll need to add the plugin to your app.jsons [plugins](https://docs.expo.dev/versions/latest/config/app/#plugins) array, then re-run expo prebuild to sync the changes before rebuilding the native app. Often this does things like adding required permissions to the Info.plist or AndroidManifest.xml. You may need to run expo prebuild --clean depending on how complex the plugin is; this will delete and re-generate the native project files from scratch.

**Comment by Seb285** [comment]
> ## Issue
> Hello, I'm working on a bare React Native app after ejecting from Expo. During the build I get this error: _error: ios_appd_id key not found in react-native-google-mobile-ads key in app.json. App will crash without it._
> 
> I already injected the Google Admob application ids in the app.json as follow:
> 
> ```
> {
>   "expo": {
>     .... expo app.json stuff ....
>   },
>   "react-native-google-mobile-ads": {
>     "ios_app_id": "ca-app-pub-....",
>     "android_app_id": "ca-app-pub-...."
>   }
> }
> ```
> 
> I tried deleting node modules, Pods, Podfile.lock, build folder and reinstall everything, clean build with XCode too, but it didn't work. I'm using version 7.0.0 but I also tried with 7.0.1, no luck:
> 
> ```
> "react-native": "0.68.2",
> "react-native-google-mobile-ads": "^7.0.0",
> ```
> 
> I really can't understand what's going on here and your help would be appreciated. Thank you so much
> 
> ## Project Files
> ### Javascript
> Click To Expand
> ### iOS
> Click To Expand

same here

**Comment by Seb285** [comment]
@andreality92 did you get it to work?

**Comment by monti-python** [comment]
Hi @Seb285,

Have a look at https://github.com/invertase/react-native-google-mobile-ads/issues/179, it can be fixed by converting your `app.config.js` into `app.json`. It seems `app.config.js` ignores config outside the `expo` block

**Comment by mikehardy** [comment]
@Draktors please do not post "same heres" or other sorts of "me too" comments. A reaction is sufficient - https://hackernoon.com/i-thought-i-understood-open-source-i-was-wrong-cf54999c097b - also please don't take offense at this comment, it is meant to be friendly and educational, and just help you interact with this repo and all open source repos

If you've got anything to add that moves this forward though, that would be awesome

**Comment by andreality92** [comment]
I could make it work few days later but don't remember exactly what I did, looking  at the version control I made sure that:
- Development team is selected under "Signing and Capabilities"
- <key>GADApplicationIdentifier</key> is removed from info.plist file (in case you added it)
- Old Expo Admob package is removed from your project

**Comment by Draktors** [comment]
@mikehardy Thanks for this advice ! 

@andreality92 I removed GADApplicationIdentifie from info.plist file and it works !

**Comment by mikehardy** [comment]
Great news! Thanks for reporting back
It doesn't seem like there is anything actionable here so I'm going to close this. If it seems like something that fits in our docs somewhere there is an edit button on the top right of every page I think, and docs PRs are pretty easy on the github web UI
Cheers
