### ISSUE TITLE
 compileSdkVersion is not specified. Please add it to build.gradle

### ISSUE THREAD

**Issue by EmreGurbuzz** [invertase/react-native-google-mobile-ads#190]
## Problem

When I include "react-native-google-mobile-ads", I can't start the project with react-native run-android. I tried it in my own project, I couldn't open it, I have the same problem when I open an empty project from scratch and add this package. How can I get around this?

### Error log
BUİLD FAILED in 20s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/Users/emregurbuz/Desktop/Projeler/parizon/node_modules/react-native-google-mobile-ads/android/build.gradle' line: 59

* What went wrong:
A problem occurred evaluating project ':react-native-google-mobile-ads'.
> Cannot get property 'googleMobileAdsJson' on extra properties extension as it does not exist

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':react-native-google-mobile-ads'.
> com.android.builder.errors.EvalIssueException: compileSdkVersion is not specified. Please add it to build.gradle

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

## react-native info
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 105.78 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.0 => 0.68.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by mikehardy** [comment]
Hi there!

> Cannot get property 'googleMobileAdsJson' on extra properties extension as it does not exist

So it's not integrated correctly. Your app.json should look something like the example app's app.json which you may see in this repository

Your app's build.gradle files should looks something like the build.gradle files that you see in our example app which may see in this repository. In particular you may need to include the kotlin gradle plugin at a new enough version 1.6.20 or I think 1.7.x is current now

Either way, this is a project integration issue so is not actionable here - we provide an example app that definitely builds and run, and we provide that for the purpose of serving as a comparison so you can see how things are supposed to work and compare it with a non-working project

In addition the example app is actually built from a script so you may consult the script to see exactly what integration steps are required https://github.com/invertase/react-native-google-mobile-ads/blob/main/refresh-example.sh

Between the script and the example itself, the answer should hopefully be visible

**Comment by ahtisham09** [comment]
Hi @mikehardy i having same issue and any solution how i can fix this issue Thanks
