### ISSUE TITLE
[📚] Reference Links Broken

### ISSUE THREAD

**Issue by pschorey** [invertase/react-native-google-mobile-ads#192]
The instructions have many links to reference documentation, but all the internal links seem to be broken.  Below are three links from the directions that I was trying to read about but can't open.

https://docs.page/invertase/react-native-google-mobile-ads/reference/admob/requestconfiguration
https://docs.page/invertase/react-native-google-mobile-ads/reference/admob/banneradsize
https://docs.page/invertase/react-native-google-mobile-ads/reference/admob/requestoptions

Is there another way I can read the above documentation?

Thanks for the great plugin!

**Comment by mikehardy** [comment]
I think we have an issue for this already? I'm mobile so I can't search easily at the moment but the issue is with docs.page not supporting the typedoc generation yet + links into it?

**Comment by pschorey** [comment]
Thanks Mike,
Sorry I missed that.  Looks like the issue is found in https://github.com/invertase/react-native-google-mobile-ads/issues/83
Appreciate it!

**Comment by code-by** [comment]
the link
https://docs.page/invertase/react-native-google-mobile-ads/reference/admob/requestconfiguration
still broken
