### ISSUE TITLE
What to Do for Google Family Policy?

### ISSUE THREAD

**Issue by bloggerklik** [invertase/react-native-google-mobile-ads#193]
It is said that for the Google Family Policy it must be specified in the code. 

- maxAdContentRating
- tagForChildDirectedTreatment

Can you show a simple example of how I should add it?

**Comment by bloggerklik** [comment]
@mikehardy  Thank you so much. Really, this job confused me a lot and I couldn't notice it because of my distraction. I have a mobile application that does not require age restrictions. That's why I chose all age groups as the target audience. However, the ads are expected to be suitable for children. I'm not sure if these should be added to the code. If added to the code, will the ad content only show ads for kids? My target audience is not just children, but all age groups. What do you think I should do?

**Comment by mikehardy** [comment]
This should be in the Google admob docs or available on stackoverflow, it's not a use case of mine so I am not authoritative but I think the thing is, if kids can use the app, ada need to be okay for kids.
