### ISSUE TITLE
[🐛] IOS Interestial and rewarded ad not show after modal appers on screen

### ISSUE THREAD

**Issue by waaplog** [invertase/react-native-google-mobile-ads#196]
## Issue
A problem occurs when displaying rewarded and interstitial ads after a modal display on iOS devices. 
interstitial ad comes and closes immediately, while the video is not played in rewarded ads.
As a solution, when we call the ad 1 second after a modal, it works.
Version used: "react-native-google-mobile-ads": "^7.0.1",
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `admob.json`:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

```ruby
# N/A
```

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by TaylorDale** [comment]
relevant #47

**Comment by waaplog** [comment]
> 

Thank you Taylor, I am a bit new and the solution that I mentioned in the issue helped me a lot so added her to help other people in this situation.
Best regards.

**Comment by waaplog** [comment]
Hello,
In the last two days, our system suffered a minor glitch due to the WhatsApp update and some numbers were automatically deleted. 
We apologize for this situation.
Now our servers are active and working. 
You can add a number and start tracking.
Kind regards.
