### ISSUE TITLE
[🐛] Admob - rewardedAd.load() not working the second time

### ISSUE THREAD

**Issue by codingdais** [invertase/react-native-google-mobile-ads#197]
Admob - rewardedAd.load() not working the second time........

**Comment by mikehardy** [comment]
Hi there! This doesn't have enough information to help us help you (https://stackoverflow.com/help/how-to-ask) so I'm going to close this - please feel free to file a new one if you can show a reproduction (https://stackoverflow.com/help/minimal-reproducible-example) along with helpful info

I will say that our included example app here lets you reload ads. I reload them. It seems to work?

**Comment by Robiullah2244** [comment]
Facing the same issue. Any solution?
