### ISSUE TITLE
[📚] Hide ads in Google play or firebase tests

### ISSUE THREAD

**Issue by raajnadar** [invertase/react-native-google-mobile-ads#202]
## Documentation Feedback

I didn't find any example or function to hide the ads on google play or firebase tests, The bot clicks on the ads and reports 2-3 crashes every time. Is there any way to hide them in the test mode?

This seems like a solution for native apps

https://stackoverflow.com/a/70415575/5519872

Official docs - https://firebase.google.com/docs/test-lab/android/android-studio#java

I am using the packing in Expo SDK 46

**Comment by DoctorJohn** [comment]
One could probably use the [`isRunningInTestLab` util from the react-native-firebase package](https://rnfirebase.io/app/utils#test-lab) (at least for firebase tests).

**Comment by raajnadar** [comment]
Can this function be added to this package?

**Comment by mikehardy** [comment]
A PR to add this as a utility function would be fine by me, I'd merge it if it seemed like it was in a sensible location.

**Comment by mikehardy** [comment]
This still needs an interested party to add it, if desired. I use firebase personally so have no interest in duplicating the code here but I will merge a PR if it shows up.
Until then, you might like https://github.com/ratson/react-native-firebase-test-lab/blob/master/android/src/main/java/name/ratson/RNFirebaseTestLabModule.java

I'm going to close this as stale though for lack of action
