### ISSUE TITLE
[📚] Diffirence between : "Banner Ads (component) "and "Google Ad Manager Banner"

### ISSUE THREAD

**Issue by chungtvdev** [invertase/react-native-google-mobile-ads#207]
## Documentation Feedback

Hi, could you give me more docs or example about : "Banner Ads (component) "and "Google Ad Manager Banner". Thank you so much

**Comment by mikehardy** [comment]
Hi there! Google Ad Manager (GAM) is a separate type of advertising / ad account with google. You can search these:

https://admanager.google.com/home/
https://admob.google.com/home/

We support both

**Comment by ds8k** [comment]
@mikehardy if I'm only using GAM ads do I still need to configure AdMob? We're currently using a pretty outdated package for ads and and would like to switch, but it doesn't require setting up an account

**Comment by mikehardy** [comment]
@ds8k interesting, so I am not *that* familiar with GAM, I only infer from what you right that if you are using GAM you do not have an admob id for either platform? That is, you expect to be able to just call the APIs but you do not have anything like these to add to the config?

https://github.com/invertase/react-native-google-mobile-ads/blob/365f1a4b733a3efa7a81fd174fcc2839cbbfd23e/RNGoogleMobileAdsExample/app.json#L5-L6

If so, I learned something today, and I'm also not sure how to handle that, as we have a strong expectation that those config items exist, to the point where we fail as fast as possible (via a build error) if they are not there :thinking:
