### ISSUE TITLE
[📚] How to display Adaptive Banner Ads (not traditional Banner ads)?

### ISSUE THREAD

**Issue by chungtvdev** [invertase/react-native-google-mobile-ads#208]
## Documentation Feedback

Hi Sir.
Coiuld you give me the docs to instruct: how to display Adaptive Banner Ad (not traditional Banner ads)

Link: https://www.youtube.com/watch?v=KfKMN9uJZDk

---

- 👉 Check out [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
@chungtvdev I'm sorry, if the docs we have are not sufficient, then we just don't have them. I am not using them personally so I can't instruct anyone on them. This may be an area where you personally have to play with them (consulting the upstream docs in the google admob documentation) until you feel they are correct, then propose a pull request for any missing documentation you feel would help future developers.

**Comment by dylancom** [comment]
Just specify the banner size you need.
```
<BannerAd
  unitId={adUnitId}
  size={BannerAdSize.ANCHORED_ADAPTIVE_BANNER}
/>
```
