### ISSUE TITLE
Rewarded ads returning : null is not an object (evaulating 'RNAppModule.eventsNotifyReady')

### ISSUE THREAD

**Issue by EMKA-ctrl** [invertase/react-native-google-mobile-ads#209]
I am trying to show **rewarded Ads on an Android project managed by expo**, and i've tried both typescript and javascript templates.

I have the last release of this package --> (7.0.1)

The code below is the function returning the ad, and no matter what i do or change, it always throws me the same error:
Does anyone know what i am doing wrong??

 ### >>  ERROR  TypeError: null is not an object (evaluating 'RNAppModule.eventsNotifyReady')

**Code:**

`import React,{useEffect,useState} from 'react';`
`import {Text, View,Button} from 'react-native';`
`import { RewardedAd,RewardedAdEventType,TestIds } from 'react-native-google-mobile-ads';`

`const bonificatsID = "ca-app-pub-REDACTED"`

`const adUnitId = __ DEV__ ? TestIds.REWARDED : bonificatsID;`

`const rewarded = RewardedAd.createForAdRequest(adUnitId, {
    requestNonPersonalizedAdsOnly: true,
    keywords: ['fashion', 'clothing'],
});`
  
`export default function App() {`
      `const [loaded, setLoaded] = useState(false);`
  
    useEffect(() => {
      const unsubscribeLoaded = rewarded.addAdEventListener(RewardedAdEventType.LOADED, () => {
        setLoaded(true);
      });
      const unsubscribeEarned = rewarded.addAdEventListener(
        RewardedAdEventType.EARNED_REWARD,
        reward => {
          console.log('User earned reward of ', reward);
        },
      );
  
      // Start loading the rewarded ad straight away
      rewarded.load();
  
      // Unsubscribe from events on unmount
      return () => {
        unsubscribeLoaded();
        unsubscribeEarned();
      };
    }, []);
  
    // No advert ready to show yet
    if (!loaded) {
      return (
        <View>
            <Text>Ad not loaded...</Text>
        </View>
      );
    }
  
    return (
      <Button
        title="Show Rewarded Ad"
        onPress={() => {
          rewarded.show();
        }}
      />
    );
  `}`

Thank you in advance

**Comment by DoctorJohn** [comment]
Are you using the dev client or expo go?

**Comment by mikehardy** [comment]
Hi there!

I have redacted your ads id from your post, and removed that version from history. You don't want that ID to be public generally. Just use a test id

Your code is not very readable - when you use markdown you want to use triple-backticks for code, ideally with a language specifier, like:

```javascript
  // this is some code
  if (hasBackticksAndLanguage) {
    readEasily();
  }
```

When you get an error like:

> >> ERROR TypeError: null is not an object (evaluating 'RNAppModule.eventsNotifyReady')

"null is not an object" on something that seems like it is the name of the native module, the first guess is that the native module is not built correctly and included in the build. 

At that point I think @DoctorJohn's question (I see it updated in the UI just above me just now!) is important. Perhaps you are not using the Expo style that allows you to build native modules

**Comment by EMKA-ctrl** [comment]
First of all, thank you for responding so fast.

@DoctorJohn I am using **expo go**, the latest version on the play store.
@mikehardy I checked and updated every package, updated to last expo SDK and all is up to date now. However these error seems to keep appearing.
I also tried to create a project using a javascript template, as I was using typescript.
I don't want to be too bold, but this error could be from the package "react-native-google-mobile-ads" itself and some incompatibility? Last time I showed an Ad successfully was with "expo-ads-mob", but now seems to be depracated.

If it is not too much to ask, how are you doing it or how would you do it?

Thanks and regards,

**Comment by mikehardy** [comment]
Expo Go is not going to work I don't think. I do not think that they have decided to include the native module for this repo in their app. I believe you have to use EAS ?

**Comment by DoctorJohn** [comment]
Mike is correct. Expo Go won't work since the react-native-mobile-ads native code is not part of it. EAS works though.
