### ISSUE TITLE
Android 13 (API 33) declaration

### ISSUE THREAD

**Issue by sametcl2** [invertase/react-native-google-mobile-ads#210]
Hi,

I've been using this library for a while and I'm pretty pleased. 

In Google Play Console,  I received a message, so I don't know if this library auto-handle this situation or where can I get **AD_ID** for adding to manifest file like this  **com.google.android.gms.permission.AD_ID** 

Thanks.

<img width="716" alt="Screen Shot 2022-08-25 at 13 34 21" src="https://user-images.githubusercontent.com/34509901/186642840-d3156d6d-081a-4902-ba02-ad433522ebe4.png">

**Comment by sametcl2** [comment]
Thank you mike

**Comment by william-keller** [comment]
Thank you guys...  I got stuck in the same doubt
