### ISSUE TITLE
Having trouble walking through documentation (AdapterStatuses errors)

### ISSUE THREAD

**Issue by StevenHarlow** [invertase/react-native-google-mobile-ads#211]
I've been reading the documentation, but it looks like there are a [bunch](https://docs.page/invertase/react-native-google-mobile-ads/reference/admob/requestoptions) [of](https://docs.page/invertase/react-native-google-mobile-ads/reference/admob/rewardedadeventtype) [broken](https://docs.page/invertase/react-native-google-mobile-ads/reference/admob/rewardedinterstitialad) [links](https://docs.page/invertase/react-native-google-mobile-ads/reference/admob/interstitialad) and I'm not sure if I'm doing something wrong. I've also noticed that the library that this module migrated from has more documentation steps (setting up firebase-core) that I'm not sure if I'm supposed to do, and the video in the "What it does" section of the installation page doesn't have much context, so I'm not sure if I'm supposed to follow any of those steps.

Currently I'm having problems initializing `mobileAds()`. On android the return `adapterStatuses` I get are:

```json
[{"description": "", "name": "com.google.android.gms.ads.MobileAds", "state": 1}, 
{"description": "Failed to create Adapter.", "name": "com.google.ads.mediation.vungle.VungleMediationAdapter", "state": 0}, 
{"description": "Failed to create Adapter.", "name": "com.google.ads.mediation.applovin.AppLovinMediationAdapter", "state": 0}, 
{"description": "Failed to create Adapter.", "name": "com.google.ads.mediation.adcolony.AdColonyMediationAdapter", "state": 0}, 
{"description": "Failed to create Adapter.", "name": "com.google.ads.mediation.tapjoy.TapjoyMediationAdapter", "state": 0}]
```

and on iOs I get:
`[{"description": "<GADAdapterStatus: 0x6000008e9500; state = Not Ready;Could not retrieve application configuration data.>", "name": "GADMobileAds", "state": 0}]`

**Comment by mikehardy** [comment]
The reference links are not that useful right now because of #83 

The documents from the `@react-native-firebase/admob` era are no longer of any value with regard to this module, so I would ignore those, it will just be confusing

Have you tried just making a throwaway test app to play with it? We create the example app here with a script, which also serves as an MCVE (https://stackoverflow.com/help/mcve) of how to build an app with this module: https://github.com/invertase/react-native-google-mobile-ads/blob/main/refresh-example.sh

Following along with that might help

**Comment by 92sajid110** [comment]
i only getting this adapter status
{"description": "", "name": "com.google.android.gms.ads.MobileAds", "state": 1}
any help

**Comment by mikehardy** [comment]
@92sajid110 - this is threadjacking, please don't do that as it splinters discussion and is not fair to the original poster. Also, if it were its own issue, it would be unanswerable (https://stackoverflow.com/help/how-to-ask / https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by anwersolangi** [comment]
I checked logcat, and got the following errors:
 'status -> '
```
[ { description: '', state: 1, name: 'com.google.android.gms.ads.MobileAds' },
  { description: 'Failed to create Adapter.', state: 0, name: 'com.google.ads.mediation.vungle.VungleMediationAdapter' },
  { description: 'Failed to create Adapter.', state: 0, name: 'com.google.ads.mediation.applovin.AppLovinMediationAdapter' },
  { description: 'Failed to create Adapter.', state: 0, name: 'com.google.ads.mediation.adcolony.AdColonyMediationAdapter' },
  { description: 'Failed to create Adapter.', state: 0, name: 'com.google.ads.mediation.tapjoy.TapjoyMediationAdapter' } ]
```

I searched around the internet for somehelp, and found [this](https://stackoverflow.com/questions/61762993/mobileads-initializecontext-string-is-deprecated) similar to this issue, however the stackoverflow answers suggested that to add APP_ID in the manifest file, I also checked the lib code, but can't find anything wrong there. Anyone found a solution?

**Comment by mikehardy** [comment]
Yeah, we already add app_id to manifest (via placeholder substitution, processing app.json keys and injecting them into gradle) otherwise nothing would work, right? So that is likely working.
Why would adapters not be working, unknown.

**Comment by fmApss** [comment]
on emulator i am getting same error (array if faild status)
but on physical phone it works (actuly i get timeout instead of faild. thats because of gov's cencorship)
