### ISSUE TITLE
[🐛] Fluid size not correctly

### ISSUE THREAD

**Issue by ricardodolnl** [invertase/react-native-google-mobile-ads#213]
The banner size 'FLUID' does not work correctly. It does not take the parent width, it takes the full device/screen with.
I have a container around the ad with padding left and right. But the banner does not fit inside this container. Instead it goes outside the right side of the container.

```javascript
<View style={styles.container}>
      <GAMBannerAd
        unitId={__DEV__ ? TestIds.GAM_NATIVE : adUnitId}
        sizes={[BannerAdSize.FLUID]}
        requestOptions={{
          requestNonPersonalizedAdsOnly: !allowTracking,
        }}
      />
</View>
```

**Comment by mikehardy** [comment]
Hi there! Can you include the information we would need to reproduce this? That is, versions of things in dependencies, build toolchain, and test execution environment?

**Comment by sedatb** [comment]
@mikehardy, I am trying to show fluid ads. I give width and height but Ads is extended to screen width. BannerAd is not using container's width, height. I. tried to give style={{width: 100, height:100}} to <BannerAd but id didn't work.
Can you help me about this problem.
Thanks

`return (
    <View style={{ flex: 1, flexDirection: 'row', marginBottom: 300 }}>
      <View style={{ width: 100, height:100, backgroundColor:'red' }}>
        <BannerAd
          unitId={myUnitId}
          size={BannerAdSize.FLUID}
          requestOptions={{
            requestNonPersonalizedAdsOnly: true,
          }}
        />
      </View>
    </View>
  );`

**Comment by DoctorJohn** [comment]
There is a TODO in the code suggesting the fluid size probably never worked:

https://github.com/invertase/react-native-google-mobile-ads/blob/e7ec4ed669ee05a0db2ae9c81ee23b5e01f8f901/android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsBannerAdViewManager.java#L173

You can make your own fluid banner though. This can be done by requesting an that has the size you need. Would look roughtly like this:

```jsx
// Get these values dynamically:
const parentWidth = 320;
const parentHeight = 60;

<BannerAd uniId="" size={`${parentWidth}x${parentHeight}`} />
```

You can use react state and the `onLayout` event handler to get the parent containers size.

**Comment by Gregoirevda** [comment]
Currently passing width through `RCT_EXPORT_VIEW_PROPERTY`

**Comment by Gregoirevda** [comment]
@RicardoDolNL can you validate if my PR solves your problem?

**Comment by ricardodolnl** [comment]
> @ricardodolnl can you validate if my PR solves your problem?

Sorry haven't had time to work on the project that I use this on recently. I hope to try it out soon, but looking at the changed files of the PR it looks good.

**Comment by MicahDavid** [comment]
It looks like this issue still exists. Has anyone been able to solve the fluid ads fitting the container width?

**Comment by BrodaNoel** [comment]
Agree. This seems to be happening again

**Comment by shukerullah** [comment]
I am still seeing the width issue on iOS. Even with a parent View set to `width: '50%'`, the Fluid ad stretches to 100% screen width:


```javascript
<View style={{ width: '50%', backgroundColor: 'red' }}>
 <GoogleMobileAds unitId={TestIds.GAM_BANNER} sizes={[GAMBannerAdSize.FLUID]} />
</View>
```

![Image](https://github.com/user-attachments/assets/70309e6e-97b5-4142-a070-da75e37bef40)

**Comment by Gregoirevda** [comment]
@shukerullah does adding `minHeight: 200` works?

**Comment by shukerullah** [comment]
> [@shukerullah](https://github.com/shukerullah) does adding `minHeight: 200` works?

No `minHeight: 200` doesn't help. The issue is specifically with width - the banner takes full device width instead of parent width on iOS.
