### ISSUE TITLE
[📚] How to detect if user has allowed tracking (App Tracking Transparency)

### ISSUE THREAD

**Issue by bitfabrikken** [invertase/react-native-google-mobile-ads#221]
## Documentation Feedback

![image](https://user-images.githubusercontent.com/2039652/189320801-7a18610e-fd98-42d5-948a-205d5d8c21bf.png)

The docs do not explain how to detect what the user has chosen, after a choice has been made in Apple's ATT popup.

This seems like something that should be in the module - why even ask the user in the first place, if you can't see the answer?

If tracking is allowed by the user, one would then initialize admob with requestNonPersonalizedAdsOnly = false - I assume.
But there is no way to tell what the user has chosen.

Some possible references:
Docs for how to maybe implement it (wish I was able to): 
https://developer.apple.com/documentation/apptrackingtransparency/attrackingmanager/authorizationstatus

A module that can read the status of what the user chooses in the dialog: 
https://github.com/birgernass/react-native-ad-consent

**Comment by mikehardy** [comment]
Why would you not use the canonical module for the same? https://github.com/zoontek/react-native-permissions

**Comment by bitfabrikken** [comment]
> Why would you not use the canonical module for the same? https://github.com/zoontek/react-native-permissions

Not sure what you mean by canonical in this sense.
But I am not using that module currently, I try to keep the use of modules to a minimum. 
Less to maintain in my apps that way.
To me, it would make sense to be able to see what the user chooses in a prompt which is launched by the same module.

**Comment by mikehardy** [comment]
I see what you are saying, but to me (maintainer) I try to spread maintenance cost out to locations where there are maintainers willing to maintain things. Because in my world (of trying to keep modules working) maintenance resources are the actual constraint in the open source ecosystem.

If you propose a PR (that is: help maintain things), you'll certainly have my ear

**Comment by dylancom** [comment]
https://github.com/birgernass/react-native-ad-consent has been integrated into this module btw by it's author.

**Comment by bitfabrikken** [comment]
@mikehardy
I'd like nothing more than submit a PR, but I have zero knowledge of swift/objc - willing to learn though. 

But I don't know how to setup react-native-google-mobile-ads for development.
RN docs only describe how to make a simple module, not how start developing on a module like this.

I've tried forking and cloning into node_modules, adding the xcodeproj to libraries and running - but I get a RTCFatal error "Unable to resolve module ./Version" from index.ts - so I'm missing something, probably obvious to you?

@dylancom 
Indeed, but no way to see if user has allowed/denied tracking. That requires ATTrackingManager, as far as what I can gather.

**Comment by DoctorJohn** [comment]
@bitfabrikken this repository comes with a [CONTRIBUTING.md](https://github.com/invertase/react-native-google-mobile-ads/blob/main/CONTRIBUTING.md) file. In there you find instructions how to get started contributing to this repository.

**Comment by bitfabrikken** [comment]
> @bitfabrikken this repository comes with a [CONTRIBUTING.md](https://github.com/invertase/react-native-google-mobile-ads/blob/main/CONTRIBUTING.md) file. In there you find instructions how to get started contributing to this repository.

Thank you, that's very helpful, had not seen it.

**Comment by mikehardy** [comment]
Also, I just ran refresh-example so the example itself is sparkling fresh (react-native 0.70.1) and I verified it runs ios/android in #226
