### ISSUE TITLE
[🐛] iOS - Close Button

### ISSUE THREAD

**Issue by dessorry** [invertase/react-native-google-mobile-ads#228]
With iPhone 14 Pro Max ad close button is in the status bar and is impossible to click it.

**Comment by mikehardy** [comment]
Hi there! You've included essentially no information to help, that makes it hard to help:

https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/minimal-reproducible-example

Following the guidelines there demonstrates empathy with us, your fellow developers, when you wish to collaborate on issues

This reminds me of this: https://github.com/invertase/react-native-google-mobile-ads/issues/204
Also this seems .... related but not quite on target: https://github.com/invertase/react-native-google-mobile-ads/issues/136

But, those make me think two things:
- maybe the SDK has an issue - worth searching in their google forum (that's where their offiical support is: https://groups.google.com/forum/#!forum/google-admob-ads-sdk
- maybe there is a workaround you can do? Or something about safe-area-context, or...any sort of hack really

Alternatively - if you look in our iOS code here at the full size ads, perhaps there is something missing in there? Have you investigated at all?  Maybe in here, but you haven't mentioned what kind of ad is in use at all https://github.com/invertase/react-native-google-mobile-ads/blob/main/ios/RNGoogleMobileAds/RNGoogleMobileAdsFullScreenAd.swift

**Comment by dessorry** [comment]
I've solved using a SafeAreaView as container for my App.
Thank you

**Comment by mikehardy** [comment]
Great news, thank you for reporting back

**Comment by CodingByJerez** [comment]
@dessorry how did you encapsulate interstitial in SafeAreaView?

**Comment by dessorry** [comment]
I haven't encapsulated the interstitial ad 
. It is still full screen mode but using a safe are view I'm able to close the ad
