### ISSUE TITLE
Refresh / reload expired interstitial ads 🔥

### ISSUE THREAD

**Issue by Rebsos** [invertase/react-native-google-mobile-ads#233]
## Issue

I've got an email from AdMob suggesting to check my code. There may be X missed revenue due to e. g. stale / expired interstitial ads. They said ads expire after 1 hour.

**How to refresh an ad after it is already loaded?**

I think this is a common case. My users are always one click away from an interstitial. But they often just open the app, scroll and close it again (app in background). After some time e. g. 2 hours they open the app again and click (interstitial shown). But then it is stale and does not count.

I've created a [repository](https://github.com/Rebsos/react-native-google-mobile-ads-reload-interstitial) to test the behavior of this package with the ad inspector (Android)

1. After one hour this package does not refresh a once loaded interstitial ad automatically (no request in the ad inspector)
2. If you run interstitial.load() again, it does not load a new ad.
3. The package is capable to load a second ad, but only if the ad is shown before

Or in other words:

```
interstitial.load() => interstitial.load()                           // does not work
interstitial.load() => interstitial.show() => interstitial.load()    // does work!
```

One bad solution is to run createForAdRequest again. But there seems to be a memory leak. Any new instance+load adds around 1mb

---

#### `package.json`:

```json
{
  "name": "rn_0_70_1_admob_reload",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "18.1.0",
    "react-native": "0.70.1",
    "react-native-google-mobile-ads": "^8.1.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.72.1",
    "react-test-renderer": "18.1.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

#### `admob.json`:

```json
{
  "name": "rn_0_70_1_admob_reload",
  "displayName": "rn_0_70_1_admob_reload",
  "react-native-google-mobile-ads": {
    "android_app_id": "ca-app-pub-3940256099942544~3347511713",
    "ios_app_id": "ca-app-pub-xxxxxxxx~xxxxxxxx"
  }
}

```

</details>

#### `ios/Podfile`:

---

#### `AndroidManifest.xml`:

---

## Environment

**`react-native info` output:**

```
System:
    OS: macOS 12.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 106.96 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8139111
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.1 => 0.70.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [X] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [X] **Android** but have not tested behavior on iOS
  - [ ] Both
- **Are you using `TypeScript`?**
  - `N`

</p>
</details>

---

- 👉 Check out [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hmm - sounds like multiple issues at once 
- the memory leak - do you have any more information on that? How you diagnosed it, and if you could track it down to some resource that's not released? That's a quick way to kill an app
- no ability to expire an ad, if ads do in fact expire in an hour that seems like something the module *could* handle by tracking the load time vs the requested show, exposing that for local inventory management purposes, and perhaps rejecting the show request for an expired ad. Rejecting like that would be a breaking change but seems like it could be valid, philosophically, in the interest of failing as fast as possible for developers vs losing revenue

To be clear about expectations, this is definitely a community effort here - I'm brainstorming ideas in this comment box but if this is affecting you, you will likely be the person to make a PR as you've got the motivation. I am happy to be a good steward here and collaborate and get anything reasonable merged+released but it is not a use case of mine so doing the work is not something I want to pursue with volunteer time.

**Comment by Rebsos** [comment]
> the memory leak - do you have any more information on that? How you diagnosed it, and if you could track it down to some resource that's not released? That's a quick way to kill an app

I've created a simple [repository](https://github.com/Rebsos/react-native-google-mobile-ads-reload-interstitial) with 4 buttons: createForAdRequest(), load(), show(), Ad inspector. In the ad inspector and logs i could see what happens. To see the memory increasement I run "adb shell dumpsys meminfo com.rn_0_70_1_admob_reload" multiple times and track the "Total PSS" value. E. g. click 10x createForAdRequest() + load(), then wait at least 10 minutes (garbage collection) and run "adb shell dumpsys meminfo com.rn_0_70_1_admob_reload"

> you will likely be the person to make a PR


I'm pobably not qualified enough to solve this. The problem may be a little bit deeper. I tried some simple solutions like removing these lines from [MobileAd.ts](https://github.com/invertase/react-native-google-mobile-ads/blob/main/src/ads/MobileAd.ts)

```
if (this._loaded || this._isLoadCalled) {
    return;
}
```

Now it seems to work, but any new ad "load()" will increase the memory usage about 1mb = memory leak. So it is not better than running createForAdRequest() and then load(). Maybe even worse. Who knows if it takes the old or new ad.

**One more** thing is that if load() then show() is run, it definitely cleans it up afterwards. Sometimes you have to wait a little bit until the memory usage goes down. But I can't find the cleanup code, so I can't solve this. For me it would be totally enough just being able to run load() multiple times without memory leak to refresh expired ads or interstitial.destroy() or interstitial.clean().

**Comment by mikehardy** [comment]
Well, even if not a solution - a really clean reproduction is worth a lot, thanks very much for taking the time to do that

**Comment by mikehardy** [comment]
This needs attention - not sure if I'll have the time, but perhaps having an ad.destroy() method that releases previous resources? Or maybe having a reload that destroys/loads the same request?

Some thought about API / use case flow here could pay off. Should we support an isExpired method ? I don't know what would be useful here but I am open to ideas + PRs

**Comment by quan2nd** [comment]
I have a problem that may also be related to this topic.
The question
https://groups.google.com/g/google-admob-ads-sdk/c/cyhsw0QvGCI
After loading Interstitial successfully, how after some time can I check that Interstitial is ready to show

**Comment by Rebsos** [comment]
If someone creates a PR, I'm happy to test it for memory leaks

Little note:
[AppLovin](https://github.com/appodeal/react-native-appodeal#gdprccpa) has an isExpired event listener, but AdMob (native) seems to have no equivalent. Even if there is, it won't solve the main problem releasing previous resources like @mikehardy said
