### ISSUE TITLE
[🐛] ios - Unable to Close Some Interstitial Ads

### ISSUE THREAD

**Issue by TestCK** [invertase/react-native-google-mobile-ads#234]
Hi,

First thanks for this library, it helped me to easily integrate Ad mob with my app.

One thing I wanted to report is, some of my iOS users has been getting some Interstitial  ads, where the close button overlaps with the status bar. It doesn't happen often but if user gets such ad, the only way is to close the app and restart.

If tried playing around  with the safearea and still those kind of ads appear. So I wanted to check is there any way to make the ad close button always appear within the safearea of the app.

I am on the latest version of the library
React Native - 0.69.5
Expo SDK - 46.0.0

 
![IMG_4413](https://user-images.githubusercontent.com/74267332/193113792-9ae24571-14bc-400d-88db-1b72b788e83d.png)

**Comment by mikehardy** [comment]
Maybe #204 ? Could use a fresh look if you check the related issues + the admob google forum https://groups.google.com/g/google-admob-ads-sdk/ etc ?

**Comment by CodingByJerez** [comment]
I have the same problem it's for iPhone 14 pro

**Comment by mikehardy** [comment]
@CodingByJerez that is just a "metoo" comment, it does not provide value. I provided a couple links above where you could investigate and report findings (if any) vs metoos

Please do not post metoos.

**Comment by TestCK** [comment]
I ended up hiding the status bar for my app. Not sure if there is any other way

**Comment by sevketaydogdu** [comment]
still needs help on this. Some of iPhone's close button under safe area.
