### ISSUE TITLE
[🐛] Cannot get property 'googleMobileAdsJson'

### ISSUE THREAD

**Issue by namikarif** [invertase/react-native-google-mobile-ads#238]
`
"react-native": "^0.63.4",
"react-native-google-mobile-ads": "^8.1.1"
`

`
1: Task failed with an exception.
-----------
* Where:
Build file '/Users/namik/Codes/Disnot/node_modules/react-native-google-mobile-ads/android/build.gradle' line: 75

* What went wrong:
A problem occurred evaluating project ':react-native-google-mobile-ads'.
> Cannot get property 'googleMobileAdsJson' on extra properties extension as it does not exist

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':react-native-google-mobile-ads'.
> compileSdkVersion is not specified.

`

**Comment by DoctorJohn** [comment]
Please search existing issues before posting new ones. Take a look at #237 

_This drives me crazy_

**Comment by mikehardy** [comment]
@namikarif I will add that  your question does nearly ever thing wrong with regards to interfacing with other humans for help. Here's a handy guide for the future, please read it --> https://stackoverflow.com/help/how-to-ask

**Comment by Hamadahmad000** [comment]
What's the solution ?

**Comment by Hamadahmad000** [comment]
i'm facing this error i have added google ad id in package.json file but this error still remain if i remove react-native-google-mobile-ads library then project build successfully when i install this library then proble occur

**Comment by DoctorJohn** [comment]
> i have added google ad id in package.json file

Where did you read that you should do that?

Also: This issue is invalid. You should open a new one.

**Comment by muhammadashfaq** [comment]
+1

**Comment by Dablu77** [comment]
FAILURE: Build completed with 2 failures.                                                                                                                                                                                                       1: Task failed with an exception.                                                                                       -----------                                                                                                             * Where:                                                                                                                Build file 'D:\K\node_modules\react-native-google-mobile-ads\android\build.gradle' line: 82                                                                                                                                                     * What went wrong:                                                                                                      A problem occurred evaluating project ':react-native-google-mobile-ads'.                                                > Cannot get property 'googleMobileAdsJson' on extra properties extension as it does not exist

**Comment by Dablu77** [comment]
Please everyone finds solutions
![Screenshot (180)](https://github.com/invertase/react-native-google-mobile-ads/assets/98605321/32e7db7a-b16e-4478-b627-617b30b1d37d)

**Comment by Dablu77** [comment]
> @namikarif I will add that your question does nearly ever thing wrong with regards to interfacing with other humans for help. Here's a handy guide for the future, please read it --> https://stackoverflow.com/help/how-to-ask

![image](https://github.com/invertase/react-native-google-mobile-ads/assets/98605321/2fcada8f-f61a-4927-ab23-ca6f33920db8)

**Comment by mikehardy** [comment]
@Dablu77 I have deleted your comments. They are not useful for troubleshooting and they have nothing to do with the original issue. This is something I consider bad behavior on an issues thread in github, please don't behave this way https://stackoverflow.com/help/how-to-ask
