### ISSUE TITLE
[🐛] Bug Report Title - React Native google mobile ads not working on real device, Rewarded ads working on Emulator but crashing on real device

### ISSUE THREAD

**Issue by Aadam322** [invertase/react-native-google-mobile-ads#241]
I am creating a react native app, In my Emulator google mobile ads (Rewarded testing ads) working very well. but when I test the app on my real device(Personal phone) then the rewarded Ads not work, it crashed the app, only banner ads working on real device.

What is the problem, could anyone please reply with a solution?

Thank you in advance for your great support

Here below is the code I am using for rewarded ads

    import React, { useState, useEffect } from "react";
    import { View, Button, Text, ScrollView, } from 'react-native'
    import { RewardedAd, RewardedAdEventType, TestIds } from 'react-native-google-mobile-ads';
    
    const adUnitId = __DEV__ ? TestIds.REWARDED : 'ca-app-pub-3940256099942544/5224354917';
    
    const rewarded = RewardedAd.createForAdRequest(adUnitId, {
      requestNonPersonalizedAdsOnly: true,
      keywords: ['fashion', 'clothing'],
    });
    
    const Testing = ({ navigation }) =>{
        const [loaded, setLoaded] = useState(false);
    
        useEffect(() => {
          const unsubscribeLoaded = rewarded.addAdEventListener(RewardedAdEventType.LOADED, () => {
            setLoaded(true);
            rewarded.show();
          });
          const unsubscribeEarned = rewarded.addAdEventListener(
            RewardedAdEventType.EARNED_REWARD,
            reward => {
              console.log('User earned reward of ', reward);
            },
          );
      
          // Start loading the rewarded ad straight away
          rewarded.load();
      
          // Unsubscribe from events on unmount
          return () => {
            unsubscribeLoaded();
            unsubscribeEarned();
          };
        }, []);
      
        return (
            <ScrollView>
            <View style={{flex:1, justifyContent : 'center',alignItems : 'center'}}>
            <Text> 
            Lorem Ipsum is simply dummy text of the printing and typesetting industry.
            Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
             </Text>
            <Button onPress = {() => navigation.navigate('First')} title='Next Screen'></Button>
               </View>
            </ScrollView>
        )
        
        }
        export default Testing;

**Comment by DoctorJohn** [comment]
Half of the issue template is missing. Including whether this happens on iOS or Android.

**Comment by mikehardy** [comment]
"It crashed the app" --> so the crash trace is important. You did not include it.

**Comment by Aadam322** [comment]
Sorry for my late response, Sir could you please check my StackOverflow question link, here I included screenshots of the crash bug report-
https://stackoverflow.com/questions/74010695/admob-react-native-google-mobile-ads-not-working-on-real-device-rewarded-ads-wo

**Comment by Aadam322** [comment]
@DoctorJohn it's happening on Android App, I have not tested the app yet on ios.
should I need to add this below line-
-keep public class com.google.android.gms.ads.** { public *; }

**Comment by mikehardy** [comment]
I'll have a release with a fix for this shortly - just packaging it up now locally after doing some tests.

**Comment by Aadam322** [comment]
@mikehardy It's working Sir, Thank you so much for your great support.

**Comment by giannis21** [comment]
for me it does not work..Android 11 POCO M3 PRO 5g... i tried both las version and 8.1.2 version

**Comment by mikehardy** [comment]
@giannis21 this is an old + closed bug, please open a new issue with full details (like, a crash trace from `adb logcat` if it is crashing...) to access help.
