### ISSUE TITLE
Help on resolving Admob errors in the app

### ISSUE THREAD

**Issue by TestCK** [invertase/react-native-google-mobile-ads#249]
Hi,

This is not more of a bug, but just wanted to get some clarifications on the below errors.

I was checking through my app logs and found below errors related to ad mob. I am getting ads most of the time but some of the request seems to fail with below errors. Are there any ways to fix these errors?

Thanks for your time and this awesome library.

```
"[googleMobileAds/no-fill] Request Error: No ad to show.",
"[googleMobileAds/timeout] Request Error: The Google ad request was unable to be fulfilled before a timeout occurred.",
"[googleMobileAds/no-fill] No ad config.",
"[googleMobileAds/network-error] The network connection was lost.",
"[googleMobileAds/mediation-no-fill] Request Error: No ad to show from all configured ad networks.",
"[googleMobileAds/internal-error] Unable to obtain a JavascriptEngine.",
"[googleMobileAds/internal-error] Received error HTTP response code: 400",
"[googleMobileAds/error-code-no-fill] The ad request was successful, but no ad was returned due to lack of ad inventory.",
"[googleMobileAds/error-code-internal-error] Something happened internally; for instance, an invalid response was received from the ad server."]
```

I am on the latest version of the library
React Native - 0.69.5
Expo SDK - 46.0.0

**Comment by mikehardy** [comment]
Wow, that's a collection that seems "half and half" to me. no-fills in general happen and network disconnects happen, so "no inventory" and network-type things seem expected, but the other half...

"no ad config"?
"Unable to obtain a JavascriptEngine" ?! what
400 and also an internal error

I would search their upstream support list - https://groups.google.com/g/google-admob-ads-sdk/ - that's where I go digging for string matches on error messages. I do not personally know why those would show up.

> Thanks for your time and this awesome library.

Much appreciated! Glad it helps - hopefully there is some info on the mailing list that gets to the root of what can cause those odd errors

**Comment by panktiszluck** [comment]
Hi, I am getting below error for testIds, happening with interstitial video, interstitial reward, and rewarded video ads.
`[Error: [googleMobileAds/no-fill] Request Error: No ad to show.]`

I have configured and initialize as below
```
try {
      mobileAds()
        .setRequestConfiguration({
          // Update all future requests suitable for parental guidance
          maxAdContentRating: MaxAdContentRating.PG,

          // Indicates that you want your content treated as child-directed for purposes of COPPA.
          tagForChildDirectedTreatment: true,

          // Indicates that you want the ad request to be handled in a
          // manner suitable for users under the age of consent.
          tagForUnderAgeOfConsent: true,

          // An array of test device IDs to allow.
          testDeviceIdentifiers: [
            'EMULATOR',
            'E62FB4E1-FEAF-XXXX-XXXX-XXXXXXXXXXXX'
          ]
        })
        .then(() => {
          // Request config successfully set!
          //Initialize react-native-google-mobile-ads
          mobileAds()
            .initialize()
            // eslint-disable-next-line @typescript-eslint/no-unused-vars
            .then((adapterStatuses: any) => {
              // Initialization complete!
              // console.log('adapterStatuses', adapterStatuses);
              setIsAdInit(true);
            });
        });
    } catch (e: any) {
      // eslint-disable-next-line no-restricted-syntax
      console.log(e);
    }
```

Using ad hooks for implementations like,
```
  //Interstitial Ad object
  const interstitialAd = useInterstitialAd(adInterUnitId, {
    requestNonPersonalizedAdsOnly: true
  });
```

Expected:
Show ad when call `interstitialAd.show();`

Actual:
`[Error: [googleMobileAds/no-fill] Request Error: No ad to show.]`

**Comment by mikehardy** [comment]
@panktiszluck 1) that is thread-jacking. Open a new issue minding the general best practices of https://stackoverflow.com/help/how-to-ask and https://stackoverflow.com/help/minimal-reproducible-example plus the issue template for specifics, 2) read the no fill docs, use the ad inspector etc
