### ISSUE TITLE
[🐛] There is a error with European User Consent (Expo)

### ISSUE THREAD

**Issue by StruanMclean** [invertase/react-native-google-mobile-ads#250]
Error

```
 ERROR  [SyntaxError: Unexpected identifier '_reactNativeGoogleMobileAds'. Expected ';' after variable declaration.]
```

code

```
import { AdsConsent, AdsConsentStatus } from 'react-native-google-mobile-ads';

const consentInfo = await AdsConsent.requestInfoUpdate();

if (consentInfo.isConsentFormAvailable && consentInfo.status === AdsConsentStatus.REQUIRED) {
  const { status } = await AdsConsent.showForm();
}
```

Android

```
    "android": {
      "softwareKeyboardLayoutMode": "pan",

      "extraProguardRules": "-keep class com.google.android.gms.internal.consent_sdk.** { *; }",

      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#FFFFFF"
      },
      "package": "Hidden",
      "versionCode": 8
    },
```

Package

```
  "react-native-google-mobile-ads": {
    "android_app_id": "Hidden",
    "ios_app_id": "Hidden",
    "delay_app_measurement_init": true,
    "user_tracking_usage_description": "We make money by using personalized ads these keep the UListIt project running."
  }
```

Please Help!
Thanks =)

**Comment by mikehardy** [comment]
:thinking: but...our example runs fine, so we have a reproduction (https://stackoverflow.com/help/minimal-reproducible-example) that I can check out and run and it works

I suspect a version or something is wrong but you haven't specified them (https://stackoverflow.com/help/how-to-ask) so I can't speculate.

Given we have a working repro, to advance this you'll have to either compare your project to the working repro that is our example app here in this repository and determine the problem by looking at the differences, or post a repro that shows the problem.

Note that our repro is even constructed automatically, so you can use that as a basis to create any google-mobile-ads reproduction really https://github.com/invertase/react-native-google-mobile-ads/blob/main/refresh-example.sh

**Comment by mikehardy** [comment]
Hey @smjkdz - Could you or someone that uses Expo and knows exactly how to configure it well add a note to this section via a PR? https://github.com/invertase/react-native-google-mobile-ads/blob/main/docs/european-user-consent.mdx#handling-consent

**Comment by smjkdz** [comment]
@mikehardy already available in Expo docs [https://docs.expo.dev/versions/latest/sdk/build-properties/#pluginconfigtypeandroid](https://docs.expo.dev/versions/latest/sdk/build-properties/#pluginconfigtypeandroid)
You can add this link to the docs I think.

**Comment by mikehardy** [comment]
@smjkdz *you* can add this link to the docs I think - please hit that edit button :pray:  - github PR web flow is trivial - we are collaborative here, not paternalistic. You're not the module user, you're also a developer!

**Comment by StruanMclean** [comment]
Thanks!
