### ISSUE TITLE
[📚] Missing documentation when gathering User consent - Failed to read publisher's account configuration

### ISSUE THREAD

**Issue by MadeinFrance** [invertase/react-native-google-mobile-ads#256]
## Feedback

I probably overlooked how to set up Admob IDs. When calling the method: `AdsConsent.requestInfoUpdate()` the create-app project exit with the exception:

`Error: Failed to read publisher's account configuration; try again later.`

 In the example project `RNGoogleMobileAdsExample` it works 👍
 
 What's the missing part of the create-app project to use this framework? See playground  with reproducible error: https://github.com/MadeinFrance/admob-test

**Comment by mikehardy** [comment]
I do not know what a "create-app" project is? Sorry
Careful on your repository with the admob IDs, they are not the most closely guarded secrets but exposing them can expose you to fraud and account shutdown

...unless they are the test ids, then that's one of the answers stackoverflow provides:
https://stackoverflow.com/questions/68457966/failed-to-read-publishers-account-configuration-please-check-your-configured-a

I don't have any special insight other than broad search: https://search.brave.com/search?q=Error%3A+Failed+to+read+publisher%27s+account+configuration%3B+try+again+later+admob&source=desktop

**Comment by MadeinFrance** [comment]
Thank you, I guess my consent form wasn't available.

**Comment by idanlevi1** [comment]
> Thank you, I guess my consent form wasn't available.

How do know if is available? how did you solve it?

**Comment by mikehardy** [comment]
@idanlevi1 if I understand correctly, it will not be available until your account setup is completely finished + activated
