### ISSUE TITLE
🔥[🐛] CocoaPods could not find compatible versions for pod "GoogleAppMeasurement"

### ISSUE THREAD

**Issue by rnkdsh** [invertase/react-native-google-mobile-ads#259]
## Issue

```
[!] CocoaPods could not find compatible versions for pod "GoogleAppMeasurement":
  In Podfile:
    RNFBAnalytics (from `../node_modules/@react-native-firebase/analytics`) was resolved to 16.3.1, which depends on
      Firebase/Analytics (= 10.1.0) was resolved to 10.1.0, which depends on
        Firebase/Core (= 10.1.0) was resolved to 10.1.0, which depends on
          FirebaseAnalytics (~> 10.1.0) was resolved to 10.1.0, which depends on
            FirebaseAnalytics/AdIdSupport (= 10.1.0) was resolved to 10.1.0, which depends on
              GoogleAppMeasurement (= 10.1.0)

    RNGoogleMobileAds (from `../node_modules/react-native-google-mobile-ads`) was resolved to 8.2.0, which depends on
      Google-Mobile-Ads-SDK (= 9.10.0) was resolved to 9.10.0, which depends on
        GoogleAppMeasurement (< 10.0, >= 7.0)
```

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `admob.json`:

```json
# N/A
```
</p>
</details>

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

```ruby
# N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 System:
    OS: macOS 13.0
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 236.64 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.9.0 - /usr/local/bin/node
    Yarn: 1.22.18 - ~/.yarn/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
    Watchman: 2022.10.17.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      API Levels: 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33
      Build Tools: 30.0.3, 31.0.0, 32.0.0, 33.0.0
      System Images: android-21 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-32 | Google Play Intel x86 Atom_64
      Android NDK: 23.0.7344513-beta4
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 16.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.70.4 => 0.70.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **Are you using `TypeScript`?**
  - `N`

</p>
</details>

---

- 👉 Check out [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by anisoft89** [comment]
I have latest version but still same issue.

`[!] CocoaPods could not find compatible versions for pod "Google-Mobile-Ads-SDK":
  In Podfile:
    Google-Mobile-Ads-SDK (= 8.2.1)

    RNGoogleMobileAds (from `../node_modules/react-native-google-mobile-ads`) was resolved to 8.2.1, which depends on
      Google-Mobile-Ads-SDK (= 9.12.0)

None of your spec sources contain a spec satisfying the dependencies: `Google-Mobile-Ads-SDK (= 8.2.1), Google-Mobile-Ads-SDK (= 9.12.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.`

**Comment by mikehardy** [comment]
@anisoft89 you have a direct entry for `Google-Mobile-Ads-SDK` in your Podfile. If you do that, how can this module manage the version 🤔 ?

Try removing it.

**Comment by anisoft89** [comment]
Removed it now, but still error.

`[!] CocoaPods could not find compatible versions for pod "Google-Mobile-Ads-SDK":
  In Podfile:
    RNGoogleMobileAds (from '../node_modules/react-native-google-mobile-ads') was resolved to 8.2.1, which depends on
      Google-Mobile-Ads-SDK (= 9.12.0)

None of your spec sources contain a spec satisfying the dependency: 'Google-Mobile-Ads-SDK (= 9.12.0)'.

You have either:
 * out-of-date source repos which you can update with 'pod repo update' or with 'pod install --repo-update'.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.`

**Comment by anisoft89** [comment]
`pod install --repo-update`
solved the problem.

**Comment by devbalmuda** [comment]
v8.2.0 solved my issue. But i used the JSC engine not hermes .

**Comment by wesleyguirra** [comment]
Reopening the issue since it starting to happen again with current version of react-native-firebase/analytics
