### ISSUE TITLE
Attempted to request a consent info update but the current Activity was null.

### ISSUE THREAD

**Issue by nes123** [invertase/react-native-google-mobile-ads#266]
### What happened?

Getting an error message 

Attempted to request a consent info update but the current Activity was null.

after calling

<a class="DataTable" data-interactive="true" style="box-sizing: border-box; background-color: rgb(248, 248, 248); color: rgb(33, 33, 33); text-decoration: none; font-feature-settings: &quot;tnum&quot;, &quot;lnum&quot;; display: block; position: relative; outline: 0px; font-family: kievit, serif, avenir, &quot;lucida grande&quot;, &quot;gill sans&quot;, &quot;helvetica neue&quot;, helvetica, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px;">

AdsConsent.requestInfoUpdate

</a>

### Platforms

Only on Android

### React Native Info

```shell
System:
    OS: macOS 12.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 24.97 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.0.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 8.6.0 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8139111
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.3 => 0.68.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Are your using Typescript?

- [X] My project is using Typescript

### package.json

```json
"react-native-google-mobile-ads": "^8.2.1",
```

### app.json

```json
{
  "name": "MyApp",
  "displayName": "MyApp",
  "react-native-google-mobile-ads": {
      "android_app_id": "ca-app-pub-##~##",
      "ios_app_id": "ca-app-pub-##~##",
      "delay_app_measurement_init": true
  }
}
```

**Comment by mikehardy** [comment]
Hi there! This sounds like an android crash? If it is, could you please attach the actual crash trace from `adb logcat`?

**Comment by mikehardy** [comment]
There is no sentry or crashlytics or ACRA integration? Native crashes really need native crash traces. This is not enough to go on without the trace

**Comment by nes123** [comment]
I am using bugsnag to catch the promise error and write the log. I am not sure how I can print the native part. Will have a look.

**Comment by nes123** [comment]
It seems that

implementation 'com.google.android.ads.consent:consent-library:1.0.6'

should be included. I didn't see it in the docs. Am I wrong?

**Comment by mikehardy** [comment]
I believe this line is the important part for consent:

https://github.com/invertase/react-native-google-mobile-ads/blob/95d53cb9c79275c92b69e61d95cacef85aa434d9/android/build.gradle#L121

Crash traces are vital for crash reports, still haven't seen one - it would provide some evidence for or against your assertion on dependencies required-but-missing

**Comment by nes123** [comment]
I suspect there is no native trace available.

It looks like the package produces the error message via: https://github.com/invertase/react-native-google-mobile-ads/blob/main/android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsConsentModule.java#L86-L92

Which also appears to swallow the native errors:
https://github.com/invertase/react-native-google-mobile-ads/blob/main/android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsConsentModule.java#L109

The code ends with https://github.com/facebook/react-native/blob/main/ReactAndroid/src/main/java/com/facebook/react/bridge/Promise.java#L92-L100
which does not include a native Exception at all, and therefore no native stacktrace.
