### ISSUE TITLE
[🐛] Not working with react-native-push-notification

### ISSUE THREAD

**Issue by alz10** [invertase/react-native-google-mobile-ads#268]
### What happened?

The library won't work with [react-native-push-notification](https://github.com/zo0r/react-native-push-notification)

```
* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
```
`Duplicate class com.google.android.gms.internal.measurement.zzbm found in modules jetified-play-services-measurement-17.3.0-runtime (com.google.android.gms:play-services-measurement:17.3.0) and jetified-play-services-measurement-base-20.1.2-runtime (com.google.android.gms:play-services-measurement-base:20.1.2)`

### The app will install if i remove this in _android/app/build.gradle_ dependencies
`implementation 'com.google.firebase:firebase-analytics:17.3.0'` 
But I need that because my application uses remote notification

### Platforms

Only on Android

### React Native Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (8) x64 Apple M1
    Memory: 28.13 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.6.2 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.0.0 - /opt/homebrew/bin/npm
    Watchman: 2022.01.31.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.5 => 0.70.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Are your using Typescript?

- [X] My project is using Typescript

### package.json

```json
{
  "name": "wrpocketguide",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "18.1.0",
    "react-native": "0.70.5",
    "react-native-google-mobile-ads": "^8.2.1",
    "react-native-push-notification": "^8.1.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "0.72.3",
    "react-test-renderer": "18.1.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

### app.json

```json
{
  "name": "app",
  "displayName": "app",
  "react-native-google-mobile-ads": {
    "android_app_id": "ca-app-pub-my-own-app-id"
  }
}
```

**Comment by mikehardy** [comment]
That library hasn't had a release in more than a year, so it has outdated dependencies, and they may collide.

Suggest using https://notifee.app as it is reasonably maintained or patch-package to bump the SDKs in that [apparently unmaintained library](https://github.com/zo0r/react-native-push-notification/graphs/code-frequency), somewhere here https://github.com/zo0r/react-native-push-notification/blob/fcf40a05175bb79fb5fdfe2ac31bb797bc5008bc/android/build.gradle#L63

We *must* use up to date native SDKs here, and if some other module is not up to date, we can't help much.
