### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by techday84** [invertase/react-native-google-mobile-ads#276]
### What happened?

Hi, it is not a bug, it is only a question. I implemented react native google mobile ads on my app. My app shows this type of ads "ads when App Open". I see other apps that shows an ads when pass from background state to active state, I try to do the same and it is working but I have a problem.

Inside my app I use inappbrowser to open a url inside my app and other utilities like react-native-share. When I click on a url or share content or other actions, the ad (ads when app open) fires again after share content o after press on the link. I don't want to show the ad in these cases, but when the user goes to another app and then he return to my app I want to show the ad. It is possible?

I don't know how other apps can show the ad only when the app goes from background to active in the same app and never when the user share content and other utilities. I don't know if it is not possible with this or maybe I make a mistake in my code. Can someone helpe me? 

Thanks a bunch!

```
 useEffect(() => {
     ...

      const subscription = AppState.addEventListener("change", nextAppState => {
        if (
          appState.current.match(/inactive|background/) &&
          nextAppState === "active"
        ) {
          console.log("App has come to the foreground!");
          if(interstitialLoaded){
            appOpenAd.show();
          }
        }
  
        appState.current = nextAppState;
        setAppStateVisible(appState.current);
        
      });
    
      return () =>{
        subscription.remove();
        unsubscribe_open_onAdLoad();
        unsubscribe_open_onAdClosed();
      };


}, [appStateVisible,interstitialLoaded]);
```

### Platforms

Only on Android

### React Native Info

```shell
.
```

### Are your using Typescript?

- [X] My project is using Typescript

### package.json

```json
.
```

### app.json

```json
.
```

### ios/Podfile

```ruby
.
```

### android/build.gradle

```groovy
.
```

### android/app/build.gradle

```groovy
.
```

### android/settings.gradle

```groovy
.
```

### AndroidManifest.xml

```xml
.
```

**Comment by mikehardy** [comment]
In Android, modals are "outside" your activity so they trigger lifecycle events for the activity
I think this is relevant, what do you think?
https://github.com/invertase/react-native-google-mobile-ads/issues/102

**Comment by zoobibackups** [comment]
same issue. I navigate user to maps are share but app open ads it displaying
