### ISSUE TITLE
i[🐛] Bug Report Title - ios_config.sh problem

### ISSUE THREAD

**Issue by medfrk** [invertase/react-native-google-mobile-ads#279]
### What happened?

when i ran the app with command yarn ios a error show with message:
info: -> RNGoogleMobileAds build script started
info: 1) Locating app.json file:
info:      (1 of 2) Searching in '...' for a app.json file.
Unknown option: n
Usage: head [-options] <url>...
    -m <method>   use method for the request (default is 'HEAD')
    -f            make request even if head believes method is illegal
    -b <base>     Use the specified URL as base
    -t <timeout>  Set timeout value
    -i <time>     Set the If-Modified-Since header on the request
    -c <conttype> use this content-type for POST, PUT, CHECKIN
    -a            Use text mode for content I/O
    -p <proxyurl> use this as a proxy
    -P            don't load proxy settings from environment
    -H <header>   send this HTTP header (you can specify several)

    -u            Display method and URL before any response
    -U            Display request headers (implies -u)
    -s            Display response status code
    -S            Display response status chain
    -e            Display response headers
    -d            Do not display content
    -o <format>   Process HTML content in various ways

    -v            Show program version
    -h            Print this message

    -x            Extra debugging output
Command PhaseScriptExecution failed with a nonzero exit code

after i opened the ios_config.sh and try to find the probleme it appear that the problem in the line 70 in the command:
  _SEARCH_RESULT=$(find "$_CURRENT_SEARCH_DIR" -maxdepth 2 -name ${_JSON_FILE_NAME} -print | head -n 1)
to resolve my probleme i have changed the command to

  _SEARCH_RESULT=$(find "$_CURRENT_SEARCH_DIR" -maxdepth 2 -name ${_JSON_FILE_NAME})

### Platforms

Only on iOS

### React Native Info

```shell
info Fetching system and libraries information...
System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
    Memory: 98.03 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.5.0 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Dolphin 2021.3.1 Patch 1 Dolphin 2021.3.1 Patch 1
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.5 => 0.68.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Are your using Typescript?

- [X] My project is using Typescript

### package.json

```json
{
  "name": "App Name",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "watch": "watchman watch-del '...' && watchman watch-project '...'",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "yarn watch && react-native start --reset-cache",
    "test": "jest",
    "lint": "eslint .",
    "build_apk": "npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res && cd android && ./gradlew assembleDebug && open app/build/outputs/apk/debug/",
    "build_aab": "npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res && cd android && ./gradlew bundleRelease && open app/build/outputs/bundle/release",
    "pod": "cd ios && pod install && cd .."
  },
  "dependencies": {
    "@freakycoder/react-native-progressive-fast-image": "^0.2.5",
    "@react-native-firebase/app": "^15.2.0",
    "@react-native-firebase/auth": "^15.2.0",
    "@react-native-google-signin/google-signin": "^8.0.0",
    "@react-navigation/bottom-tabs": "^6.3.1",
    "@react-navigation/drawer": "^6.4.1",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/native-stack": "^6.6.2",
    "apisauce": "^2.1.5",
    "date-fns": "^2.28.0",
    "date-fns-tz": "^1.3.5",
    "i18n-js": "^3.9.2",
    "intl": "^1.2.5",
    "lodash.memoize": "^4.1.2",
    "react": "17.0.2",
    "react-intl": "^6.0.4",
    "react-native": "0.68.5",
    "react-native-add-calendar-event": "^4.0.0",
    "react-native-bootsplash": "^4.3.0",
    "react-native-bouncy-checkbox": "^2.1.10",
    "react-native-bouncy-checkbox-group": "^0.1.0",
    "react-native-easy-grid": "^0.2.2",
    "react-native-fast-image": "^8.5.11",
    "react-native-fbsdk-next": "^10.0.0",
    "react-native-gesture-handler": "^2.4.2",
    "react-native-google-mobile-ads": "^8.2.0",
    "react-native-interactions": "^0.4.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-localization": "^2.3.1",
    "react-native-localize": "^2.2.2",
    "react-native-mmkv": "^2.4.1",
    "react-native-onesignal": "^4.4.0",
    "react-native-reanimated": "^2.8.0",
    "react-native-restart": "^0.0.24",
    "react-native-safe-area-context": "^4.3.1",
    "react-native-screens": "^3.13.1",
    "react-native-share": "^7.6.6",
    "react-native-simple-toast": "^1.1.3",
    "react-native-splash-screen": "^3.3.0",
    "react-native-svg": "^12.3.0",
    "react-native-video": "^5.2.0",
    "react-native-webview": "^11.22.7",
    "react-redux": "^8.0.2",
    "recyclerlistview": "^3.3.0-beta.2",
    "redux": "^4.2.0",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.4.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@bam.tech/react-native-make": "^3.0.3",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.67.0",
    "react-native-flipper": "^0.150.0",
    "react-native-mmkv-flipper-plugin": "^1.0.0",
    "react-test-renderer": "17.0.2",
    "redux-devtools-extension": "^2.13.9",
    "redux-flipper": "^2.0.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

### app.json

```json
{
  "name": "AppName",
  "displayName": "App Name",
  "react-native-google-mobile-ads": {
    "android_app_id": "ca-app-pub-.......",
    "ios_app_id": "ca-app-pub-......"
  }
}
```

**Comment by mikehardy** [comment]
Hi there - I've seen this before. If you open a terminal and type `which head` you'll see that there is an unexpected utility that answers to the name `head` in your path but is trying to perform an HTTP `HEAD` request instead of the expected utility that is part of BSD standard tools and grabs the first lines of a file

`man head` yields this for me:

```
HEAD(1)                      General Commands Manual                     HEAD(1)

NAME
     head – display first lines of a file

SYNOPSIS
     head [-n count | -c bytes] [file ...]


```

etc and is the utility in question.

The standard BSD head utility should be first in your PATH

**Comment by mikehardy** [comment]
Or try this - we changed the similar line in react-native-firebase to be a fully-specified path for the same reason, I think it's a reasonable solution:

https://github.com/invertase/react-native-firebase/blob/main/packages/app/ios_config.sh#L69

```bash
  _SEARCH_RESULT=$(find "$_CURRENT_SEARCH_DIR" -maxdepth 2 -name ${_JSON_FILE_NAME} -print | /usr/bin/head -n 1)
```

**Comment by medfrk** [comment]
thank you very much for your response:
i have tabed interminal the command 'which head' and give me the path to xampp head and i have changed the command to 
_SEARCH_RESULT=$(find "$_CURRENT_SEARCH_DIR" -maxdepth 2 -name ${_JSON_FILE_NAME} -print | /usr/bin/head -n 1)
and its work now.

**Comment by mikehardy** [comment]
Great - thanks for the feedback, I'm creating a PR with that fix now and I'll release it as soon as CI goes green

**Comment by medfrk** [comment]
Thank's a loot
