### ISSUE TITLE
[📚] Not enough documentation regarding the createForRequest function

### ISSUE THREAD

**Issue by HamsterBoi** [invertase/react-native-google-mobile-ads#282]
### Documentation Feedback

I saw the example for creating an ad i.e:
`const rewarded = RewardedAd.createForAdRequest(adUnitId, {
  requestNonPersonalizedAdsOnly: true,
  keywords: ['fashion', 'clothing'],
});`

but what if I want to create an ad with requestNonPersonalizedAdsOnly false? 
`const rewarded = RewardedAd.createForAdRequest(adUnitId, {);`
is this sufficient? because i see on firebase that the ads showing are nonpersonalized

**Comment by mikehardy** [comment]
The answer to your question may depend on a few things but you don't provide a lot of detail
https://stackoverflow.com/help/how-to-ask

A possible answer could be "on iOS, you have not obtained consent to show personalized ads"
