### ISSUE TITLE
[Question] Reload Banner

### ISSUE THREAD

**Issue by quan2nd** [invertase/react-native-google-mobile-ads#284]
### Documentation Feedback

Hello.
I have 2 questions.
1. Is there any way I can reload the banner?
2. Is there a mechanism to reload the banner in the library after a period of time or after the first loading of the banner fails?
Thank you.

**Comment by mikehardy** [comment]
🤔 

https://github.com/invertase/react-native-google-mobile-ads/issues?q=is%3Aissue+reload

https://github.com/invertase/react-native-google-mobile-ads/issues/195

https://github.com/invertase/react-native-google-mobile-ads/pull/245

The library does not track time or need to reload for your, it simply does what you ask imperatively, so any related logic will be project-specific in your project code

**Comment by quan2nd** [comment]
@mikehardy 
It seems the reload function only works for interstitial and reward. I don't know how to use the Banner.
I see google encourages Banner "can refresh automatically after a certain period of time."
https://developers.google.com/admob/flutter/banner/get-started

**Comment by dylancom** [comment]
Banner ads refresh every 30 / 60 seconds. You can leave that up to AdMob.
But in case you want to force reload the banner after some event you can just set a unique key on the banner.

**Comment by quan2nd** [comment]
> 

Thank you. Your way solved my problem.
