### ISSUE TITLE
Parent View with marginHorizontal doesn't affect BannerAd

### ISSUE THREAD

**Issue by caiqueex** [invertase/react-native-google-mobile-ads#287]
### What happened?

Hi all,

Parent View with marginHorizontal doesnt affect BannerAd

`          <View
            style={{
              margin: 16,
              alignItems: 'center',
              justifyContent: 'center',
            }}
          >
            <BannerAd
              unitId={TestIds.BANNER}
              size={BannerAdSize.ANCHORED_ADAPTIVE_BANNER}
            />
          </View>`

I already tested with margin, padding and width and nothing works... And I tested changing prop size in BannerAd too.

does anyone have a suggestion? I want margin because all my screen has 16px of padding/margin. 

![example](https://user-images.githubusercontent.com/8368079/206484885-17c0e3bb-5230-4d2a-9295-b7fbebba8ec0.jpeg)

### Platforms

Android and iOS

### React Native Info

```shell
doesn't apply
```

### Are your using Typescript?

- [X] My project is using Typescript

### package.json

```json
doesn't apply
```

### app.json

```json
doesn't apply
```

### ios/Podfile

```ruby
doesn't apply
```

### android/build.gradle

```groovy
doesn't apply
```

### android/app/build.gradle

```groovy
doesn't apply
```

### android/settings.gradle

```groovy
doesn't apply
```

### AndroidManifest.xml

```xml
doesn't apply
```

**Comment by mikehardy** [comment]
https://github.com/invertase/react-native-google-mobile-ads/blob/443405296804c0e29d17bda3abf162599f6e52ab/src/BannerAdSize.ts#L50-L64

Sounds like you might want FLUID type?

https://github.com/invertase/react-native-google-mobile-ads/blob/443405296804c0e29d17bda3abf162599f6e52ab/src/ads/BaseAd.tsx#L116-L124

Or you could experiment with measuring the container you want to put it in then sending in the size? https://github.com/invertase/react-native-google-mobile-ads/blob/443405296804c0e29d17bda3abf162599f6e52ab/src/types/BannerAdProps.ts#L48

**Comment by dylancom** [comment]
We currently only support device width adaptive banners. But ideally the package should also support setting a custom width.

**Comment by caiqueex** [comment]
> https://github.com/invertase/react-native-google-mobile-ads/blob/443405296804c0e29d17bda3abf162599f6e52ab/src/BannerAdSize.ts#L50-L64
> 
> Sounds like you might want FLUID type?
> 
> https://github.com/invertase/react-native-google-mobile-ads/blob/443405296804c0e29d17bda3abf162599f6e52ab/src/ads/BaseAd.tsx#L116-L124
> 
> Or you could experiment with measuring the container you want to put it in then sending in the size?
> 
> https://github.com/invertase/react-native-google-mobile-ads/blob/443405296804c0e29d17bda3abf162599f6e52ab/src/types/BannerAdProps.ts#L48

FLUID doest't respect the parent... I'm using my View with marginHorizontal but I added overflow hidden... It "works", but i piece of banner was cut

**Comment by dylancom** [comment]
Would this solve you're use-case @caiqueex?
https://github.com/invertase/react-native-google-mobile-ads/pull/296
Currently we allow setting a custom size like "300x200". This PR makes it possible to just set a width: `size="300x"` and get  an ad width auto height.
Or would it for e.g. be more clear if we'd used `size=300xauto`?

**Comment by caiqueex** [comment]
@dylancom I'll try it... My device is a galaxy fold 3, with 280px of width
