### ISSUE TITLE
[🐛] Excessive frozen frames over time jumped 300% on android

### ISSUE THREAD

**Issue by nes123** [invertase/react-native-google-mobile-ads#289]
### What happened?

InterstitialAd causes the app frozen frames on android apps to jump sharply. We removed them from the app, and it went back to normal. Any idea what might cause that?

### Platforms

Only on Android

### React Native Info

```shell
N/A
```

### Are your using Typescript?

- [X] My project is using Typescript

### package.json

```json
N/A
```

### app.json

```json
N/A
```

**Comment by mikehardy** [comment]
Hi there! No, and this isn't a lot to go on. Performance problems are notoriously difficult to pin down, I'd submit you'll need a reproduction and a dump of all the diagnostics accompanied by versions of everything and performance trace information. You should collaborate with official support to pursue it https://groups.google.com/g/google-admob-ads-sdk
