### ISSUE TITLE
Dev build error: `new NativeEventemitter() requires a non-null argument`

### ISSUE THREAD

**Issue by mikehardy** [invertase/react-native-google-mobile-ads#29]
To get rid of the `new NativeEventemitter() requires a non-null argument` warning/error in dev iOS needs to implement the required methods, carefully calling super methods and managing observer state etc. If Android also implements them (and arguably, it should) then it also needs to manage listener count status and not emit events if there are no listeners.

Solution sketch and more details on a related module here: https://github.com/react-native-netinfo/react-native-netinfo/issues/486#issuecomment-989836178

_Originally posted by @mikehardy in https://github.com/invertase/react-native-google-ads/issues/6#issuecomment-989991865_

**Comment by guyca** [comment]
We've been using the [following approach](https://github.com/wix/react-native-navigation/blob/b53f13c60fe6498ad1690adf1dfd7509f602965c/lib/src/adapters/NativeEventsReceiver.ts#L23) to work around this issue In [wix/react-native-navigation](https://github.com/wix/react-native-navigation). Been using it for 4 years without any issues, we can submit a PR if you're interested.

**Comment by mikehardy** [comment]
Hey @guyca :wave: - thanks for looking in to this and for the offer!
If we've got a reproduction of this then a PR would be great yes, but this *may* not be happening any more. This library was a pretty raw copy of old mature code 29 days ago, but in the last 29 days since the "raw copy" part of it has been polished up and at it's core it was old mature code. So this may no longer be a problem but I haven't prioritized issue triage yet (been prioritizing PR review + merge + release instead...)

**Comment by guyca** [comment]
gotcha! This issue reproduces for us in "3.2.x". We'll try v4 once it's out of beta and report back.

**Comment by mikehardy** [comment]
:thinking: v4 *shouldn't* fix that actually, it's only a major because a rewrite from JS to TS deserves flagging as a major I think but it's an abundance of caution, not really aimed at fixing things (other than module development experience)

Which unfortunately means if it was happening in 3.2.x it'll probably still reproduce. Which leaves us with "PRs definitely happily accepted" :-)

**Comment by guyca** [comment]
We'll submit a PR next week 👍
