### ISSUE TITLE
RewardedAd.show() The requested RewardedAd has not loaded and could not be shown.[🐛] Bug Report Title - CHANGE ME 

### ISSUE THREAD

**Issue by little-steps** [invertase/react-native-google-mobile-ads#291]
### What happened?

react-native-google-mobile-ads , i am working on this library and using this banner and interstitial  and showing but from 2 days I am working on rewarded ads it is displaying same error
 RewardedAd.show() The requested RewardedAd has not loaded and could not be shown.
I don't know where is the problem occur , i also change network and phone but still this problem is facing,
i am also not loading rewarded ads multiple time 

### Platforms

Only on Android

### React Native Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i7-4600M CPU @ 2.90GHz
    Memory: 1.45 GB / 6.93 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7935034
    Visual Studio: Not Found
  Languages:
    Java: 17.0.2
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.6 => 0.70.6
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Are your using Typescript?

- [X] My project is using Typescript

### package.json

```json
{
  "name": "last",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "18.1.0",
    "react-native": "0.70.6",
    "react-native-google-mobile-ads": "^8.2.2"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "0.72.3",
    "react-test-renderer": "18.1.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

### app.json

```json
"name": "last",
  "displayName": "last",
  "react-native-google-mobile-ads": {
    "android_app_id": "ca-app-pub-3710407208024096~4378320674"
  }
```

**Comment by DoctorJohn** [comment]
Could you share the code where you're calling `RewardedAd.show()` ?

**Comment by mikehardy** [comment]
You also might try the example app here. It uses the test IDs but it is my understanding that rewarded ads show just fine on Android.

**Comment by usamaehsan** [comment]
i am facing same issue, have you got any solution?

**Comment by little-steps** [comment]
@mikehardy I am trying both testid and with live app id but in both case it is not working 
my banner ad and intertitial ads are working properly only rewardad is giving this problem i don't know why

**Comment by little-steps** [comment]
> Could you share the code where you're calling `RewardedAd.show()` ?

same code copies from this library.
i have also check it in event listener on loaded

**Comment by anwargul0x** [comment]
Facing same issue on expo client build , rewarded ads aren't being loaded

**Comment by UsmanAlgoace** [comment]
Facing the same issue
