### ISSUE TITLE
Native Ads Support

### ISSUE THREAD

**Issue by sabinayakc** [invertase/react-native-google-mobile-ads#299]
### Question
- Does this library support Native ads?

### Description
I am new to admob and am trying to implement some basic ads to my react native app. I see that there is a new kind of ad callled `Native Ads` which are loaded using Native IOS/Android components. 

https://developers.google.com/admob/ios/native/start

Wanted to know if this library is planning to support this feature or something is on the works? 

I also found this repo which integrates the Native Ad so I am thinking we can integrate the code into this repo somehow or start a PR. 

https://github.com/ammarahm-ed/react-native-admob-native-ads

Thanks.

**Comment by dylancom** [comment]
Please use search before opening new issues. https://github.com/invertase/react-native-google-mobile-ads/issues/42
