### ISSUE TITLE
Rewarded ads (TestIds or real adUnits) not showing up on iOS (Error: [googleMobileAds/no-fill] Request Error: No ad to show.)

### ISSUE THREAD

**Issue by novirusallowed** [invertase/react-native-google-mobile-ads#301]
I am having problems for more than a week now in displaying RewardedAds on iOS.
I have followed the implementation example [here](https://docs.page/invertase/react-native-google-mobile-ads/displaying-ads#rewarded-ads) and also tried the one that is using Hooks.

Everything works perfectly on Android but on iOS not even the TestIds work.

This comment by @DoctorJohn perfectly describes my issue:

I actually spent multiple hours investigating this issue last weekend. However, the results are slightly underwhelming. Here is what I did:

### 1. Validate ads are not loading in our example app

I started by confirming that rewarded ads don't load in my setup with the [react-native-google-mobile-ads example app](https://github.com/invertase/react-native-google-mobile-ads/tree/main/RNGoogleMobileAdsExample). They don't. The following is logged in the console:

```
LOG  ios rewarded interstitial ad event: error
LOG  ios rewarded interstitial error: [googleMobileAds/no-fill] Request Error: No ad to show.
LOG  ios rewarded ad event: error
LOG  ios rewarded error: [googleMobileAds/no-fill] Request Error: No ad to show.
```

Here is what the ad inspector had to say:

<div style='flex-flow: row'>
<img src="https://user-images.githubusercontent.com/14076775/189549432-9c000699-8c23-40c5-b1a0-6441341fbcec.png">
<img src="https://user-images.githubusercontent.com/14076775/189549634-c4781dbb-88f9-4bc0-85b5-7066e5a9af97.png">
</div>

When I turn on single ad source test:

![image](https://user-images.githubusercontent.com/14076775/189552114-620f932d-8e3a-4c4a-aa21-19112554f69f.png)

### 2. Compared our code to the official examples

I continued comparing our code to the [official documentation](https://developers.google.com/admob/ios/rewarded) and the [official example app](https://github.com/googleads/googleads-mobile-ios-examples/tree/main/Swift/admob/RewardedVideoExample). Luckily/Unfortunately I didn't really (check "Other findings" further down) find any issues here.

### 3. Checked whether ads load in the official example app

Checked whether rewarded ads load in the [official example app](https://github.com/googleads/googleads-mobile-ios-examples/tree/main/Swift/admob/RewardedVideoExample). They don't. Interesting. All other ad types work as expected.

The xcode logs report:

```
Rewarded ad failed to load with error: Request Error: No ad to show
```

The logs also warn:

```
To get test ads on this device, set:
Objective-C
    GADMobileAds.sharedInstance.requestConfiguration.testDeviceIdentifiers = @[ GADSimulatorID ];
Swift
    GADMobileAds.sharedInstance().requestConfiguration.testDeviceIdentifiers = [ GADSimulatorID ]
```

So I added the suggested code. The warning went away, still no ads to show though.

### 4. Checked whether ads load in the official flutter example app

Checked whether our flutter friends get any special treatment by running the [official flutter example app](https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/example). Rewarded ads don't load there either. All other ad types work as expected.

That's what their console logs:

```
flutter: RewardedAd failed to load: LoadAdError(code: 1, domain: com.google.admob, message: Request Error: No ad to show., responseInfo: ResponseInfo(responseId: NlceY9CaIYCg7_UPzN-CkAM, mediationAdapterClassName: null, adapterResponses: [AdapterResponseInfo(adapterClassName: GADMAdapterGoogleAdMobAds, latencyMillis: 2980), description: {
    AdUnitMapping =     {
        "campaign_id" = 1057492276;
        pubid = "ca-app-pub-3940256099942544/1712485313/cak=no_cache&cadc=7d&caqid=NlceY9DHIKmy9u8Pt6GFmAg";
    };
    Error = "Error Domain=com.google.admob Code=5 \"Request Error: The Google ad request was unable to be fulfilled before a timeout occurred.\" UserInfo={NSLocalizedDescription=Request Error: The Google ad request was unable to be fulfilled before a timeout occurred.}";
    Latency = "2.98";
    Network = GADMAdapterGoogleAdMobAds;
}, adUnitMapping: {pubid: ca-app-pub-3940256099942544/1712485313/cak=no_cache&cadc=7d&caqid=NlceY9DHIKmy9u8Pt6GFmAg, campaign_id: 1057492276}, adError: AdE<…>
```

## My setup (using OSX-KVM):

```
System:
    OS: macOS 12.5.1
    CPU: (8) x64 Intel Core 2 Duo P9xxx (Penryn Class Core 2)
    Memory: 44.92 MB / 4.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.8.0 - /var/folders/_5/z62cpbj13md90cw362b32sfc0000gn/T/yarn--1662931012332-0.5539745813245331/node
    Yarn: 1.22.19 - /var/folders/_5/z62cpbj13md90cw362b32sfc0000gn/T/yarn--1662931012332-0.5539745813245331/yarn
    npm: 8.18.0 - /usr/local/bin/npm
    Watchman: 2022.08.29.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/developer/.gem/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.1 => 0.68.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Next steps

We should check whether rewarded ads load with real ad ids in an app that already has been released to the Apple App Store and which is linked to admob. (Currently can't do that myself, maybe in a month or so).

I also tried swapping in my iOS admob app and ad ids. Got the same results. However, my app and ad ids were freshly created the day I did the testing. Should try again, now that they have been around a little longer.

I'm curious whether this issue has something to do with my and Mikes setup (OSX-KVM).

## Other findings

The [admob iOS quick start guide](https://developers.google.com/admob/ios/quick-start) suggests adding a `SKAdNetworkItems` array to the `info.plist` file. As far as I can tell we don't do that in our example app. However, my test results didn't change after adding said array to the example app.

Our App Transport Security setup also slighty differs from [the official docs](https://developers.google.com/admob/ios/app-transport-security). Again, adjusting these in our example apps `info.plist` didn't make any difference.

The [googleads-mobile-flutter package](https://github.com/googleads/googleads-mobile-flutter) has more detailed errors about ad loading errors in the console. They do that by adding ad response infos to their errors. We don't really need to add that to our implementation since I noticed the ad inspector gives us about as much information. Still here is their implementation in case someone is curious and wants to add something similar to assist further investigations of this or similar issues:

https://github.com/googleads/googleads-mobile-flutter/blob/bdcc9df9e69c87fb22ee50998121ef48811cf3c8/packages/google_mobile_ads/ios/Classes/FLTAdInstanceManager_Internal.m#L92-L99

https://github.com/googleads/googleads-mobile-flutter/blob/bdcc9df9e69c87fb22ee50998121ef48811cf3c8/packages/google_mobile_ads/ios/Classes/FLTAd_Internal.m#L277-L294

https://github.com/googleads/googleads-mobile-flutter/blob/bdcc9df9e69c87fb22ee50998121ef48811cf3c8/packages/google_mobile_ads/ios/Classes/FLTAd_Internal.m#L230-L249

_Originally posted by @DoctorJohn in https://github.com/invertase/react-native-google-mobile-ads/issues/109#issuecomment-1243054778_

**Comment by little-steps** [comment]
can u please share code of android 
my android ads are not working rewardads 
always show an error 
RewardedAd.show() The requested RewardedAd has not loaded and could not be shown.[🐛] Bug Report Title - CHANGE ME #291

**Comment by baochungit** [comment]
For me, on Android, ads show up on some devices, some not. on iOS, ads are not showing up at all. Looking at the `Ads activity performance` section on Admob dashboard, I can see there are requests but somehow the ads not showing. The LOADED event not fired?
