### ISSUE TITLE
[Meta Audience Network] Advertising Tracking Enabled

### ISSUE THREAD

**Issue by robinshin** [invertase/react-native-google-mobile-ads#302]
### Documentation Feedback

Hello,

I did set up ATT for iOS on my Google AdMob account and I'm starting to use Audience Network Mediation.

In the Meta documentation, it is required to use Advertising Tracking Enabled for iOS (https://developers.facebook.com/docs/audience-network/setting-up/platform-setup/ios/advertising-tracking-enabled).

Is this information automatically set up and sent with Google AdMob's ATT?

**Comment by ajouve** [comment]
@robinshin did youu revolved it ?

I have the same issue my Meta ads are displayed on android but on iOS meta ads are not showing, seems that the Advertising tracking is not activated https://developers.google.com/admob/ios/mediation/meta#advertising_tracking_enabled

Not un expert in react but I will try to exec

```swift
FBAdSettings.setAdvertiserTrackingEnabled(true)
```

From my app it should work
