### ISSUE TITLE
[Help wanted!] Inquiry - How to add mediation networks which requires external repositories for SDKs.

### ISSUE THREAD

**Issue by ytakzk** [invertase/react-native-google-mobile-ads#318]
### Documentation Feedback

This is not a bug report nor documentation feedback, but I would love to know how we can add mediation networks which requires external repositories for SDKs.

For example, [ironsource](https://developers.google.com/admob/android/mediation/ironsource#android_studio_integration_recommended) expects an external source to install SDK, but how is it possible to achieve this with your library?
I've tried to add the following url to fetch the SDK, but it looks to be ignored when building.

```
repositories {
    google()
    mavenCentral()
    // this is added, but this source is ignored for some reason..
    maven {
        url 'https://android-sdk.is.com/'
    }
}
```

Does anyone here know how we can add this kind of mediation netoworks?

Thank you in advance!

**Comment by Robiullah2244** [comment]
Hi @ytakzk, Did you able to add mediation? I need help.
