### ISSUE TITLE
[📚] Preload component ad

### ISSUE THREAD

**Issue by ricardodolnl** [invertase/react-native-google-mobile-ads#324]
### Documentation Feedback

I couldn't find any documentation about preloading (component) ads. The thing I'm looking for is that I can preload the ad so that when the user ends up on the screen with the ad, the ad will already be loaded and visible.
At this moment when the user ends up on the screen with the ad, the ad still needs to be loaded. It takes, also depending on the internet speed, a lot of time to load. So those seconds loading are a sort of wasted time not showing any ads.

**Comment by dylancom** [comment]
"Preloading banners, on the other hand, is a violation of AdMob policy.  Every time your app requests a banner, it's expected to display that banner to the user immediately on receiving it. Otherwise, advertisers can be charged for ads that are never shown." - Mobile Ads SDK Team

**Comment by sontruongna** [comment]
Mobile Ads SDK Team confirmed that banners can be pre-loaded
[](https://groups.google.com/g/google-admob-ads-sdk/c/BuczXZG9AeU)
It would be nice to include this feature in this library

**Comment by dylancom** [comment]
@sontruongna It would be nice if you submit a PR for this feature.
