### ISSUE TITLE
[📚] Documentation Issue Title - CHANGE ME 

### ISSUE THREAD

**Issue by zoobibackups** [invertase/react-native-google-mobile-ads#326]
### Documentation Feedback

The Documentation is not very clear. Not enough documentation on event listener and hooks. no clean code or some other thing. I have done some work and want to share that. how can I add that code to the documentation.

**Comment by dylancom** [comment]
Well make a PR to our docs then? https://github.com/invertase/react-native-google-mobile-ads/tree/main/docs
