### ISSUE TITLE
How to show/hide View BannerAd automatically?

### ISSUE THREAD

**Issue by chungtv1doi** [invertase/react-native-google-mobile-ads#336]
### Documentation Feedback

I set up the View for the BannerAd. 
If User turn off the internet. Banner could not be loaded. The View could be hidden temporally.
If User turn on the internet. Banner could be loaded successfully. The View will be shown.
How to do that?

**Comment by mikehardy** [comment]
You may observe the loaded status on a banner if I understand correctly, so it is possible to know whether a banner is loaded or not. Attempting to load the banner should be happening already in some useEffect where you can setState or similar?

Then using standard react-native view properties you can make the view's display depend on some state property that you alter based on load status

This is not confined to this repository I think, it is a two-part question if you break it down:

1- how do you make a view alter it's display behavior based on some state? This is a standard react-native question, not this repo's responsibility / not actionable here --> closable issue
2- can you change the application's state based on banner load status? Certainly. When attempting to load the banner, if it doesn't load, set state accordingly --> solution provided I think?
