### ISSUE TITLE
[🐛] GAMBannerAd loaded visible on App screen but mraid.isViewable() returning false

### ISSUE THREAD

**Issue by amolrajoba** [invertase/react-native-google-mobile-ads#339]
### What happened?

I am using this plugin to show Google Ad Manager Banner ad. 

```
return (        
<SafeAreaView>
  <ScrollView >
    <View >                
      <GAMBannerAd 
        unitId={TEST_AD_BANNER}
        sizes={[BannerAdSize.MEDIUM_RECTANGLE]}
        onAdLoaded={() => {
            console.log('Android GAMBannerAd  -> loaded');
          }}
          onAdFailedToLoad={(error) => {
            console.error('Android GAMBannerAd  failed to load: ', error);
          }}
        />
    </View>
  </ScrollView>
</SafeAreaView>
)
```
In react-native app, GAMBannerAd loaded, onAdLoaded callback called, GAMBannerAd visible on screen but the mraid method mraid.isViewable() returning value as 'false' in banner html.  Even MRAID 3 exposureChange event is also not working.
Also noticed that if app goes in background due to a call or due to switching different app and when user comes back to this app the mraid method mraid.isViewable() returning value as 'true'. Same experience when user scrolls the app screen down & up again method mraid.isViewable() returning value as 'true'.

This issue i am not facing in Native Android apps or Native iOS apps when GAM Banner ad is implemented. I have other Native Android/iOS apps where same version Google Mobiles Ads sdk is implemented mraid.isViewable() returning value as 'true' without any user interaction with App.

Please check and suggest solution or fix the issue.

### Platforms

Android, but have not tested behavior on iOS

### React Native Info

```Shell
npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 57.16 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.6.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.4.0 - /opt/homebrew/bin/npm
    Watchman: 2023.01.30.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK: Not Found
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.2 => 0.71.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Are your using Typescript?

- [ ] My project is using Typescript

### package.json

```JSON
{
  "name": "consumerapp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "react": "18.2.0",
    "react-native": "0.71.2",
    "react-native-ad-manager": "^2.0.4",
    "react-native-google-mobile-ads": "^9.1.1"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native-community/eslint-config": "^3.2.0",
    "@tsconfig/react-native": "^2.0.2",
    "@types/jest": "^29.2.1",
    "@types/react": "^18.0.24",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.2.1",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.73.7",
    "prettier": "^2.4.1",
    "react-test-renderer": "18.2.0",
    "typescript": "4.8.4"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

### app.json

```JSON
{
  "name":  "com.consumerapp",
  "displayName": "com.consumerapp",
  "react-native-google-mobile-ads": {
    "android_app_id": "ca-app-pub-3940256099942544~3347511713",
    "ios_app_id": "ca-app-pub-3940256099942544~1458002511"
  }
}
```

**Comment by dylancom** [comment]
Please submit a PR and fix the issue.

**Comment by amolrajoba** [comment]
@dylancom sorry but i can't fix this as i don't have knowledge of react-native and its activity lifecycle internal details. The issue is impacting banner viewability & billable impression metric/statistic in Google Ad Manager. It will be great help to me & the community if contributors look into this issue/case.

**Comment by dylancom** [comment]
@amolrajoba I think you'd be surprised what you can fix if you take a look at the ios / android folders and see the native code.

**Comment by dylancom** [comment]
Oke so worth investigating why https://github.com/invertase/react-native-google-mobile-ads/blob/main/android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsBannerAdViewManager.java#L88 fails...

**Comment by amolrajoba** [comment]
any update on "recordManualImpression" failing for GAMBannerAd?

**Comment by amolrajoba** [comment]
@mikehardy @dylancom can you please help here? i tried to figure out how to fix but not able to.

**Comment by mikehardy** [comment]
@amolrajoba no sorry, this is not a use case of mine. I'm open to PRs to fix it and can help merge+release them but can't prioritize it

**Comment by aidan-24com** [comment]
@amolrajoba 

the issue is due to the JS sending through a string `"recordManualImpression"`, where the Android Java code is expecting an Integer (`1`). iOS doesn't appear to use the commandId, so theoretically you should be able to change the commandId in JS to a number `1` and submit a PR…

![image](https://user-images.githubusercontent.com/78929158/231127676-5b465233-dc19-4b12-9ba9-6261ef5f0a3a.png)

**Comment by amolrajoba** [comment]
This issue still exists. GAM Banner viewable impression counting is still not happening in Android till user does scroll action on the app UI. It also impacts mraid js object and mraid.isViewable() in webview where Banner is loaded.
