### ISSUE TITLE
[🐛] Require cycle in the lib

### ISSUE THREAD

**Issue by birdofpreyru** [invertase/react-native-google-mobile-ads#34]
I just tried to migrate existing project from `@react-native-firebase/admob@11.5.0` to `@invertase/react-native-google-ads@2.0.0`. Testing it first on Android in dev mode, it seems to fail right away with `admob()` call returning `undefined`. RN logs warn about require cycles, ~and that would be my first guess for the problem~:
![image](https://user-images.githubusercontent.com/20144632/145696434-c1bd930f-0308-4e95-a1d5-b5804714155a.png)
I'll probably debug further and submit a PR later.

P.S.: Glad to see you finally found time to try to make this lib happen, but imho you should be a bit more modest with bumping the major release version on each change. It would make more sense to keep it 0.x.y until it is really tested and confirmed to work in the field.

P.S.S.: Actually, I figured out that in v2.0.0 the default export is just `googleMobileAds` itself, while according to docs and latest code the function `() => googleModileAds` is exported.

**Comment by DoctorJohn** [comment]
Try `admob.setRequestConfiguration(...)` instead of `admob().setRequestConfiguration(...)`. I had this issue myself experimenting the current version :)

**Comment by birdofpreyru** [comment]
Thanks @DoctorJohn , yeah, also noticed it right after creating the bug ticket. Anyway, require cycles should be eliminated, even if not causing particular problems now.

**Comment by mikehardy** [comment]
All credit to @dylancom for getting it out the door. I won't release 0.x software, that's a semver fail in my opinion. And I will bump major versions any time I hit the release button and it might cause a previously running build to fail. Ask yourself, what does it matter how big a version number is? Quick answer: it does not, the only thing that matters is the signal contained in the number difference. There is no concept of "modesty" in versioning for me, that's a moral concept that doesn't apply to numbers. And so we go...

Sorry it's not working out of the box though - still some growing pains here. Thanks a bunch for joining in with testing.

**Comment by mikehardy** [comment]
Actually - I think I just released a version that fixes the admob vs admob() fix - check changelog

**Comment by mikehardy** [comment]
Oh darn - I was waiting for CI to finish and was distracted by children and dinner etc. Hadn't hit the publish button yet. v2.0.1 is going out this moment with the fix that makes the old API work (`admob()`) - but again all credit to @dylancom - he's fixing the lib here at a furious pace, and it's really appreciated

**Comment by birdofpreyru** [comment]
I don't know... most projects I saw bump major version only on total API overhaul, introducing landslide breaking changes; and if they think something may break / small breaking changes - they bump minor version, and if some small fixes not requireing any changes in the user's code - then patch version. ¯\_(ツ)_/¯

**Comment by mikehardy** [comment]
Nope, semantic versioning means one thing and one thing very specifically about the major version changing: it's a breaking change. Anything that breaks running software is a breaking change. It's a really simple definition, and it's fully automated here in our changelog generation and releasing, I literally never touch the versions, I just note what kind of change it is - https://github.com/semantic-release/ - it's really liberating as a philosophy

**Comment by zoom2009** [comment]
Same here in clean project

```javascript
import React, { useEffect } from 'react'
import { View } from 'react-native'
import admob, { MaxAdContentRating } from '@invertase/react-native-google-ads'

const App = () => {
  useEffect(() => {

  }, [])

  return (
    <View style={{ flex: 1 }}>
    </View>
  )
}

export default App

```

<img src="https://user-images.githubusercontent.com/33366155/145697488-3d959cb4-186c-4ef2-b66f-a18f3f875a39.png" width="200px" />

**Comment by mikehardy** [comment]
Yep. Worth noting, require cycles are a warning but may be safely ignored *at the moment*.
They should not be causing any functionality issues that we are aware of.
Obviously we want to fix them, but at the moment getting the library running, on current SDKs, using the old APIs (where still possible assuming current SDKs support them) is the highest priority

That said, *any* PRs that address the require cycles will be appreciated :pray:

**Comment by Darkensses** [comment]
Hey @mikehardy I'm seeing this issue again in 6.2.5 
![image](https://user-images.githubusercontent.com/23271049/171066692-3d71efc1-1f52-4160-95f2-e9833bf9b558.png)

**Comment by mikehardy** [comment]
Well, darn. Thanks for pointing it out @Darkensses - I'll reopen for further triage

**Comment by vladimirevstratov** [comment]
Stucked with this cycle in react-native-google-mobile-ads v8.2.1

**Comment by mikehardy** [comment]
Yes, unless you see some other progress, this needs a PR to fix. We'll happily merge and release any reasonable PRs that do so :pray:
