### ISSUE TITLE
Prebuild for EXPO doesn't work [📚] Documentation Issue Title - CHANGE ME 

### ISSUE THREAD

**Issue by audrew** [invertase/react-native-google-mobile-ads#340]
### Documentation Feedback

It says that: # For expo users not using EAS npx expo prebuild. But in my case prebuild does nothing and I get Invariant violation errors for RNGoogleMobileAdsBannerView was not found in the UIManager . If there is any specifications of how to fix it?

**Comment by dpeace8** [comment]
I'm also not using EAS. I followed the instructions from the docs and I got the same error.

**Comment by Nikita-Shuminskiy** [comment]
+

**Comment by cobrakai-lab** [comment]
same

**Comment by QuyetAQ** [comment]
same error.
