### ISSUE TITLE
Feature request: please add the `OnPaidEventListener`

### ISSUE THREAD

**Issue by OmarThinks** [invertase/react-native-google-mobile-ads#343]
## Feature Request:

Please add the `OnPaidEventListener`  
https://developers.google.com/android/reference/com/google/android/gms/ads/OnPaidEventListener

Thank you so much!  
:) :) :)

### Platforms

Android, but have not tested behavior on iOS

### React Native Info

```Shell
-
```

### Are your using Typescript?

- [ ] My project is using Typescript

### package.json

```JSON
-
```

### app.json

```JSON
-
```

### ios/Podfile

```Ruby
-
```

### android/build.gradle

```Groovy
-
```

### android/app/build.gradle

```Groovy
-
```

### android/settings.gradle

```Groovy
-
```

### AndroidManifest.xml

```XML
-
```

**Comment by OmarThinks** [comment]
I want to send the value I receive from the paid ad to firebase and google analytics, to set it as a conversion.  
But I need this event listener.  
I can only find five listeners in this package:  
- onAdLoaded
- onAdFailedToLoad
- onAdOpened
- onAdClosed
- onAppEvent

And I can not find a way to use any of these events to send ad-paid value to firebase, to set it as a conversion, and enable ROAS in google ads.  




Thank you so much for your hard work.
😁

**Comment by OmarThinks** [comment]
I also hope that you find this link also helpful:  https://developers.google.com/admob/android/impression-level-ad-revenue

😁

**Comment by tmagnien** [comment]
Hi. My company is facing the same issue. Is there a way to have it done by sonsoring the development?

**Comment by OmarThinks** [comment]
@tmagnien 
If they don't respond.  
I am afraid that plan B might be Native Modules.
https://reactnative.dev/docs/native-modules-intro
It's kinda hard, I know.
😅

**Comment by frederiko-famobi** [comment]
Hey guys, I wanted to update you that this feature is being implemented. Please check: 
https://github.com/invertase/react-native-google-mobile-ads/pull/477#issue-1980224617

Best regards

**Comment by OmarThinks** [comment]
@frederiko-famobi 
Thanks a lot for telling us!
😁

**Comment by tmagnien** [comment]
That's great news!

**Comment by OmarThinks** [comment]
@mikehardy 
Thanks a lot!

**Comment by mikehardy** [comment]
My part was easy! I get credit for the releases since I set up the automated publishing but @birdofpreyru deserves all the credit here for sure. Well done work on that PR

**Comment by OmarThinks** [comment]
Thanks you guys!
@mikehardy @dylancom @birdofpreyru 
🚀🎉

**Comment by birdofpreyru** [comment]
The credit should go to @frederiko-famobi and his company, for they asked and funded me to implement this feature :smiley:

**Comment by mikehardy** [comment]
Indeed, @frederiko-famobi I will extend some sincere thanks then, funding open source software is rare than it should be and I celebrate it every time. Cheers
