### ISSUE TITLE
[📚] AdMob banner policies

### ISSUE THREAD

**Issue by VictorioMolina** [invertase/react-native-google-mobile-ads#346]
### Documentation Feedback

I think it could be good to add examples of invalid implementations (against Google policies) of the different types of ads.

For example, I have some doubts in the following scenarios with Banner Ads:

1. Is it valid to render banners inside FlatLists?

https://support.google.com/admob/thread/64380765/is-it-allowed-to-put-banners-ads-in-a-scrollable-news-feed?hl=en

3. As the users scrolls to see more content, isn’t this situation violating Google policies (increasing chances of accidental clicks)?

4. If it is valid, which frequency should we use to avoid admob account invalidation?

5. Is it recommended or legal to apply styles to banner containers? For example, wrapping the Banner inside a wrapper component which renders a text indicating the component is an Ad.

**Comment by dylancom** [comment]
AdMob has plenty of docs and resources available on this topic (and forums with thousands of questions) so I'd rather direct the users to those (that stay updated) than that this repo becomes a place where we help everyone out with their specific implementation.
It might be good to direct users to those resources available though, such as: https://support.google.com/admob/answer/6275335
https://www.youtube.com/@AdMob
