### ISSUE TITLE
Storing App Ids in gradle properties to avoid uploading to Github.

### ISSUE THREAD

**Issue by cw-sanjeev** [invertase/react-native-google-mobile-ads#351]
### Documentation Feedback

I think it would be a strong measure if we are able to add ad ids from admob during build process or during intialization instead of declaring the id in app.json.

It's good practice to have keys/ids in encrypted backend server/gragle properties file which we tend to not push in version control and read during app build process

Is there a way we can avoid this?

**Comment by mikehardy** [comment]
Not currently. You could construct the app.json dynamically at build time, using inputs from some other system. It's just a text file, and if the one you had in version control in your project had variables-for-future-interpolation vs hard coded IDs, seems it would work?
