### ISSUE TITLE
Banner  ads design on  landscape mode

### ISSUE THREAD

**Issue by Salmankhan033** [invertase/react-native-google-mobile-ads#364]
### Documentation Feedback

I set banner ads on the main view 
It looks some time good on the simulator(testing ads) but when I publish the app then it shows to the right side in portrait mode(large size), and on another screen landscape and in landscape mode it shows small in the testing and also in real ads.
also, the interstitial ads look good in testing mode but in real ads look big and can't close/exit it.
in some devices, it shows a fix in the screen but in some devices, it takes more space and does not close it.
I am using the 9.1.1 version.

How to set the banner ads full in landscape and the  InterstitialAd fix in all screen sizes?
banner and interstitial take extra size more than the  display size

<table>
 <tr>
  <td>Banner Size</td>
   <td>Banner Size in landscape</td>
   <td>Instertisal Size</td>
 </tr>
 <tr>
<td><img src="https://user-images.githubusercontent.com/58082294/231261054-1c31fd2d-6230-4e36-b3b2-267395cdd9d1.png" alt="Drawing"  width="150" height="300"/> </td>
<td> <img src="https://user-images.githubusercontent.com/58082294/231261154-ba9969e7-f565-4d53-ba9d-3a2de1e4d0be.png" alt="Drawing"  width="150" height="300"/>  </td>
<td><img src="https://user-images.githubusercontent.com/58082294/231262971-992f96a0-8dc7-4eb0-8900-9565863044e8.png" alt="Drawing"  width="150" height="300"/></td>
</tr></table>

**Banner ads code:**
  {showAds && (
        <BannerAd
          unitId={adUnitId}
          size={BannerAdSize.FULL_BANNER}
          requestOptions={{
            requestNonPersonalizedAdsOnly: true,
          }}
        />
      )}

**Comment by dylancom** [comment]
If you load an ad in landscape mode and change orientation you have to load a new ad for that orientation.

**Comment by Salmankhan033** [comment]
> If you load an ad in landscape mode and change orientation you have to load a new ad for that orientation.

The second screen already in landscape mode then how to load for it.
I set it in navigations when user goes to second screen then it will be landscape mode

**Comment by dylancom** [comment]
I see you are using the FULL_BANNER fixed size while you should be using an adaptive banner instead. Please see the AdMob docs to find out which ad types you need for your use case.
