### ISSUE TITLE
[🐛] Missing argument for parameter 'orientation' in call

### ISSUE THREAD

**Issue by SzAkos** [invertase/react-native-google-mobile-ads#366]
### What happened?

I updated the version to the latest and this error came up:
Missing argument for parameter 'orientation' in call

### Platforms

Only on iOS

### React Native Info

```Shell
"react-native": "0.68.2"
```

### Are your using Typescript?

- [ ] My project is using Typescript

### package.json

```JSON
-
```

### app.json

```JSON
-
```

**Comment by dylancom** [comment]
Please update to the latest version and provide some info / show a code example. What kind of ads do you display?

**Comment by dorthwein** [comment]
I'm running into this with v11.0.0
