### ISSUE TITLE
Not working on web version

### ISSUE THREAD

**Issue by kidar2** [invertase/react-native-google-mobile-ads#372]
### What happened?

When i try to run web version i get the errors:

ERROR in ./node_modules/react-native-google-mobile-ads/lib/module/common/Base64.js 20:0-77
Module not found: Error: Can't resolve 'react-native/Libraries/Utilities/binaryToBase64' 

ERROR in ./node_modules/react-native-google-mobile-ads/lib/module/internal/SharedEventEmitter.js 19:0-73
Module not found: Error: Can't resolve 'react-native/Libraries/vendor/emitter/EventEmitter' 

### Platforms

Android, but have not tested behavior on iOS

### React Native Info

```Shell
"react": "18.1.0"
"react-native": "0.70.2"
```

### Are your using Typescript?

- [x] My project is using Typescript

### package.json

```JSON
-
```

### app.json

```JSON
-
```

### ios/Podfile

```Ruby
-
```

### android/build.gradle

```Groovy
-
```

### android/app/build.gradle

```Groovy
-
```

### android/settings.gradle

```Groovy
-
```

### AndroidManifest.xml

```XML
-
```

**Comment by bibhuti9** [comment]
is it working in release mode in android?

**Comment by kidar2** [comment]
I didn't check. Does it make sence? Is your library support web version ?

**Comment by bibhuti990** [comment]
I'm facing the same problem in android

**Comment by bibhuti9** [comment]
I'm facing the same problem in android
