### ISSUE TITLE
[📚] Documentation Issue Title - Reusing existing instance of the InterstitialAd

### ISSUE THREAD

**Issue by linkeddg** [invertase/react-native-google-mobile-ads#379]
### Documentation Feedback

In the documentation for Interstitial Ads the last paragraph says: "If needed, you can reuse the existing instance of the InterstitialAd class to load more adverts and show them when required." But looking at the code, if you attempt to just call .load() on the interstitial object again after the initial load it blocks goes into a:

// Prevent multiple load calls
    if (this._loaded || this._isLoadCalled) {
      return;
    }
    
None of the other methods besides the _handleAdEvent set the _loaded or isLoadCalled to false:

if (type === AdEventType.CLOSED) {
      this._loaded = false;
      this._isLoadCalled = false;
    }

    if (type === AdEventType.ERROR) {
      this._loaded = false;
      this._isLoadCalled = false;
    }
    
I'm not sure how I'm supposed to load a new ad after a specific amount of time has passed, or when users come back to a screen except by calling createForAdRequest again. :fire:

**Comment by johndev247** [comment]
@linkeddg  I'm unable to use this library with EAS build. please are you also using Expo?

**Comment by codergautam** [comment]
Same issue! My interstitials not loading on prod build in EAS. If any help much appreciated. It works fine in dev build.
