### ISSUE TITLE
[🐛] Bug Report Title - EAS Build Fail on Android but works on IOS

### ISSUE THREAD

**Issue by johndev247** [invertase/react-native-google-mobile-ads#380]
### What happened?

I'm building my App using  "npx eas-cli build --profile development" but it keeps on failing at gradle with the error below, It builds successfully on IOS without any Issue. At first I thought the issue was with my project but when I remove "react-native-google-mobile-ads" it builds successfully without any issue. so it looks like "react-native-google-mobile-ads" is causing the failure. Please am I missing something or Its a general issue? 

ERROR: 
[stderr] 
FAILURE: Build completed with 2 failures.
[stderr] 
1: Task failed with an exception.
[stderr] 
-----------
[stderr] 
* What went wrong:
[stderr] 
Execution failed for task ':app:processDebugMainManifest'.
[stderr] 
> Manifest merger failed with multiple errors, see logs
[stderr] 
* Try:
[stderr] 
> Run with --stacktrace option to get the stack trace.
[stderr] 
> Run with --info or --debug option to get more log output.
[stderr] 
> Run with --scan to get full insights.
[stderr] 
==============================================================================
[stderr] 
2: Task failed with an exception.
[stderr] 
-----------
[stderr] 
* What went wrong:
[stderr] 
java.lang.StackOverflowError (no error message)
[stderr] 
* Try:
[stderr] 
> Run with --stacktrace option to get the stack trace.
[stderr] 
> Run with --info or --debug option to get more log output.
[stderr] 
> Run with --scan to get full insights.
[stderr] 
==============================================================================
[stderr] 
* Get more help at https://help.gradle.org
[stderr] 
BUILD FAILED in 4m 17s

### Platforms

Android, but have not tested behavior on iOS

### React Native Info

```Shell
"react-native": "0.71.7"
```

### Are your using Typescript?

- [ ] My project is using Typescript

### package.json

```JSON
"expo": "48.0.0",
"react-native": "0.71.7",
"react-native-google-mobile-ads": "^10.3.2",
```

### app.json

```JSON
{ 
  "expo":{
  },
  "react-native-google-mobile-ads": {
    "android_app_id": "My admod android id",
    "ios_app_id": "my admob ios id"
  }
}
```

**Comment by AymanAbdElhamiid** [comment]
hello , did u get anywhere ?
