### ISSUE TITLE
[🐛] [Error: [googleMobileAds/error-code-internal-error] Something happened internally; for instance, an invalid response was received from the ad server.]

### ISSUE THREAD

**Issue by sureshem30** [invertase/react-native-google-mobile-ads#398]
### What happened?

I am getting this error  **[Error: [googleMobileAds/error-code-internal-error] Something happened internally; for instance, an invalid response was received from the ad server.]** while adding ads to my app. Even the Testids.Banner or other testads are not working. I have added payment method as well. Can you tell me what's the issue. 

### Platforms

Android, but have not tested behavior on iOS

### React Native Info

```Shell
System:
  OS: Windows 10 10.0.19044
  CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
  Memory: 1.16 GB / 7.94 GB
Binaries:
  Node:
    version: 18.16.0
    path: D:\nodejs\node.EXE
  Yarn: Not Found
  npm:
    version: 9.5.1
    path: D:\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK:
    API Levels:
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
    Build Tools:
      - 28.0.3
      - 29.0.2
      - 30.0.0
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 33.0.0
    System Images:
      - android-26 | Google Play Intel x86 Atom
      - android-28 | ARM 64 v8a
      - android-30 | Intel x86 Atom_64
      - android-31 | Intel x86 Atom_64
    Android NDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 17.5.33530.505 (Visual Studio Community 2022)
    - 15.9.33529.398 (Visual Studio Community 2017)
Languages:
  Java: 11.0.16
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.0
    wanted: 0.72.0
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Are your using Typescript?

- [ ] My project is using Typescript

### package.json

```JSON
{
  "name": "learnnative",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@notifee/react-native": "^7.7.1",
    "@react-native-async-storage/async-storage": "^1.17.11",
    "@react-native-community/datetimepicker": "^6.7.1",
    "@react-native-firebase/app": "^16.5.1",
    "@react-native-firebase/messaging": "^16.5.1",
    "@react-navigation/bottom-tabs": "^6.5.2",
    "@react-navigation/native": "^6.1.1",
    "@react-navigation/native-stack": "^6.9.7",
    "apisauce": "^2.1.6",
    "moment": "^2.29.4",
    "react": "18.1.0",
    "react-native": "0.70.6",
    "react-native-device-info": "^10.6.0",
    "react-native-document-picker": "^8.1.3",
    "react-native-element-dropdown": "^2.5.1",
    "react-native-gesture-handler": "^2.8.0",
    "react-native-google-mobile-ads": "^11.0.0",
    "react-native-image-picker": "^5.1.0",
    "react-native-otp-verify": "^1.1.4",
    "react-native-paper": "^5.1.0",
    "react-native-permissions": "^3.7.2",
    "react-native-push-notification": "^8.1.1",
    "react-native-responsive-dimensions": "^3.1.1",
    "react-native-safe-area-context": "^4.4.1",
    "react-native-screens": "^3.18.2",
    "react-native-table-component": "^1.2.2",
    "react-native-tts": "^4.1.0",
    "react-native-vector-icons": "^9.2.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "0.72.3",
    "react-test-renderer": "18.1.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

### app.json

```JSON
{
  "name": "learnnative",
  "displayName": "------",
  "react-native-google-mobile-ads": {
    "android_app_id": "ca-app-pub-8930218409532778~2082457332"
  }
}
```

**Comment by mikehardy** [comment]
What do you see in the native logs when this occurs?

**Comment by sureshem30** [comment]
When i console logged the function onAdFailedToLoad it was giving me this error  :- [Error: [googleMobileAds/error-code-internal-error] Something happened internally; for instance, an invalid response was received from the ad server.]

**Comment by mikehardy** [comment]
@sureshem30 "console logged" does not sound like native logs. I mean `adb logcat`. Did you see anything in `adb logcat` while this error happens?

**Comment by sureshem30** [comment]
This is the native log for ad error

06-30 10:28:33.205 12044 19832 E NetworkScheduler.ATC: Called cancelTask for already completed task com.google.android.gms/.measurement.PackageMeasurementTaskService{u=0 tag="Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG" trigger=window{start=0s,end=2s,earliest=-161s,latest=-159s} requirements=[NET_CONNECTED,PREFERRED_CHARGING] attributes=[PERSISTED] scheduled=-161s last_run=-161s exec_window_multiplier=1.0000 jid=N/A status=ACTIVE retries=0 client_lib=GMS_TASK_SCHEDULER-232316000} :1 [CONTEXT service_id=218 ]
06-30 10:28:33.619 12044 23132 E NetworkScheduler.ATC: Called cancelTask for already completed task com.google.android.gms/.measurement.PackageMeasurementTaskService{u=0 tag="Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG" trigger=window{start=0s,end=2s,earliest=-161s,latest=-159s} requirements=[NET_CONNECTED,PREFERRED_CHARGING] attributes=[PERSISTED] scheduled=-161s last_run=-161s exec_window_multiplier=1.0000 jid=N/A status=ACTIVE retries=0 client_lib=GMS_TASK_SCHEDULER-232316000} :1 [CONTEXT service_id=218 ]
06-30 10:28:43.519 12044 23132 E NetworkScheduler.ATC: Called cancelTask for already completed task com.google.android.gms/.measurement.PackageMeasurementTaskService{u=0 tag="Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG" trigger=window{start=0s,end=2s,earliest=-171s,latest=-169s} requirements=[NET_CONNECTED,PREFERRED_CHARGING] attributes=[PERSISTED] scheduled=-171s last_run=-171s exec_window_multiplier=1.0000 jid=N/A status=ACTIVE retries=0 client_lib=GMS_TASK_SCHEDULER-232316000} :1 [CONTEXT service_id=218 ]
06-30 10:28:43.935 12044 19832 E NetworkScheduler.ATC: Called cancelTask for already completed task com.google.android.gms/.measurement.PackageMeasurementTaskService{u=0 tag="Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG" trigger=window{start=0s,end=2s,earliest=-172s,latest=-170s} requirements=[NET_CONNECTED,PREFERRED_CHARGING] attributes=[PERSISTED] scheduled=-172s last_run=-171s exec_window_multiplier=1.0000 jid=N/A status=ACTIVE retries=0 client_lib=GMS_TASK_SCHEDULER-232316000} :1 [CONTEXT service_id=218 ]
06-30 10:28:43.943 12044 25774 E NetworkScheduler.ATC: Called cancelTask for already completed task com.google.android.gms/.measurement.PackageMeasurementTaskService{u=0 tag="Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG" trigger=window{start=0s,end=2s,earliest=-172s,latest=-170s} requirements=[NET_CONNECTED,PREFERRED_CHARGING] attributes=[PERSISTED] scheduled=-172s last_run=-171s exec_window_multiplier=1.0000 jid=N/A status=ACTIVE retries=0 client_lib=GMS_TASK_SCHEDULER-232316000} :1 [CONTEXT service_id=218 ]
06-30 10:28:44.557 12044 19832 E NetworkScheduler.ATC: Called cancelTask for already completed task com.google.android.gms/.measurement.PackageMeasurementTaskService{u=0 tag="Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG" trigger=window{start=0s,end=2s,earliest=-172s,latest=-170s} requirements=[NET_CONNECTED,PREFERRED_CHARGING] attributes=[PERSISTED] scheduled=-172s last_run=-172s exec_window_multiplier=1.0000 jid=N/A status=ACTIVE retries=0 client_lib=GMS_TASK_SCHEDULER-232316000} :1 [CONTEXT service_id=218 ]
06-30 10:29:03.473 12044 23129 E NetworkScheduler.ATC: Called cancelTask for already completed task com.google.android.gms/.measurement.PackageMeasurementTaskService{u=0 tag="Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG" trigger=window{start=0s,end=2s,earliest=-191s,latest=-189s} requirements=[NET_CONNECTED,PREFERRED_CHARGING] attributes=[PERSISTED] scheduled=-191s last_run=-191s exec_window_multiplier=1.0000 jid=N/A status=ACTIVE retries=0 client_lib=GMS_TASK_SCHEDULER-232316000} :1 [CONTEXT service_id=218 ]
06-30 10:29:03.904 12044 19832 E NetworkScheduler.ATC: Called cancelTask for already completed task com.google.android.gms/.measurement.PackageMeasurementTaskService{u=0 tag="Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG" trigger=window{start=0s,end=2s,earliest=-192s,latest=-190s} requirements=[NET_CONNECTED,PREFERRED_CHARGING] attributes=[PERSISTED] scheduled=-192s last_run=-191s exec_window_multiplier=1.0000 jid=N/A status=ACTIVE retries=0 client_lib=GMS_TASK_SCHEDULER-232316000} :1 [CONTEXT service_id=218 ]
06-30 10:29:13.621 12044 23132 E NetworkScheduler.ATC: Called cancelTask for already completed task com.google.android.gms/.measurement.PackageMeasurementTaskService{u=0 tag="Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG" trigger=window{start=0s,end=2s,earliest=-201s,latest=-199s} requirements=[NET_CONNECTED,PREFERRED_CHARGING] attributes=[PERSISTED] scheduled=-201s last_run=-201s exec_window_multiplier=1.0000 jid=N/A status=ACTIVE retries=0 client_lib=GMS_TASK_SCHEDULER-232316000} :1 [CONTEXT service_id=218 ]
06-30 10:29:14.042 12044 23129 E NetworkScheduler.ATC: Called cancelTask for already completed task com.google.android.gms/.measurement.PackageMeasurementTaskService{u=0 tag="Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG" trigger=window{start=0s,end=2s,earliest=-202s,latest=-200s} requirements=[NET_CONNECTED,PREFERRED_CHARGING] attributes=[PERSISTED] scheduled=-202s last_run=-201s exec_window_multiplier=1.0000 jid=N/A status=ACTIVE retries=0 client_lib=GMS_TASK_SCHEDULER-232316000} :1 [CONTEXT service_id=218 ]
06-30 10:29:14.048 12044 23132 E NetworkScheduler.ATC: Called cancelTask for already completed task com.google.android.gms/.measurement.PackageMeasurementTaskService{u=0 tag="Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG" trigger=window{start=0s,end=2s,earliest=-202s,latest=-200s} requirements=[NET_CONNECTED,PREFERRED_CHARGING] attributes=[PERSISTED] scheduled=-202s last_run=-201s exec_window_multiplier=1.0000 jid=N/A status=ACTIVE retries=0 client_lib=GMS_TASK_SCHEDULER-232316000} :1 [CONTEXT service_id=218 ]
06-30 10:29:14.599 12044 19832 E NetworkScheduler.ATC: Called cancelTask for already completed task com.google.android.gms/.measurement.PackageMeasurementTaskService{u=0 tag="Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG" trigger=window{start=0s,end=2s,earliest=-202s,latest=-200s} requirements=[NET_CONNECTED,PREFERRED_CHARGING] attributes=[PERSISTED] scheduled=-202s last_run=-202s exec_window_multiplier=1.0000 jid=N/A status=ACTIVE retries=0 client_lib=GMS_TASK_SCHEDULER-232316000} :1 [CONTEXT service_id=218 ]
06-30 10:29:33.507 12235 19035 E GmsConnectionFactory: UID for network attribution might be misset for tag 805306624 [CONTEXT service_id=39 ]
06-30 10:29:33.507 12235 19035 E GmsConnectionFactory: djjo: FULL
06-30 10:29:33.507 12235 19035 E GmsConnectionFactory:  at d.N(:com.google.android.gms@232316044@23.23.16 (190400-540660214):0)
06-30 10:29:33.507 12235 19035 E GmsConnectionFactory:  at aoen.a(:com.google.android.gms@232316044@23.23.16 (190400-540660214):14)
06-30 10:29:33.507 12235 19035 E GmsConnectionFactory:  at arci.c(:com.google.android.gms@232316044@23.23.16 (190400-540660214):8)
06-30 10:29:33.507 12235 19035 E GmsConnectionFactory:  at arci.b(:com.google.android.gms@232316044@23.23.16 (190400-540660214):0)
06-30 10:29:33.507 12235 19035 E GmsConnectionFactory:  at com.google.android.gms.ads.social.d.d(:com.google.android.gms@232316044@23.23.16 (190400-540660214):5)
06-30 10:29:33.507 12235 19035 E GmsConnectionFactory:  at com.google.android.gms.ads.social.d.c(:com.google.android.gms@232316044@23.23.16 (190400-540660214):5)
06-30 10:29:33.507 12235 19035 E GmsConnectionFactory:  at com.google.android.gms.ads.social.d.a(:com.google.android.gms@232316044@23.23.16 (190400-540660214):8)
06-30 10:29:33.507 12235 19035 E GmsConnectionFactory:  at com.google.android.gms.ads.social.e.c(:com.google.android.gms@232316044@23.23.16 (190400-540660214):1)
06-30 10:29:33.507 12235 19035 E GmsConnectionFactory:  at com.google.android.gms.ads.social.n.call(:com.google.android.gms@232316044@23.23.16 (190400-540660214):9)
06-30 10:29:33.507 12235 19035 E GmsConnectionFactory:  at dnez.a(:com.google.android.gms@232316044@23.23.16 (190400-540660214):0)
06-30 10:29:33.507 12235 19035 E GmsConnectionFactory:  at dndz.run(:com.google.android.gms@232316044@23.23.16 (190400-540660214):3)
06-30 10:29:33.507 12235 19035 E GmsConnectionFactory:  at dnfa.run(:com.google.android.gms@232316044@23.23.16 (190400-540660214):0)
06-30 10:29:33.507 12235 19035 E GmsConnectionFactory:  at acjj.c(:com.google.android.gms@232316044@23.23.16 (190400-540660214):6)
06-30 10:29:33.507 12235 19035 E GmsConnectionFactory:  at acjj.run(:com.google.android.gms@232316044@23.23.16 (190400-540660214):7)
06-30 10:29:33.507 12235 19035 E GmsConnectionFactory:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
06-30 10:29:33.507 12235 19035 E GmsConnectionFactory:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
06-30 10:29:33.507 12235 19035 E GmsConnectionFactory:  at acoq.run(:com.google.android.gms@232316044@23.23.16 (190400-540660214):0)
06-30 10:29:33.507 12235 19035 E GmsConnectionFactory:  at java.lang.Thread.run(Thread.java:1012)
06-30 10:29:33.515 12235 19035 E Ads     : Failed to connect to ********************************************************** No DSID retrieved.
06-30 10:29:33.522 12235 19035 E GmsConnectionFactory: UID for network attribution might be misset for tag 805306624 [CONTEXT service_id=39 ]
06-30 10:29:33.522 12235 19035 E GmsConnectionFactory: djjo: FULL
06-30 10:29:33.522 12235 19035 E GmsConnectionFactory:  at d.N(:com.google.android.gms@232316044@23.23.16 (190400-540660214):0)
06-30 10:29:33.522 12235 19035 E GmsConnectionFactory:  at aoen.a(:com.google.android.gms@232316044@23.23.16 (190400-540660214):14)
06-30 10:29:33.522 12235 19035 E GmsConnectionFactory:  at arci.c(:com.google.android.gms@232316044@23.23.16 (190400-540660214):8)
06-30 10:29:33.522 12235 19035 E GmsConnectionFactory:  at arci.b(:com.google.android.gms@232316044@23.23.16 (190400-540660214):0)
06-30 10:29:33.522 12235 19035 E GmsConnectionFactory:  at com.google.android.gms.ads.social.d.d(:com.google.android.gms@232316044@23.23.16 (190400-540660214):5)
06-30 10:29:33.522 12235 19035 E GmsConnectionFactory:  at com.google.android.gms.ads.social.d.c(:com.google.android.gms@232316044@23.23.16 (190400-540660214):5)
06-30 10:29:33.522 12235 19035 E GmsConnectionFactory:  at com.google.android.gms.ads.social.d.a(:com.google.android.gms@232316044@23.23.16 (190400-540660214):8)
06-30 10:29:33.522 12235 19035 E GmsConnectionFactory:  at com.google.android.gms.ads.social.e.c(:com.google.android.gms@232316044@23.23.16 (190400-540660214):1)
06-30 10:29:33.522 12235 19035 E GmsConnectionFactory:  at com.google.android.gms.ads.social.n.call(:com.google.android.gms@232316044@23.23.16 (190400-540660214):9)
06-30 10:29:33.522 12235 19035 E GmsConnectionFactory:  at dnez.a(:com.google.android.gms@232316044@23.23.16 (190400-540660214):0)
06-30 10:29:33.522 12235 19035 E GmsConnectionFactory:  at dndz.run(:com.google.android.gms@232316044@23.23.16 (190400-540660214):3)
06-30 10:29:33.522 12235 19035 E GmsConnectionFactory:  at dnfa.run(:com.google.android.gms@232316044@23.23.16 (190400-540660214):0)
06-30 10:29:33.522 12235 19035 E GmsConnectionFactory:  at acjj.c(:com.google.android.gms@232316044@23.23.16 (190400-540660214):6)
06-30 10:29:33.522 12235 19035 E GmsConnectionFactory:  at acjj.run(:com.google.android.gms@232316044@23.23.16 (190400-540660214):7)
06-30 10:29:33.522 12235 19035 E GmsConnectionFactory:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
06-30 10:29:33.522 12235 19035 E GmsConnectionFactory:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
06-30 10:29:33.522 12235 19035 E GmsConnectionFactory:  at acoq.run(:com.google.android.gms@232316044@23.23.16 (190400-540660214):0)
06-30 10:29:33.522 12235 19035 E GmsConnectionFactory:  at java.lang.Thread.run(Thread.java:1012)
06-30 10:29:33.526 12235 19035 E Ads     : Failed to connect to ********************************************************** No DSID retrieved.
06-30 10:29:33.531 12235 19035 E GmsConnectionFactory: UID for network attribution might be misset for tag 805306624 [CONTEXT service_id=39 ]
06-30 10:29:33.531 12235 19035 E GmsConnectionFactory: djjo: FULL
06-30 10:29:33.531 12235 19035 E GmsConnectionFactory:  at d.N(:com.google.android.gms@232316044@23.23.16 (190400-540660214):0)
06-30 10:29:33.531 12235 19035 E GmsConnectionFactory:  at aoen.a(:com.google.android.gms@232316044@23.23.16 (190400-540660214):14)
06-30 10:29:33.531 12235 19035 E GmsConnectionFactory:  at arci.c(:com.google.android.gms@232316044@23.23.16 (190400-540660214):8)
06-30 10:29:33.531 12235 19035 E GmsConnectionFactory:  at arci.b(:com.google.android.gms@232316044@23.23.16 (190400-540660214):0)
06-30 10:29:33.531 12235 19035 E GmsConnectionFactory:  at com.google.android.gms.ads.social.d.d(:com.google.android.gms@232316044@23.23.16 (190400-540660214):5)
06-30 10:29:33.531 12235 19035 E GmsConnectionFactory:  at com.google.android.gms.ads.social.d.c(:com.google.android.gms@232316044@23.23.16 (190400-540660214):5)
06-30 10:29:33.531 12235 19035 E GmsConnectionFactory:  at com.google.android.gms.ads.social.d.a(:com.google.android.gms@232316044@23.23.16 (190400-540660214):8)
06-30 10:29:33.531 12235 19035 E GmsConnectionFactory:  at com.google.android.gms.ads.social.e.c(:com.google.android.gms@232316044@23.23.16 (190400-540660214):1)
06-30 10:29:33.531 12235 19035 E GmsConnectionFactory:  at com.google.android.gms.ads.social.n.call(:com.google.android.gms@232316044@23.23.16 (190400-540660214):9)
06-30 10:29:33.531 12235 19035 E GmsConnectionFactory:  at dnez.a(:com.google.android.gms@232316044@23.23.16 (190400-540660214):0)
06-30 10:29:33.531 12235 19035 E GmsConnectionFactory:  at dndz.run(:com.google.android.gms@232316044@23.23.16 (190400-540660214):3)
06-30 10:29:33.531 12235 19035 E GmsConnectionFactory:  at dnfa.run(:com.google.android.gms@232316044@23.23.16 (190400-540660214):0)
06-30 10:29:33.531 12235 19035 E GmsConnectionFactory:  at acjj.c(:com.google.android.gms@232316044@23.23.16 (190400-540660214):6)
06-30 10:29:33.531 12235 19035 E GmsConnectionFactory:  at acjj.run(:com.google.android.gms@232316044@23.23.16 (190400-540660214):7)
06-30 10:29:33.531 12235 19035 E GmsConnectionFactory:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
06-30 10:29:33.531 12235 19035 E GmsConnectionFactory:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
06-30 10:29:33.531 12235 19035 E GmsConnectionFactory:  at acoq.run(:com.google.android.gms@232316044@23.23.16 (190400-540660214):0)
06-30 10:29:33.531 12235 19035 E GmsConnectionFactory:  at java.lang.Thread.run(Thread.java:1012)
06-30 10:29:33.536 12235 19035 E Ads     : Failed to connect to ********************************************************** No DSID retrieved.
06-30 10:29:33.541 12235 19035 E GmsConnectionFactory: UID for network attribution might be misset for tag 805306624 [CONTEXT service_id=39 ]
06-30 10:29:33.541 12235 19035 E GmsConnectionFactory: djjo: FULL
06-30 10:29:33.541 12235 19035 E GmsConnectionFactory:  at d.N(:com.google.android.gms@232316044@23.23.16 (190400-540660214):0)
06-30 10:29:33.541 12235 19035 E GmsConnectionFactory:  at aoen.a(:com.google.android.gms@232316044@23.23.16 (190400-540660214):14)
06-30 10:29:33.541 12235 19035 E GmsConnectionFactory:  at arci.c(:com.google.android.gms@232316044@23.23.16 (190400-540660214):8)
06-30 10:29:33.541 12235 19035 E GmsConnectionFactory:  at arci.b(:com.google.android.gms@232316044@23.23.16 (190400-540660214):0)
06-30 10:29:33.541 12235 19035 E GmsConnectionFactory:  at com.google.android.gms.ads.social.d.d(:com.google.android.gms@232316044@23.23.16 (190400-540660214):5)
06-30 10:29:33.541 12235 19035 E GmsConnectionFactory:  at com.google.android.gms.ads.social.d.c(:com.google.android.gms@232316044@23.23.16 (190400-540660214):5)
06-30 10:29:33.541 12235 19035 E GmsConnectionFactory:  at com.google.android.gms.ads.social.d.a(:com.google.android.gms@232316044@23.23.16 (190400-540660214):8)
06-30 10:29:33.541 12235 19035 E GmsConnectionFactory:  at com.google.android.gms.ads.social.e.c(:com.google.android.gms@232316044@23.23.16 (190400-540660214):1)
06-30 10:29:33.541 12235 19035 E GmsConnectionFactory:  at com.google.android.gms.ads.social.n.call(:com.google.android.gms@232316044@23.23.16 (190400-540660214):9)
06-30 10:29:33.541 12235 19035 E GmsConnectionFactory:  at dnez.a(:com.google.android.gms@232316044@23.23.16 (190400-540660214):0)
06-30 10:29:33.541 12235 19035 E GmsConnectionFactory:  at dndz.run(:com.google.android.gms@232316044@23.23.16 (190400-540660214):3)
06-30 10:29:33.541 12235 19035 E GmsConnectionFactory:  at dnfa.run(:com.google.android.gms@232316044@23.23.16 (190400-540660214):0)
06-30 10:29:33.541 12235 19035 E GmsConnectionFactory:  at acjj.c(:com.google.android.gms@232316044@23.23.16 (190400-540660214):6)
06-30 10:29:33.541 12235 19035 E GmsConnectionFactory:  at acjj.run(:com.google.android.gms@232316044@23.23.16 (190400-540660214):7)
06-30 10:29:33.541 12235 19035 E GmsConnectionFactory:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
06-30 10:29:33.541 12235 19035 E GmsConnectionFactory:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
06-30 10:29:33.541 12235 19035 E GmsConnectionFactory:  at acoq.run(:com.google.android.gms@232316044@23.23.16 (190400-540660214):0)
06-30 10:29:33.541 12235 19035 E GmsConnectionFactory:  at java.lang.Thread.run(Thread.java:1012)
06-30 10:29:33.545 12235 19035 E Ads     : Failed to connect to ********************************************************** No DSID retrieved.
06-30 10:29:33.552 12235 19035 E GmsConnectionFactory: UID for network attribution might be misset for tag 805306624 [CONTEXT service_id=39 ]
06-30 10:29:33.552 12235 19035 E GmsConnectionFactory: djjo: FULL
06-30 10:29:33.552 12235 19035 E GmsConnectionFactory:  at d.N(:com.google.android.gms@232316044@23.23.16 (190400-540660214):0)
06-30 10:29:33.552 12235 19035 E GmsConnectionFactory:  at aoen.a(:com.google.android.gms@232316044@23.23.16 (190400-540660214):14)
06-30 10:29:33.552 12235 19035 E GmsConnectionFactory:  at arci.c(:com.google.android.gms@232316044@23.23.16 (190400-540660214):8)
06-30 10:29:33.552 12235 19035 E GmsConnectionFactory:  at arci.b(:com.google.android.gms@232316044@23.23.16 (190400-540660214):0)
06-30 10:29:33.552 12235 19035 E GmsConnectionFactory:  at com.google.android.gms.ads.social.d.d(:com.google.android.gms@232316044@23.23.16 (190400-540660214):5)
06-30 10:29:33.552 12235 19035 E GmsConnectionFactory:  at com.google.android.gms.ads.social.d.c(:com.google.android.gms@232316044@23.23.16 (190400-540660214):5)
06-30 10:29:33.552 12235 19035 E GmsConnectionFactory:  at com.google.android.gms.ads.social.d.a(:com.google.android.gms@232316044@23.23.16 (190400-540660214):8)
06-30 10:29:33.552 12235 19035 E GmsConnectionFactory:  at com.google.android.gms.ads.social.e.c(:com.google.android.gms@232316044@23.23.16 (190400-540660214):1)
06-30 10:29:33.552 12235 19035 E GmsConnectionFactory:  at com.google.android.gms.ads.social.n.call(:com.google.android.gms@232316044@23.23.16 (190400-540660214):9)
06-30 10:29:33.552 12235 19035 E GmsConnectionFactory:  at dnez.a(:com.google.android.gms@232316044@23.23.16 (190400-540660214):0)
06-30 10:29:33.552 12235 19035 E GmsConnectionFactory:  at dndz.run(:com.google.android.gms@232316044@23.23.16 (190400-540660214):3)
06-30 10:29:33.552 12235 19035 E GmsConnectionFactory:  at dnfa.run(:com.google.android.gms@232316044@23.23.16 (190400-540660214):0)
06-30 10:29:33.552 12235 19035 E GmsConnectionFactory:  at acjj.c(:com.google.android.gms@232316044@23.23.16 (190400-540660214):6)
06-30 10:29:33.552 12235 19035 E GmsConnectionFactory:  at acjj.run(:com.google.android.gms@232316044@23.23.16 (190400-540660214):7)
06-30 10:29:33.552 12235 19035 E GmsConnectionFactory:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
06-30 10:29:33.552 12235 19035 E GmsConnectionFactory:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
06-30 10:29:33.552 12235 19035 E GmsConnectionFactory:  at acoq.run(:com.google.android.gms@232316044@23.23.16 (190400-540660214):0)
06-30 10:29:33.552 12235 19035 E GmsConnectionFactory:  at java.lang.Thread.run(Thread.java:1012)
06-30 10:29:33.555 12235 19035 E Ads     : Failed to connect to ********************************************************** No DSID retrieved.

**Comment by everymedia22** [comment]
> @sureshem30 were you able to find solution?

No. It was not solved
