### ISSUE TITLE
rewarded.load() is not working

### ISSUE THREAD

**Issue by mhr996** [invertase/react-native-google-mobile-ads#400]
### What happened?

I've followed the documentation step by step to add reward ads, however, reward.load() is not loading any ads when I navigate to the screen, here is my code: 

`const adUnitId = __DEV__ ? TestIds.REWARDED : "ca-app-pub-***********";

  const rewarded = RewardedAd.createForAdRequest(adUnitId, {
    requestNonPersonalizedAdsOnly: true,
    keywords: ["business", "job"],
  });

  useEffect(() => {
   const unsubscribeLoaded = rewarded.addAdEventListener(RewardedAdEventType.LOADED, () => {
     setAdLoaded(true);
     console.log("ad has been loaded");
   });
   const unsubscribeEarned = rewarded.addAdEventListener(
     RewardedAdEventType.EARNED_REWARD,
     (reward) => {
       setEarned(true);
       console.log("reward earned" + reward.amount);
     }
   );

   const unsubscribeClosed = rewarded.addAdEventListener(AdEventType.CLOSED, (reward) => {
     console.log("ad has been closed");
     setAdLoaded(false);
     rewarded.load();
   });

   // Start loading the rewarded ad straight away
   rewarded.load();
   console.log("started loading ad");

   // Unsubscribe from events on unmount
   return () => {
     unsubscribeLoaded();
     unsubscribeEarned();
     unsubscribeClosed();
   };
  }, []);

return (
<TouchableOpacity
        style={styles.adBTN}
        activeOpacity={0.9}
        onPress={() => {
          if (rewarded.loaded) {
            rewarded.show();
          }
        }}>
    
      </TouchableOpacity>
)`

The weird thing is that when I'm in the development build, and I'm inside the reward page, i change some text or something, so the expo app does a refresh, then, the ad is opened, but then when I close it, and try again, it doesn't load, I get out of the screen then return to it, and it doesn't load! what a confusing issue that's happening, Is anything wrong with my code?

### Platforms

Only on Android

### React Native Info

```Shell
I'm using expo
```

### Are your using Typescript?

- [ ] My project is using Typescript

### package.json

```JSON
{
  "name": "forsa",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "1.17.11",
    "@react-native-community/slider": "4.2.4",
    "@react-navigation/bottom-tabs": "^6.5.4",
    "@react-navigation/core": "^6.4.6",
    "@react-navigation/native": "^6.1.3",
    "@react-navigation/native-stack": "^6.9.9",
    "algoliasearch": "^4.17.1",
    "expo": "47",
    "expo-app-loading": "^2.1.1",
    "expo-clipboard": "~4.0.1",
    "expo-dev-client": "~2.0.1",
    "expo-device": "~5.0.0",
    "expo-font": "~11.0.1",
    "expo-image-picker": "~14.0.2",
    "expo-linear-gradient": "~12.0.1",
    "expo-linking": "~3.3.1",
    "expo-notifications": "~0.17.0",
    "expo-splash-screen": "~0.17.5",
    "expo-status-bar": "~1.4.4",
    "expo-updates": "~0.15.6",
    "firebase": "^9.17.1",
    "lottie-react-native": "5.1.4",
    "moment": "^2.29.4",
    "react": "18.1.0",
    "react-instantsearch-hooks": "^6.44.2",
    "react-native": "0.70.8",
    "react-native-animatable": "^1.3.3",
    "react-native-dropdown-picker": "^5.4.4",
    "react-native-eva-icons": "^1.3.1",
    "react-native-gesture-handler": "~2.8.0",
    "react-native-google-mobile-ads": "^11.1.1",
    "react-native-modalbox": "^2.0.2",
    "react-native-phone-number-input": "^2.1.0",
    "react-native-safe-area-context": "4.4.1",
    "react-native-screens": "~3.18.0",
    "react-native-svg": "13.4.0",
    "react-native-swiper-flatlist": "^3.0.18",
    "react-native-web": "~0.18.11"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}
```

### app.json

```JSON
{
  "expo": {
    "scheme": "forsa",
    "name": "Forsa - فرصة",
    "slug": "forsa",
    "version": "1.1.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "userInterfaceStyle": "light",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#000000"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": ["**/*"],
    "ios": {
      "supportsTablet": true
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#000000"
      },
      "intentFilters": [
        {
          "action": "VIEW",
          "autoVerify": true,
          "data": [
            {
              "scheme": "https",
              "host": "forsaapp.com"
            }
          ],
          "category": ["BROWSABLE", "DEFAULT"]
        }
      ],
      "package": "com.markmhr.chanceApp",
      "versionCode": 4,
      "permissions": []
    },
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "plugins": [
      [
        "expo-notifications",
        {
          "icon": "./assets/icon.png",
          "color": "#000000"
        }
      ]
    ],
    "extra": {
      "eas": {
        "projectId": "bec5c500-f8ea-431d-b222-******8"
      }
    }
  },
  "react-native-google-mobile-ads": {
    "android_app_id": "ca-app-pub-********"
  }
}
```

**Comment by arncet** [comment]
I have the same issue :(

**Comment by tholmgren** [comment]
Me too, very similar code for the rewarded ad.  
I also have banner ads, they load fine.  

I'm using Expo 48

**Comment by tholmgren** [comment]
Incase it helps anyone else, 

As a work around for testing, I created a try catch, if it failed, I just loaded a new ad.  

   const FireRewardAd = () => {
    try {
      rewarded.show();
      console.log("reward showed");

    } catch (error) {
      rewarded.load();
      console.log("reward loaded");
   
    }
  };

**Comment by davewang** [comment]
As a work around using a hook is work for me!
```javascript
 const { isLoaded, isClosed,isEarnedReward , load, show } =  useRewardedAd(adUnitRewardId);
```

**Comment by haophan1507** [comment]
I have the same issue, it usually works the first time, but isLoaded=false a long time after that

**Comment by JuEunSung** [comment]
i can't speak English perfectly ... But I hope I can be of any help. :)

try this...

i maked hooks


`
export function useHandleAdmobReward() {
  const { isLoaded, load, show } = useRewardedAd(AD_KEY.REWARD[Platform.OS.toUpperCase()], {
    requestNonPersonalizedAdsOnly: true,
    keywords: ['exchange', 'travel', 'trip', 'financial', 'stock', 'family'],
  });

  useEffect(() => {
    if (!isLoaded) {
      load();
    }
  }, [isLoaded, load]);

  const openAd = () => {
    if (isLoaded) {
      show();
    }
  };

  return {
    isLoaded,
    openAd,
  };
}
`

your screen or component etc ...

`
.
.
.

const { isLoaded, openAd } = useHandleAdmobReward();

...

// apply a disabled button style accordingly if you wish.
<Button onPress={openAd} disabled={isLoaded}> 
  <Text>Show AD</Text>
</Button>

.
.
.
`

**Comment by arncet** [comment]
I really don't like it but i found a way to fix this issue, by re-creating the reward object each time i want to play it : 

```ts
import { useEffect, useRef, useState } from 'react';
import MobileAds, { RewardedAd, RewardedAdEventType, TestIds } from 'react-native-google-mobile-ads';

const adUnitId = __DEV__ ? TestIds.REWARDED : 'ca-app-pub-xxxxxxxxxxxxx/yyyyyyyyyyyyyy';

const useRewardAd = () => {
  const [isLoaded, setIsLoaded] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const rewarded = useRef<RewardedAd | null>(null);
  const unsubscribeLoaded = useRef<() => void | null>(null);
  const unsubscribeEarned = useRef<() => void | null>(null);

  const destroy = () => {
    if (unsubscribeLoaded.current) unsubscribeLoaded.current();
    if (unsubscribeEarned.current) unsubscribeEarned.current();
    rewarded.current = null;
    setIsLoaded(false);
    setIsLoading(false);
  };

  const play = () => {
    try {
      destroy();
      setIsLoading(true);

      rewarded.current = RewardedAd.createForAdRequest(adUnitId, {
        requestNonPersonalizedAdsOnly: true,
        keywords: ['fashion', 'clothing'],
      });

      unsubscribeLoaded.current = rewarded.current.addAdEventListener(RewardedAdEventType.LOADED, () => {
        setIsLoaded(true);
        setIsLoading(false);
      });

      unsubscribeEarned.current = rewarded.current.addAdEventListener(
        RewardedAdEventType.EARNED_REWARD,
        reward => {
          console.warn('User earned reward of ', reward);
          destroy();
        },
      );

      rewarded.current.load();
    } catch (e) {
      setIsLoading(false);
      console.error(e);
      throw e;
    }
  }

  const openAdInspector = () => MobileAds().openAdInspector();

  useEffect(() => {
    if (isLoaded && rewarded.current) rewarded.current.show();
  }, [isLoaded]);

  useEffect(() => {
    return destroy;
  }, []);

  return ({
    isLoading,
    isLoaded,
    play,
    openAdInspector
  })
};

export default useRewardAd;

```

**Comment by magicvirus** [comment]
For anyone having trouble with rewarded ads I spent 2 days trying to work this out.

With many code crashes later. 

To get it to work with Expo EAS you need to use it via hooks. 

const { isLoaded, isClosed, load, show } = useInterstitialAd(TestIds.INTERSTITIAL, {
    requestNonPersonalizedAdsOnly: true,
  });

displaying-ads-hook
