### ISSUE TITLE
[📚] Get user choices for the app itself?

### ISSUE THREAD

**Issue by fr3nzy** [invertase/react-native-google-mobile-ads#410]
### Documentation Feedback

The GDPR form includes a section that allows users to give consent for the app's requested data collection. This is different to vendor consent. I can't see any way to access the consent choices like `AdsConsent.getUserChoices()` as it only returns vendor choices. Is there way to access this?

**Comment by DoctorJohn** [comment]
Yes, you can obtain and decode the TCString. It contains all selections made in the form including app requested data collection.

```ts
import {TCModel, TCString} from '@iabtcf/core';
import {AdsConsent} from 'react-native-google-mobile-ads';

function getTCModel() : TCModel {
  const tcString = await AdsConsent.getTCString();
  const tcModel = TCString.decode(tcString);
  return tcModel;
}

function userAllowedStorage(): boolean {
  const tcModel = getTCModel();
  return tcModel.purposeConsents.has(1);
}

function userAllowedPersonalizedAds(): boolean {
  const tcModel = getTCModel();
  return tcModel.purposeConsents.has(4);
}
```

You can find these values by either logging the TCModel instance or looking the TCString format up online.

**Comment by fr3nzy** [comment]
@DoctorJohn Perfect thank you!

It seems `iabtcf` is not needed at all, as `AdsConsent` has `getTCModel()` method, which allows us to skip getting the tcstring and decoding it :) 

```
...
const tcModel = await AdsConsent.getTCModel();
return tcModel.purposeConsents.has(1)
...
```

**Comment by fr3nzy** [comment]
@DoctorJohn Perfect thank you!

It seems `iabtcf` is not needed at all, as `AdsConsent` has `getTCModel()` method, which allows us to skip getting the tcstring and decoding it :) 

```
...
const tcModel = await AdsConsent.getTCModel();
return tcModel.purposeConsents.has(1)
...
```
