### ISSUE TITLE
Native Ads

### ISSUE THREAD

**Issue by akhzarna** [invertase/react-native-google-mobile-ads#42]
Can i implement Native Advance and App Open Ads of Google ADMob using this library ? Actually i did not find any option within this library. I have already implemented Banner, Interstitial and Rewarded using this Library

**Comment by dylancom** [comment]
I just created a PR to add "App Open Ads" support.
https://github.com/invertase/react-native-google-ads/pull/54

**Comment by dylancom** [comment]
App Open Ads can now be tested from 4.1.0. See the new package: https://www.npmjs.com/package/react-native-google-mobile-ads

**Comment by mikehardy** [comment]
Hey @dylancom are "native advance ads" the same as "app open ads"? Stated differently: can this be closed?

**Comment by dylancom** [comment]
@mikehardy No, it's a different format. Which is also the most difficult one to implement within RN as it let's you change the style to match your app. (typically used within social media apps, such as Twitter that has ads that look like Tweets and Instagram that have ads that look like a posted photo / video).

**Comment by ammarahm-ed** [comment]
I apologize for the long delay. I will open a draft PR this weekend.

**Comment by vivianmauer** [comment]
Hello

There's any update on this?

**Comment by mrkgmr** [comment]
Hi, is there some update with this? Seems that this is discontinued or something like that... :S

**Comment by dreamary-yj** [comment]
Is ther any update with this? 😢

**Comment by yaminichhabra** [comment]
Any updates ?

**Comment by TaylorDale** [comment]
Following

**Comment by muminbhat** [comment]
Following

**Comment by mikehardy** [comment]
@muminbhat just hit the subscribe button over on the right side people - otherwise you make notifications FOR EVERYONE THAT IS FOLLOWING

...just letting them know that you're following, which is sort of 🤷

**Comment by renatomserra** [comment]
I started a related post, this would be awesome, id participate in a bounty for this.
Kinda crazy to think google doesn't offer support for their main money maker in react native.

**Comment by SumitR9910** [comment]
Any updates on this?

**Comment by dylancom** [comment]
Native ads are supported as of today! https://docs.page/invertase/react-native-google-mobile-ads/native-ads
