### ISSUE TITLE
[🐛] Crashes on Android in development mode with Fabric enabled

### ISSUE THREAD

**Issue by birdofpreyru** [invertase/react-native-google-mobile-ads#420]
### What happened?

Hey guys, I just rapidly tried to enable Fabric in my existing app, where this library was the last piece preventing me to enable it (and I got it as since v11.3.0 it should be supported). So, it seems to work on Android in release builds, but crashes the app on start-up if run in development mode. Same behavior both in simulator and on a real device. Unfortunately, I don't have time right now to carefully troubleshoot it.

### Platforms

Android, but have not tested behavior on iOS

### React Native Info

```Shell
N/A
```

### Are your using Typescript?

- [ ] My project is using Typescript

### package.json

```JSON
N/A
```

### app.json

```JSON
N/A
```

**Comment by dylancom** [comment]
Have you tried / compared it with our demo app?

**Comment by birdofpreyru** [comment]
Sorry, false alarm. I am finally back to it, and have verified that my app crashes when something happens in react-native-webview, and not in this library. Also I have verified that demo app of RN Google Mobile Ads works for me fine.
