### ISSUE TITLE
[🐛] Bug Report Title - Cryptic Error when building for ios

### ISSUE THREAD

**Issue by noumankhan95** [invertase/react-native-google-mobile-ads#426]
### What happened?

im using expo managed workflow and added the package . eas builds the app successfully for  android but when i try to build the app for android it throws the following error 

**_❌  (node_modules/react-native-google-mobile-ads/ios/RNGoogleMobileAds/RNGoogleMobileAdsModule.mm:120:85)

  118 |   if (requestConfiguration[@"tagForChildDirectedTreatment"]) {
  119 |     BOOL tag = [requestConfiguration[@"tagForChildDirectedTreatment"] boolValue];
> 120 |     GADMobileAds.sharedInstance.requestConfiguration.tagForChildDirectedTreatment = tag;
      |                                                                                     ^ incompatible integer to pointer conversion assigning to 'NSNumber * _Nullable' from 'BOOL' 
  121 |   }
  122 | 
  123 |   if (requestConfiguration[@"tagForUnderAgeOfConsent"]) {

❌  (node_modules/react-native-google-mobile-ads/ios/RNGoogleMobileAds/RNGoogleMobileAdsModule.mm:125:80)

  123 |   if (requestConfiguration[@"tagForUnderAgeOfConsent"]) {
  124 |     BOOL tag = [requestConfiguration[@"tagForUnderAgeOfConsent"] boolValue];
> 125 |     GADMobileAds.sharedInstance.requestConfiguration.tagForUnderAgeOfConsent = tag;
      |                                                                                ^ incompatible integer to pointer conversion assigning to 'NSNumber * _Nullable' from 'BOOL' 
  126 |   }
  127 | 
  128 |   if (requestConfiguration[@"testDeviceIdentifiers"]) {

› Compiling react-native-google-mobile-ads Pods/RNGoogleMobileAds » RNGoogleMobileAdsInterstitialModule.m

› Compiling react-native-google-mobile-ads Pods/RNGoogleMobileAds » RNGoogleMobileAdsConsentModule.m

› Compiling react-native-google-mobile-ads Pods/RNGoogleMobileAds » RNGoogleMobileAdsCommon.mm

› Compiling react-native-google-mobile-ads Pods/RNGoogleMobileAds » RNGoogleMobileAdsBannerViewManager.mm

    Run script build phase '[CP-User] Generate app.config for prebuilt Constants.manifest' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'EXConstants' from project 'Pods')

    Run script build phase 'Start Packager' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Tarrhoon' from project 'Tarrhoon')

    Run script build phase 'Bundle React Native code and images' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Tarrhoon' from project 'Tarrhoon')

    Run script build phase '[CP-User] [RNGoogleMobileAds] Configuration' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Tarrhoon' from project 'Tarrhoon')

▸ ** BUILD FAILED **

▸ The following build commands failed:

▸ 	CompileC /Users/expo/workingdir/build/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNGoogleMobileAds.build/Objects-normal/x86_64/RNGoogleMobileAdsModule.o /Users/expo/workingdir/build/node_modules/react-native-google-mobile-ads/ios/RNGoogleMobileAds/RNGoogleMobileAdsModule.mm normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'RNGoogleMobileAds' from project 'Pods')

▸ (1 failure)

** BUILD FAILED **

The following build commands failed:

	CompileC /Users/expo/workingdir/build/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNGoogleMobileAds.build/Objects-normal/x86_64/RNGoogleMobileAdsModule.o /Users/expo/workingdir/build/node_modules/react-native-google-mobile-ads/ios/RNGoogleMobileAds/RNGoogleMobileAdsModule.mm normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'RNGoogleMobileAds' from project 'Pods')

(1 failure)

Exit status: 65

+-------------+-------------------------+

|           Build environment           |

+-------------+-------------------------+

| xcode_path  | /Applications/Xcode.app |

| gym_version | 2.211.0                 |

| sdk         | iPhoneOS16.2.sdk        |

+-------------+-------------------------+

Looks like fastlane ran into a build/archive error with your project

It's hard to tell what's causing the error, so we wrote some guides on how

to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/

Before submitting an issue on GitHub, please follow the guide above and make

sure your project is set up correctly.

fastlane uses `xcodebuild` commands to generate your binary, you can see the

the full commands printed out in yellow in the above log.

Make sure to inspect the output above, as usually you'll find more error information there

[stderr] 

[!] Error building the application - see the log above

Error: The "Run fastlane" step failed with an unknown error. Refer to "Xcode Logs" below for additional, more detailed logs._**

![Screenshot (453)](https://github.com/invertase/react-native-google-mobile-ads/assets/67652122/0bae0169-6d55-492a-820b-bd8e02033538)

### Platforms

Only on iOS

### React Native Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz
    Memory: 1.24 GB / 7.91 GB
  Binaries:
    Node: 17.8.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.12.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 30, 31, 33
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.2, 34.0.0
      System Images: android-30 | Google APIs Intel x86 Atom, android-33 | Google APIs Intel x86_64 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.33130.400 (Visual Studio Community 2019)
  Languages:
    Java: 11.0.17 - C:\Program Files\Java\jdk-11.0.17\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.8 => 0.71.8
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Are your using Typescript?

- [ ] My project is using Typescript

### package.json

```JSON
{
  "name": "social_assistance",
  "version": "1.1",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "1.17.11",
    "@react-native-community/netinfo": "9.3.7",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.12",
    "@stripe/stripe-react-native": "0.23.3",
    "expo": "~48.0.18",
    "expo-av": "~13.2.1",
    "expo-constants": "~14.2.1",
    "expo-dev-client": "~2.2.1",
    "expo-device": "~5.2.1",
    "expo-document-picker": "~11.2.2",
    "expo-file-system": "^15.2.2",
    "expo-image-picker": "~14.1.1",
    "expo-media-library": "~15.2.3",
    "expo-notifications": "^0.18.1",
    "expo-sharing": "^11.2.2",
    "expo-splash-screen": "~0.18.2",
    "expo-status-bar": "~1.4.4",
    "expo-task-manager": "~11.1.1",
    "firebase": "^9.23.0",
    "path": "^0.12.7",
    "radio-buttons-react-native": "^1.0.4",
    "react": "18.2.0",
    "react-native": "0.71.8",
    "react-native-dotenv": "^3.4.9",
    "react-native-google-mobile-ads": "^11.4.0",
    "react-native-paper": "^5.8.0",
    "react-native-safe-area-context": "4.5.0",
    "react-native-screens": "^3.20.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "babel-plugin-transform-inline-environment-variables": "^0.4.4"
  },
  "private": true
}
```

### app.json

```JSON
{
  "expo": {
    "name": "Tarrhoon",
    "slug": "social_assistance",
    "version": "1.3",
    "orientation": "portrait",
    "icon": "./assets/appicon.png",
    "userInterfaceStyle": "light",
    "notification": {
      "icon": "./assets/appicon.png"
    },
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "cover"
    },
    "plugins": [
      [
        "expo-notifications",
        {
          "icon": "./assets/splashlogo.png",
          "color": "#ffffff"
        }
      ],
      [
        "expo-media-library",
        {
          "photosPermission": "Allow Social Assistance to access your photos.",
          "savePhotosPermission": "Allow Social Assistance to save photos.",
          "isAccessMediaLocationEnabled": true
        }
      ],
      [
        "expo-image-picker",
        {
          "photosPermission": "The app accesses your photos to let you share them With the Admin"
        }
      ],
      [
        "expo-av",
        {
          "microphonePermission": "Allow App to access your microphone."
        }
      ]
    ],
    "assetBundlePatterns": ["**/*"],
    "ios": {
      "icon": "./assets/simpleicon.png",
      "supportsTablet": true,
      "infoPlist": {
        "UIBackgroundModes": ["audio"],
        "NSPhotoLibraryUsageDescription": "Allow Social Assistance to access your photos.",
        "NSPhotoLibraryAddUsageDescription": "Allow Social Assistance to save photos."
      },
      "bundleIdentifier": "com.muhammad1700.social-assistance"
    },
    "android": {
      "versionCode": 3,
      "icon": "./assets/simpleicon.png",
      "googleServicesFile": "./google-services.json",
      "adaptiveIcon": {
        "foregroundImage": "./assets/appicon.png",
        "backgroundColor": "#7369ef"
      },
      "package": "com.muhammad1700.social_assistance",
      "permissions": [
        "android.permission.READ_EXTERNAL_STORAGE",
        "android.permission.WRITE_EXTERNAL_STORAGE",
        "android.permission.ACCESS_MEDIA_LOCATION",
        "android.permission.RECORD_AUDIO",
        "android.permission.MODIFY_AUDIO_SETTINGS"
      ]
    },
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "extra": {
      "eas": {
        "projectId": "****************************"
      }
    }
  },
  "react-native-google-mobile-ads": {
    "android_app_id": "**************************",
    "ios_app_id": "**************************"
  }
}
```

**Comment by dylancom** [comment]
This has been fixed in 11.4.1...
https://github.com/invertase/react-native-google-mobile-ads/releases/tag/v11.4.1
