### ISSUE TITLE
[🐛] How to pass Network Extras bundle to AdRequest.Builder

### ISSUE THREAD

**Issue by vishal-developer** [invertase/react-native-google-mobile-ads#431]
### What happened?

Hi Team,
I am using mediation set up by creating custom SDK adapter/network as an ad adapter using https://developers.google.com/admob/android/custom-events/setup.
I want to pass some parameters to adapter classes. Can you please help me understand which API I should use to pass params to custom adapter classes.

### Platforms

Android, but have not tested behavior on iOS

### React Native Info

```Shell
NA
```

### Are your using Typescript?

- [X] My project is using Typescript

### package.json

```JSON
NA
```

### app.json

```JSON
NA
```

### ios/Podfile

```Ruby
NA
```

### android/build.gradle

```Groovy
NA
```

### android/app/build.gradle

```Groovy
NA
```

### android/settings.gradle

```Groovy
NA
```

### AndroidManifest.xml

```XML
NA
```

**Comment by dylancom** [comment]
I don't think we support this currently. Feel free to make a PR.
