### ISSUE TITLE
java.lang.NullPointerException ReactNativeGoogleMobileAdsBannerAdViewManager.initAdView 

### ISSUE THREAD

**Issue by sedatb** [invertase/react-native-google-mobile-ads#432]
### What happened?

app crashing in android

 io.invertase.googlemobileads.ReactNativeGoogleMobileAdsBannerAdViewManager.initAdView (ReactNativeGoogleMobileAdsBannerAdViewManager.java:174)
 
 I use   "react-native-google-mobile-ads": "^11.6.3" version
 

### Platforms

Only on Android

### React Native Info

```Shell
System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M1
    Memory: 38.42 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.2.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.6 - /opt/homebrew/bin/npm
    Watchman: 2023.05.22.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.10121639
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.19 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.4 => 0.68.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Are your using Typescript?

- [ ] My project is using Typescript

### package.json

```JSON
"react": "17.0.2",
    "react-native": "0.68.4",
    "react-native-device-info": "^10.2.0",
    "react-native-fast-image": "^8.3.7",
    "react-native-gesture-handler": "^2.10.0",
    "react-native-google-mobile-ads": "^11.6.3",
```

### app.json

```JSON
"name": "xxx",
  "displayName": "xxx",
```

**Comment by dylancom** [comment]
Hmm maybe caused by this change: https://github.com/invertase/react-native-google-mobile-ads/commit/984247ff80dab36004bd49c27a20f489e075029b ?

**Comment by sedatb** [comment]
I added null check in initAdView and requestAd methods.

in initAdView
if(adView = new AdManagerAdView(reactViewGroup.getContext()) != null){
adView =
          new AdManagerAdView(
              Objects.requireNonNull(
                  ((ReactContext) reactViewGroup.getContext()).getCurrentActivity()));
                  ....
} else {
return null
}....

in requestAd method

BaseAdView adView = initAdView(reactViewGroup);
if(adView != null)


it solves I think

**Comment by sedatb** [comment]
I think it solves but I am not sure it is correct. It prevents crashes in crashlytic. This package should be updated. Do you have any ideas ?

**Comment by sedatb** [comment]
@mikehardy thanks for new version.
