### ISSUE TITLE
EXPO SDK 49 - react-native-google-mobile-ads 12.0.0, debugGeography key not working, cannot set a debug location to EEA

### ISSUE THREAD

**Issue by drakulic-goran** [invertase/react-native-google-mobile-ads#435]
### What happened?

Setting debugGeography key to AdsConsentDebugGeography.EEA does not give any result, still getting status NotRequired and not getting consent form to show.

const consentInfo = await AdsConsent.requestInfoUpdate({
     debugGeography: AdsConsentDebugGeography.EEA, 
     testDeviceIdentifiers: ['MY-DEVICE-HASHED-ID'], 
});

On SDK 47 with react-native-google-mobile-ads 8.1.2. this worked perfect.

### Platforms

Android, but have not tested behavior on iOS

### React Native Info

```Shell
expo sdk 49, eas build, dev-client
```

### Are your using Typescript?

- [X] My project is using Typescript

### package.json

```JSON
EXPO 49.0.0 
react-native-google-mobile-ads 12.0.0
```

### app.json

```JSON
app.json
```

**Comment by dylancom** [comment]
You could try to run the project from Android Studio and log https://github.com/invertase/react-native-google-mobile-ads/blob/2a632f0e64caae705e21248269b788cf6728a899/android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsConsentModule.java#L103

**Comment by Jeffreyoboe1** [comment]
I am seeing the same issue.  on iOS, I receive response and see the form as expected.  On android, both on emulator and on a real device, I get the following response upon `requestInfoUpdate($options)`:

consentInfo Object {
  "canRequestAds": true,
  "isConsentFormAvailable": false,
  "privacyOptionsRequirementStatus": "NOT_REQUIRED",
  "status": "NOT_REQUIRED",
}

Any assistance please?

**Comment by fr3nzy** [comment]
I'm in the UK, which is no longer part of the EEA. However the `privacyOptionsRequirementStatus` is always 'REQUIRED', and changing the debug geography changes nothing. No matter the location selected, the form is always required

**Comment by TaylorDale** [comment]
At a quick glance this is happening to me too. (non expo, have specified debugGeography: AdsConsentDebugGeography.EEA )  and I am not getting the form, result of STDAdsConsentRequest() is 

{"canRequestAds": true, "isConsentFormAvailable": false, "privacyOptionsRequirementStatus": "NOT_REQUIRED", "status": "NOT_REQUIRED"}

**Comment by ayeshabasit** [comment]
This is still an issue

**Comment by ahlbet** [comment]
I am having this issue as well on a real ios device. I'm not using expo and I'm running `react-native-google-mobile-ads` v12.4.0. Here's how I'm attempting to request:

```
  const uniqueId = await DeviceInfo.getUniqueId();

  const consentInfo = await AdsConsent.requestInfoUpdate({
    debugGeography: AdsConsentDebugGeography.EEA,
    testDeviceIdentifiers: [uniqueId],
  });
```

The docs aren't clear on which device id from `react-native-device-info` to use but I've tried both from `.getUniqueId` and `.getDeviceId` and neither work. The response for consent info is always

```
{"canRequestAds": true, "isConsentFormAvailable": 0, "privacyOptionsRequirementStatus": "NOT_REQUIRED", "status": "NOT_REQUIRED"}
```
@drakulic-goran were you able to resolve this issue?

**Comment by aleks-2amigos** [comment]
I have just encountered this issue on:
```
"expo": "~51.0.28",
"react-native-google-mobile-ads": "^14.2.3",
```

**Comment by Rc85** [comment]
I am facing this issue as well on Android.

**Comment by tewellg** [comment]
I was struggling with this issue, but since it's not a package bug, just incomplete documentation examples, I don't think it's appropriate to put a long winded answer here, so here's an SO link to what worked for me: https://stackoverflow.com/questions/77146972/consent-form-available-false-react-native-google-mobile-ads/79594382#79594382

**Comment by dylancom** [comment]
Instead of complaining about the docs, make it better by submitting a PR.

**Comment by tewellg** [comment]
> Instead of complaining about the docs, make it better by submitting a PR.

Apologies if it sounded like I was complaining - my intention was to help with the reply, not complain.

**Comment by stavbi1** [comment]
any updates on this? i'm getting isConsentFormAvailable = false no matter what I do

**Comment by liveasypeasy** [comment]
I ran into the same issue with
```
"expo": "~54.0.30",
"react-native-google-mobile-ads": "^16.0.0",
```

Referencing an old SO post (https://stackoverflow.com/questions/4524752/how-can-i-get-device-id-for-admob), turned out I needed to hash the uniqueId from `react-native-device-info`. So what worked for me was
```
const uniqueId = await getUniqueId();
const deviceId = stringMd5(uniqueId).toUpperCase();
consentInfo = await AdsConsent.requestInfoUpdate({
  debugGeography: AdsConsentDebugGeography.EEA,
  testDeviceIdentifiers: [deviceId],
});
```

where `stringMd5()` was from `react-native-quick-md5`.
