### ISSUE TITLE
🔥[🐛] addListener on AdEvents replaces existing listeners, does not allow multiple

### ISSUE THREAD

**Issue by TaylorDale** [invertase/react-native-google-mobile-ads#44]
I'm implementing this module and one of the more design-orientated issues I've come across is the use of onAdEvent. To avoid having a large renderable component that manages the state of the ads, I'm using React's context API to provide access to the ad classes throughout the app.

```
const [adCTX] = useState({
    interstitial: new GADSWrapper(
      InterstitialAd.createForAdRequest(AdmobId.periodicInt1, {
        requestNonPersonalizedAdsOnly: false,
      }),
    ),
    rewarded: new GADSWrapper(
      RewardedAd.createForAdRequest(AdmobId.removeAdReward, {
        requestNonPersonalizedAdsOnly: false,
      }),
    ),
  });

<AdContext.Provider value={adCTX}>
      <App />
 </AdContext.Provider>

```

Some advantages of doing it this way:
- no/less prop drilling
- a lot of apps (I make anyway) it's appropriate to consider ads as a more "global" feature, naturally works better this way/Manage logic where appropriate (load ad at the start of the app when context is initialised, show it much further down the component tree via a button)
- no unnecessary re-renders ?
- avoid mega-components where a lot of logic is all written in the one place, write load logic in app start, write display logic in a button component, write reward logic elsewhere

The current setup however I'm running into issues, mainly due to the fact onAdEvent can only have one listener at a time, and when you try to add another one (as you would with addListener on an EventEmitter) it will overwrite the old one (Which was a little confusing at first and I had to dig into the source, as I expected it to act similarly)!

What I've ended up doing is making an EventEmitter wrapper class, that allows multiple listeners to be added.

Something to consider for implementation natively in this library? 

For reference - this is the wrapper class/ctx provider I have written (the "AdsEventListener" method can be used in the useEffect block of a component to register for events):
```
import { GoogleAdsTypes, RewardedAd } from '@invertase/react-native-google-ads';
import { createContext } from 'react';
import { EventEmitter } from 'events';

export class GADSWrapper<
  T extends GoogleAdsTypes.RewardedAd | GoogleAdsTypes.InterstitialAd,
> extends EventEmitter {
  public ads: T;
  private unbind: () => void;

  constructor(ads: T) {
    super();
    this.ads = ads;
    this.unbind = ads.onAdEvent(this.onEvent.bind(this));
  }

  //: GoogleAdsTypes.AdEventType | GoogleAdsTypes.RewardedAdEventType
  onEvent(event: any) {
    this.emit('event', event);
  }

  AdsEventListener(
    callback: (
      event:
        | GoogleAdsTypes.AdEventType
        | GoogleAdsTypes.RewardedAdEventType
        | string,
    ) => void,
  ) {
    this.addListener('event', callback);
    return () => {
      this.removeListener('event', callback);
    };
  }

  Unbind() {
    this.unbind();
  }
}

export interface IAdContext {
  rewarded: GADSWrapper<GoogleAdsTypes.RewardedAd>;
  interstitial: GADSWrapper<GoogleAdsTypes.InterstitialAd>;
}

const AdContext = createContext({} as IAdContext);

export default AdContext;
```

**Comment by Mikenso** [comment]
Hi, 
1. Why do you use useState in this case? Consider using useMemo
2. Why do you specifically develop your own context wrapper when you can use Redux or any other popular library? With redux sagas you can use event emitter for as many google ads entities as you want. 
3. When your project will grow you will face more and more cases with listeners, subscritions and etc. So you will put more and more around app root component? - this is why again it is better to use global state managemant

So I think There is no need to implement this feature natively

**Comment by mikehardy** [comment]
I was under the impression any time you changed a context, all consumers had to re-render, eliminating the unnecessary re-render as a pro of the approach?

Here's what I think: none of your arguments are actually important to consider. What I read was:

"only one listener is allowed at a time, multiple listeners should be possible"

Do you think that sums it up? If so, it would steer clear of all the inevitable bike-shedding about application design.

**Comment by TaylorDale** [comment]
That's fair, since the introduction of context for many of my apps I have found redux to be a little overcomplicated and have just stuck with context for app state.

Re being opinionated about app structure @mikehardy that makes sense to me, I am coming at it from a very specific use case perspective. 

**So re-setting the question:** Your summation is correct. I find the behaviour that if I use the provided "onAdEvent" multiple times it will overwrite the previous listeners a little undefined-ey (or atleast unclear), also coming with the expectation from usual JS usage of the EventEmitter pattern of using addListener.

**Comment by mikehardy** [comment]
I use context myself, I was hiding my actual opinion for the purpose of being your unrequested irritating intellectual sparring partner on design ;-).

Yeah, I'd say it's a bug personally. If it's going to overwrite, it should be "setListener", "addListener" has a clear implication of a manageable collection

Okay, I'm going to alter the title and for the avoidance of doubt attempt to state clearly (correct me if I'm wrong):

addListener should allow multiple listeners for adEvent, right now it is replacing, not adding

**Comment by TaylorDale** [comment]
> addListener should allow multiple listeners for adEvent, right now it is replacing, not adding

Perfect!

> I use context myself, I was hiding my actual opinion for the purpose of being your unrequested irritating intellectual sparring partner on design ;-).

I'm up for it - haven't had a good design pattern spar for a while :P 🥊🥊

Cheers mate.

**Comment by pierroo** [comment]
> Hi,
> 
> 1. Why do you use useState in this case? Consider using useMemo
> 2. Why do you specifically develop your own context wrapper when you can use Redux or any other popular library? With redux sagas you can use event emitter for as many google ads entities as you want.
> 3. When your project will grow you will face more and more cases with listeners, subscritions and etc. So you will put more and more around app root component? - this is why again it is better to use global state managemant
> 
> So I think There is no need to implement this feature natively

I would love to see an example of how to implement it with redux.
As stated above, I would like to prevent countless re-render on heavy main component; but I would also like to have the listener of ads event centered at one place.
As well as being able to load() and show() ads from anywhere in the app, without having to recreate the add through createForAdRequest each time.

I'm still unable to find a way to do so, for adding the created ad into redux will always lead to this error:

 redux-persist/createPersistoid: error serializing state TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'EventSubscriptionVendor'
    |     property '_subscriptionsForType' -> object with constructor 'Object'
    |     property 'google_ads_interstitial_event' -> object with constructor 'Array'
    |     index 0 -> object with constructor 'EmitterSubscription'
    --- property 'subscriber' closes the circle

am I missing something? :/

**Comment by Mikenso** [comment]
@pierroo Hi

>  I'm still unable to find a way to do so, for adding the created ad into redux will always lead to this error:
>  redux-persist/createPersistoid: error serializing state TypeError: Converting circular structure to JSON

You should not try to store advert instance (or any complex object) at reducer, especially when you persist it. 
You just need to initialise interstitial (or rewarded) instance at file field in your sagas adv logic file. And manage adv logic through dispatching actions (show action, or load, or whatever you want)

**Comment by mikehardy** [comment]
This has activity on #110 - will likely go in as part of implementation of Google Ad Manager support
