### ISSUE TITLE
[🐛] Ad Inspector Error: Ad Inspector closed unexpectedly

### ISSUE THREAD

**Issue by F170x** [invertase/react-native-google-mobile-ads#443]
### What happened?

I've just updated from `6.3.0` to `12.0.0` and now I'm getting an alert in my app with the following message:

> **Ad Inspector Error** 
> Ad Inspector closed unexpectedly.

![alert](https://github.com/googleads/swift-package-manager-google-mobile-ads/assets/69001223/a3a3167c-cf52-435d-b343-88623de96833)

I never call `openAdInspector` to open the inspector
The device is not in _Test devices_ in the admob console
I'm only using the component `<BannerAd />` and the ads works
I don't know how to reproduce it, I just updated and now I'm getting that alert on my app randomly a couple of times per day.

I think that it could be related to the update `10.8.0` of the SDK, because I patched this package to downgrade the SDK to `10.7.0` and the errors gone, and the release notes says:
> Ad inspector now displays the error that occurred when the session fails to start.

Release notes: https://developers.google.com/admob/ios/rel-notes

Do you know what could be happening?

### Platforms

Only on iOS

### React Native Info

```Shell
System:
  OS: macOS 13.5
  CPU: (8) arm64 Apple M1
  Memory: 57.47 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.20.2
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 8.19.4
    path: /usr/local/bin/npm
  Watchman:
    version: 2022.10.10.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10671973
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.3.1
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Are your using Typescript?

- [X] My project is using Typescript

### package.json

```JSON
{
  "dependencies": {
    "expo": "~49.0.7",
    "react": "18.2.0",
    "react-native": "0.72.4",
    "react-native-google-mobile-ads": "^12.0.0",
  },
  "devDependencies": {
    "@babel/core": "^7.22.10"
  }
}
```

### app.json

```JSON
{
  "react-native-google-mobile-ads": {
    "android_app_id": "...",
    "ios_app_id": "...",
    "delay_app_measurement_init": false,
    "optimize_initialization": true,
    "optimize_ad_loading": true,
    "user_tracking_usage_description": "..."
  },
  "expo": {
    "platforms": [
      "ios",
      "android"
    ],
    "jsEngine": "hermes"
  }
}
```

**Comment by UARRR** [comment]
Same here, using the iOS SDK.

**Comment by roman-sundurov** [comment]
The same problem.

**Comment by yangjunke** [comment]
I read this from Google docs : "Add your device as a test device. Ad inspector only launches on test devices."

https://developers.google.com/admob/ios/ad-inspector

**Comment by roman-sundurov** [comment]
I did not enable the Test Device Setup on SDK 10.9.0. But, I received an error message in the Ad Inspector.

**Comment by roman-sundurov** [comment]
Oh, sorry. I forgot to add I got this error on the native SwiftUI.
