### ISSUE TITLE
[🐛] Cannot call addAdEventListener on event of type GAMAdEventType - Throwing Error: GAMInterstitialAd.addAdEventListener(*) 'type' expected a valid event type value.

### ISSUE THREAD

**Issue by matganine** [invertase/react-native-google-mobile-ads#444]
### What happened?

Hi, 
I tried to call addAdEventListener on a GAMInterstitialAd for events of type GAMAdEventType.APP_EVENT. However, an error was thrown: 

"GAMInterstitialAd.addAdEventListener(*) 'type' expected a valid event type value."

After checking the source code, the issue is in the implementation of `_addAdEventListener`:

`  protected _addAdEventListener<T extends EventType>(type: T, listener: AdEventListener<T>) {
    if (
      !(
        isOneOf(type, Object.values(AdEventType)) ||
        (isOneOf(type, Object.values(RewardedAdEventType)) &&
          (this._type === 'rewarded' || this._type === 'rewarded_interstitial'))
      )
    ) {
      throw new Error(
        `${this._className}.addAdEventListener(*) 'type' expected a valid event type value.`,
      );
    }
    if (!isFunction(listener)) {
      throw new Error(
        `${this._className}.addAdEventListener(_, *) 'listener' expected a function.`,
      );
    }

    const id = this._adEventListenerId++;
    this._getAdEventListeners(type).set(id, listener);
    return () => {
      this._getAdEventListeners(type).delete(id);
    };
  }`

The filter is missing the type GAMAdEventType and the correct implementation should be:

`  protected _addAdEventListener<T extends EventType>(type: T, listener: AdEventListener<T>) {
    if (
      !(
        isOneOf(type, Object.values(AdEventType)) ||
        isOneOf(type, Object.values(GAMAdEventType)) ||
        (isOneOf(type, Object.values(RewardedAdEventType)) &&
          (this._type === 'rewarded' || this._type === 'rewarded_interstitial'))
      )
    ) {
      throw new Error(
        `${this._className}.addAdEventListener(*) 'type' expected a valid event type value.`,
      );
    }
    if (!isFunction(listener)) {
      throw new Error(
        `${this._className}.addAdEventListener(_, *) 'listener' expected a function.`,
      );
    }

    const id = this._adEventListenerId++;
    this._getAdEventListeners(type).set(id, listener);
    return () => {
      this._getAdEventListeners(type).delete(id);
    };
  }`

Would it be possible to fix this issue ? If necessary, I would gladly create a pull request for this fix

Thank you in advance!

### Platforms

Android and iOS

### React Native Info

```Shell
info Fetching system and libraries information...
System:
  OS: macOS 13.2
  CPU: (10) arm64 Apple M1 Max
  Memory: 331.25 MB / 32.00 GB
  Shell:
    version: 5.8.1
    path: /bin/zsh
Binaries:
  Node:
    version: 16.17.0
    path: ~/.nvm/versions/node/v16.17.0/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 8.15.0
    path: ~/.nvm/versions/node/v16.17.0/bin/npm
  Watchman:
    version: 2023.08.14.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.11.2
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.2
      - iOS 16.2
      - macOS 13.1
      - tvOS 16.1
      - watchOS 9.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2021.1 AI-211.7628.21.2111.8309675
  Xcode:
    version: 14.2/14C18
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.13
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Are your using Typescript?

- [X] My project is using Typescript

### package.json

```JSON
{
  "name": "AdmaxReactNative",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@react-native-community/picker": "^1.8.1",
    "react": "18.2.0",
    "react-native": "0.72.4",
    "react-native-gesture-handler": "^2.12.1",
    "react-native-google-mobile-ads": "^12.0.0",
    "react-native-permissions": "^3.8.4",
    "react-native-safe-area-context": "^4.7.1",
    "react-native-safe-area-view": "^1.1.1",
    "react-navigation": "^4.4.4",
    "react-navigation-stack": "^2.10.4"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/eslint-config": "^0.72.2",
    "@react-native/metro-config": "^0.72.11",
    "@tsconfig/react-native": "^3.0.0",
    "@types/react": "^18.0.24",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.2.1",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.76.8",
    "prettier": "^2.4.1",
    "react-test-renderer": "18.2.0",
    "typescript": "4.8.4"
  },
  "reactNativePermissionsIOS": [
    "AppTrackingTransparency",
    "BluetoothPeripheral",
    "Calendars",
    "Camera",
    "Contacts",
    "FaceID",
    "LocationAccuracy",
    "LocationAlways",
    "LocationWhenInUse",
    "MediaLibrary",
    "Microphone",
    "Motion",
    "Notifications",
    "PhotoLibrary",
    "PhotoLibraryAddOnly",
    "Reminders",
    "Siri",
    "SpeechRecognition",
    "StoreKit"
  ],
  "engines": {
    "node": ">=16"
  }
}
```

### app.json

```JSON
{
  "name": "AdmaxReactNative",
  "displayName": "AdmaxReactNative",
  "react-native-google-mobile-ads": {
    "android_app_id": "ca-app-pub-3549158951868469~5138751934",
    "ios_app_id": "ca-app-pub-3549158951868469~5138751934",
    "user_tracking_usage_description": "This identifier will be used to deliver personalized ads to you."
  }
}
```

**Comment by DoctorJohn** [comment]
Hi @matganine !

Yup, looks like the `GAMAdEventType` is missing from the check. The proposed solution seems to be correct.

> I would gladly create a pull request for this fix

I encourage you to do so! The maintainers of this repository are nice and PRs are welcome.
