### ISSUE TITLE
[🐛]AdMobMediation is supported?

### ISSUE THREAD

**Issue by burhanahmed92** [invertase/react-native-google-mobile-ads#445]
### What happened?

react-native-admob package supported the AdMobMediationTestSuite

Is there a way todo the ad mediation in this library.
Kindly guide how can i do that

### Platforms

Android and iOS

### React Native Info

```Shell
"react-native": "0.71.7",
```

### Are your using Typescript?

- [ ] My project is using Typescript

### package.json

```JSON
"dependencies": {
    "@expo/vector-icons": "^13.0.0",
    "@react-native-async-storage/async-storage": "1.17.11",
    "@react-native-community/blur": "^4.3.2",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-community/netinfo": "9.3.7",
    "@react-native-firebase/analytics": "^18.3.0",
    "@react-native-firebase/app": "^18.3.0",
    "@react-native-seoul/masonry-list": "^1.4.1",
    "@react-navigation/drawer": "^5.9.0",
    "@react-navigation/native": "^5.7.3",
    "@react-navigation/stack": "^5.9.0",
    "axios": "^1.4.0",
    "expo": "~48.0.15",
    "expo-build-properties": "~0.6.0",
    "expo-constants": "~14.2.1",
    "expo-device": "~5.2.1",
    "expo-document-picker": "~11.2.2",
    "expo-file-system": "~15.2.2",
    "expo-image-picker": "~14.1.1",
    "expo-linear-gradient": "^12.1.2",
    "expo-media-library": "~15.2.3",
    "expo-notifications": "~0.18.1",
    "expo-permissions": "~14.1.1",
    "expo-splash-screen": "~0.18.2",
    "expo-status-bar": "~1.4.4",
    "native-base": "^3.4.28",
    "react": "18.2.0",
    "react-native": "0.71.7",
    "react-native-document-picker": "^9.0.1",
    "react-native-dotenv": "^3.4.8",
    "react-native-gesture-handler": "^2.10.1",
    "react-native-google-mobile-ads": "^11.6.5",
    "react-native-masonry-list": "^2.16.1",
    "react-native-modalize": "^2.1.1",
    "react-native-pure-jwt": "^3.0.2",
    "react-native-reanimated": "~2.14.4",
    "react-native-safe-area-context": "4.4.1",
    "react-native-screens": "~3.20.0",
    "react-native-sensitive-info": "^5.5.8",
    "react-native-svg": "13.4.0",
    "react-native-swiper": "^1.6.0"
  },
```

### app.json

```JSON
"react-native-google-mobile-ads": {
    "android_app_id": "-", //My ad ID
    "ios_app_id": "-"//My ad ID
  }
```

**Comment by DoctorJohn** [comment]
Yes, you can use mediation. This library does not require any additional setup to work with mediation. Follow [the regular official guide](https://developers.google.com/admob/android/mediate) to get started.

**Comment by frederikocmr** [comment]
Hello, I would like to share that I succesfully implemented AdMob Mediation using React Native + Expo (prebuild).

Here's a checklist of what to do (code-wise):

- Update the Info.plist adding the SKAdNetworkItems keys (there are a lot) for iOS.
- Add AppLovinSDK and Chartboost input/output Paths to project.pbxproj for iOS.
- Adds Pods for ‘GoogleMobileAdsMediationAppLovin’,  ‘GoogleMobileAdsMediationChartboost’, ‘GoogleMobileAdsMediationFyber’, ‘GoogleMobileAdsMediationIronSource’ and ‘GoogleMobileAdsMediationFacebook’ on iOS.
- Add “applovin.sdk.key” metadata to AndroidManifest.xml on Android
- Add repositories { maven { url 'https://android-sdk.is.com/' } maven { url 'https://cboost.jfrog.io/artifactory/chartboost-ads/' } }   to build.gradle on Android
- Add implementations of applovin, facebook, ironsource, chartboost and fyber to build.gradle on Android

So for the tutorials, look for mediation for the following adapters:
- AppLovin
- ChartBoost
- IronSource
- Fyber
- Facebook

https://developers.google.com/admob/android/choose-networks
https://developers.google.com/admob/ios/choose-networks

**Comment by w3company-leo** [comment]
@frederikocmr 
Hi, Thanks for sharing information.

How can I do this???
```
Add AppLovinSDK and Chartboost input/output Paths to project.pbxproj for iOS.
```

**Comment by clementinoux** [comment]
@frederikocmr thanks for sharing your tips! Can you please confirm that you were able to make the bidding network operational (not only waterfall)? I still don't manage to fill ads on the bidding network except for admob ads... 
Thanks a lot!

**Comment by sly170816** [comment]
@clementinoux same issue. We don't manage to fill ads onthe bidding network except with AdMob ads. Did you manage to get successfull fills with Meta on iOS?

**Comment by clementinoux** [comment]
> @clementinoux same issue. We don't manage to fill ads onthe bidding network except with AdMob ads. Did you manage to get successfull fills with Meta on iOS?

@sly170816 

### 1) we did managed to make Meta bidding operational 

Some information that could be useful:  
- **Meta do not bid on Non-Personalized traffic**. In our setup of the inter / rewarded we had
`RewardedAd.createForAdRequest(adId, {
      requestNonPersonalizedAdsOnly: true
  })`
`InterstitialAd.createForAdRequest(adId, {
      requestNonPersonalizedAdsOnly: true
  })`
- Changing the boolean to `false` results to successful fills

### 2) but the level of ads Meta on actually binding is still super low
- For that issue I still don't have any hints

The solution I would recommend : migrate to another mediation platform
