### ISSUE TITLE
[🐛] test ads show perfectly , but in release apk and playstore app not show ads , my admob account is approved 

### ISSUE THREAD

**Issue by pradhyumansinh9849** [invertase/react-native-google-mobile-ads#449]
### What happened?

release apk not show ads 

### Platforms

Android, but have not tested behavior on iOS

### React Native Info

```Shell
OS: macOS 13.5.1
  CPU: (8) arm64 Apple M2
  Memory: 77.25 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 19.7.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.19
    path: ~/Documents/EXPOLEADGENERATORIOS/node_modules/.bin/yarn
  npm:
    version: 9.5.0
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.05.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK:
    Android NDK: 22.1.7171670
IDEs:
  Android Studio: 2022.1 AI-221.6008.13.2211.9619390
  Xcode:
    version: 14.3/14E222b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.18
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: 0.72.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Are your using Typescript?

- [ ] My project is using Typescript

### package.json

```JSON
"react-native-google-mobile-ads": "^11.7.0",
```

### app.json

```JSON
{
  "name": "EventLeads",
  "displayName": "EventLeads",
  "react-native-google-mobile-ads": {
    "ios_app_id": "ca-app-pub-6212321504438529~56985xxxxx",
    "android_app_id": "ca-app-pub-6212321504438529~77191xxxxx"
  }
}
```

**Comment by BaptistePro** [comment]
Hi @pradhyumansinh9849, I'm currently experiencing the same problem. Can you tell me if you've added Mediations to your ads in your Google admob account?

**Comment by fr3nzy** [comment]
I'm also experiencing the same problem.  test ads are working in debug mode, but in release apk and playstore, no ads are showing. My admob account is verified, my app is approved and ready to show ads, but admob is showing zero ads served.

**Comment by BaptistePro** [comment]
> I'm also experiencing the same problem. test ads are working in debug mode, but in release apk and playstore, no ads are showing. My admob account is verified, my app is approved and ready to show ads, but admob is showing zero ads served.

I'm working on it, but for the moment I don't have any solutions. If you have any news, please let me know.

**Comment by fr3nzy** [comment]
https://github.com/invertase/react-native-google-mobile-ads/issues/442#issuecomment-1785995457
