### ISSUE TITLE
[🐛] Bug Adaptive Banner - Can not show collapsible banner Ad

### ISSUE THREAD

**Issue by TVGSoft** [invertase/react-native-google-mobile-ads#460]
### What happened?

I want to display collapsible banner Ad with react native. However, it doesn't work similarly to Android native code.
![2023-09-24 00 41 34](https://github.com/invertase/react-native-google-mobile-ads/assets/20625911/03b01d45-9446-4dad-9d21-44b131186135)

This is my react native code, and it can not show a collapsible banner:
```typescript
<SafeAreaView style={{ flex: 1 }}>
      <View style={{ flex: 1 }}>
        <View
          style={{
            position: 'absolute',
            bottom: 0,
            width: '100%'
          }}>
          <BannerAd
            unitId="ca-app-pub-3940256099942544/9214589741"
            size={BannerAdSize.ANCHORED_ADAPTIVE_BANNER}
            requestOptions={{
              requestNonPersonalizedAdsOnly: true,
              networkExtras: {
                collapsible: 'bottom'
              }
            }}
          />
        </View>
      </View>
    </SafeAreaView>
``` 

This is my Android native code from repo: https://github.com/googleads/googleads-mobile-android-examples/tree/main/java/admanager/AdaptiveBannerExample
And I added network extra to "loadBanner" function:
```java
private void loadBanner(AdSize adSize) {
    // Create an ad request.
    adView = new AdManagerAdView(this);
    adView.setAdUnitId("ca-app-pub-3940256099942544/9214589741");
    adView.setBackgroundColor(getResources().getColor(android.R.color.holo_blue_light));
    adContainerView.removeAllViews();
    adContainerView.addView(adView);
    adView.setAdSizes(adSize);

    Bundle extras = new Bundle();
    extras.putString("collapsible", "bottom");

    AdRequest adRequest = new AdManagerAdRequest.Builder().addNetworkExtrasBundle(AdMobAdapter.class, extras).build();

    // Start loading the ad in the background.
    adView.loadAd(adRequest);
  }
```

### Platforms

Only on Android

### React Native Info

```Shell
info Fetching system and libraries information...
System:
    OS: macOS 13.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 22.15 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
    Watchman: 2023.07.24.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/giaptran/.rubies/ruby-3.1.2/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.10671973
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 12.0.1 - /usr/bin/javac
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.2.0 => 18.2.0 
    react-native: 0.70.4 => 0.70.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.72.4 is now available (your project is running on v0.70.4).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.72.4.
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.70.4.
info To upgrade, run "react-native upgrade".
```

### Are your using Typescript?

- [X] My project is using Typescript

### package.json

```JSON
{
  "name": "RNGoogleMobileAdsExample",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest",
    "prepare": "patch-package"
  },
  "dependencies": {
    "react": "18.2.0",
    "react-native": "0.72.2",
    "react-native-google-mobile-ads": "link:../"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.2",
    "@babel/runtime": "^7.20.0",
    "@react-native-community/eslint-config": "^3.2.0",
    "@tsconfig/react-native": "^2.0.2",
    "@types/jest": "^29.2.1",
    "@types/react": "^18.0.24",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.2.1",
    "detox": "^20.6.0",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "jest-circus": "^29.5.0",
    "jest-environment-node": "^29.5.0",
    "jet": "https://github.com/invertase/jet#@mikehardy/jet-next",
    "metro-react-native-babel-preset": "0.73.8",
    "mocha": "^10.2.0",
    "patch-package": "^8.0.0",
    "prettier": "^2.4.1",
    "react-test-renderer": "18.2.0",
    "typescript": "^5.0.2"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

### app.json

```JSON
{
  "name": "RNGoogleMobileAdsExample",
  "displayName": "RNGoogleMobileAdsExample",
  "react-native-google-mobile-ads": {
    "android_app_id": "ca-app-pub-3940256099942544~3347511713",
    "ios_app_id": "ca-app-pub-3940256099942544~1458002511",
    "delay_app_measurement_init": false,
    "optimize_initialization": true,
    "optimize_ad_loading": true,
    "user_tracking_usage_description": "This identifier will be used to deliver personalized ads to you.",
    "sk_ad_network_items": [
      "cstr6suwn9.skadnetwork",
      "4fzdc2evr5.skadnetwork",
      "4pfyvq9l8r.skadnetwork",
      "2fnua5tdw4.skadnetwork",
      "ydx93a7ass.skadnetwork",
      "5a6flpkh64.skadnetwork",
      "p78axxw29g.skadnetwork",
      "v72qych5uu.skadnetwork",
      "ludvb6z3bs.skadnetwork",
      "cp8zw746q7.skadnetwork",
      "c6k4g5qg8m.skadnetwork",
      "s39g8k73mm.skadnetwork",
      "3qy4746246.skadnetwork",
      "3sh42y64q3.skadnetwork",
      "f38h382jlk.skadnetwork",
      "hs6bdukanm.skadnetwork",
      "v4nxqhlyqp.skadnetwork",
      "wzmmz9fp6w.skadnetwork",
      "yclnxrl5pm.skadnetwork",
      "t38b2kh725.skadnetwork",
      "7ug5zh24hu.skadnetwork",
      "9rd848q2bz.skadnetwork",
      "y5ghdn5j9k.skadnetwork",
      "n6fk4nfna4.skadnetwork",
      "v9wttpbfk9.skadnetwork",
      "n38lu8286q.skadnetwork",
      "47vhws6wlr.skadnetwork",
      "kbd757ywx3.skadnetwork",
      "9t245vhmpl.skadnetwork",
      "a2p9lx4jpn.skadnetwork",
      "22mmun2rn5.skadnetwork",
      "4468km3ulz.skadnetwork",
      "2u9pt9hc89.skadnetwork",
      "8s468mfl3y.skadnetwork",
      "av6w8kgt66.skadnetwork",
      "klf5c3l5u5.skadnetwork",
      "ppxm28t8ap.skadnetwork",
      "424m5254lk.skadnetwork",
      "ecpz2srf59.skadnetwork",
      "uw77j35x4d.skadnetwork",
      "mlmmfzh3r3.skadnetwork",
      "578prtvx9j.skadnetwork",
      "4dzt52r2t5.skadnetwork",
      "gta9lk7p23.skadnetwork",
      "e5fvkxwrpn.skadnetwork",
      "8c4e2ghe7u.skadnetwork",
      "zq492l623r.skadnetwork",
      "3rd42ekr43.skadnetwork",
      "3qcr597p9d.skadnetwork"
    ]
  }
}
```

**Comment by TVGSoft** [comment]
I'm able to find out when change the "initAdView" function to:
```java
Activity currentActivity = ((ReactContext) reactViewGroup.getContext()).getCurrentActivity();
      if (currentActivity != null) {
        adView = new AdView(currentActivity);
      } else {
        adView = new AdView(reactViewGroup.getContext());
      }
``` 

With AdView constructor parameter is current activity then It will able to show collapsible banner, but only when I resume the activity from background. The correct behavior, it should show the collapsible banner after activity created.

https://github.com/invertase/react-native-google-mobile-ads/assets/20625911/b3b69e4f-8185-422b-836e-f233666e7e83

And it happened a bug the banner can not display content after click on close button as video attached.

**Comment by dylancom** [comment]
Are there any official docs about this collapsible banner?

**Comment by TVGSoft** [comment]
@dylancom Currently, No official docs from Google related this. But they inform us if we add above network extra request then it will display accordingly.

**Comment by dylancom** [comment]
Keep in mind that this is a community effort to make the google mobile ads sdk available to React Native.
If there are no docs for experimental stuff available there isn't much we can do.
Feel free to submit a PR.

**Comment by thanhtrung0301** [comment]
@TVGSoft  I add this line to event onAdLoaded and onAdClosed to:
 ```
      @Override
          public void onAdLoaded() {
            // call displayAds to refresh ads
            WritableMap payload = displayAds(reactViewGroup, adView);
            sendEvent(reactViewGroup, EVENT_AD_LOADED, payload);
          }
```
```
       @Override
          public void onAdClosed() {
            // Danh added: call displayAds to refresh ads
            WritableMap payload = displayAds(reactViewGroup, adView);
            sendEvent(reactViewGroup, EVENT_AD_CLOSED, null);
          }
```
And:
```Java
 WritableMap payload = Arguments.createMap();
    payload.putDouble("width", PixelUtil.toDIPFromPixel(width));
    payload.putDouble("height", PixelUtil.toDIPFromPixel(height));
    // Ref: Collapsible banner ads are only available for Google demand during the beta period. Ads served through mediation show as normal, non-collapsible banner ads.
    BaseAdView oldAdView = getAdView(reactViewGroup);
    if (oldAdView != null) {
      reactViewGroup.removeView(oldAdView);
      reactViewGroup.addView(adView);
    }
```
to resolve above issues.

**Comment by dylancom** [comment]
@TVGSoft have you been able to solve it? Our demo app works well on iOS, but notice some issues on Android.

**Comment by TaylorDale** [comment]
Am I missing something here - I've added 

```
networkExtras: {
    collapsible: 'bottom',
  },
```

To the requestOptions,  not getting any behaviour change on iOS or android. Package ver 12.6.0

**Comment by dylancom** [comment]
Make sure that you are using an Adaptive banner test id, not a normal banner test id. On Android it doesn't seem to work yet though...

**Comment by TaylorDale** [comment]
Here's where I am at (Android, using the adaptive banner test ID): 

No matter what I do, I am getting this exact issue:
https://groups.google.com/g/google-admob-ads-sdk/c/RMETruwLECc

IE: What appears to potentially be a collapsible ad (Has a collapse button you can press on the right hand side) is just a normal size banner ad. I can press the collapse button and the collapse button disappears. Solution in that link was to pass the correct activity to the SDK but I believe that's already being done here.

**Comment by TaylorDale** [comment]
> Please test our demo app on iOS. It has a working collapsible banner ad :)

Hmm... no luck for me. Compiled the example from the 12.6.0 commit, to no avail. Also behaving the same way in all of my apps when implemented. Any ideas?

![image](https://github.com/invertase/react-native-google-mobile-ads/assets/5500716/6f3f9b84-20d3-4ecc-aff0-7e661c59f40b)

**Comment by dylancom** [comment]
Have you tried to go back and forth a couple of times? I notice it sometimes doesn't return a collapsible banner...
But if it does:
<img width="511" alt="Scherm­afbeelding 2023-12-12 om 10 58 24" src="https://github.com/invertase/react-native-google-mobile-ads/assets/12894112/70fb242a-a87f-4a7a-ad0a-0cc781e3bd24">

**Comment by TaylorDale** [comment]
OK so I just tried it on simulator iPad iOS 16.4, first load you're right I get a standard banner, second load I get something that *looks like* it could be a collapsible banner - however, it is a regular sized banner just with a non-functional hovering "Expand/collapse" icon

![image (1)](https://github.com/invertase/react-native-google-mobile-ads/assets/5500716/f5aa774e-ac72-4bbf-bc40-f846c2e1b906)

Something to note, if I click and drag the banner area it "clips" as if the banner's parent container is the same size as the banner itself, not the whole screen. Not sure if that would cause some sort of issue with layout?

**Comment by TaylorDale** [comment]
> Haven't tested it on iPad, but could indeed be a clipping parent container. Feel free to submit a PR and improve our demo :)

I don't have iOS14/8Plus simulator but I just ran it on iPhone15/ios17 sim and I also got the same result there, after extending the parent container so it can't be something outside the <Banner> component clipping it... not sure what else to test at this stage. Would be great if a 3rd party could confirm/deny?

**Comment by haresh4d** [comment]
Hello All,

I am facing this issue in android. Collapsible Banner is initially not exapnded but gets expanded after some refocus event on the screen.

**Comment by haresh4d** [comment]
is there anybody who is still facing this issue?

**Comment by haresh4d** [comment]
Any solution to this?
