### ISSUE TITLE
[📚] Documentation Issue - Upgrade path from 6.0 -> current

### ISSUE THREAD

**Issue by sdb1228** [invertase/react-native-google-mobile-ads#464]
### Documentation Feedback

Hello! Is there some documentation around updating from 6.1 -> current.  Everytime I get around version 9 I get the error below and I am sure its because I haven't been updating the package.  Would love to know how to update to current!

There is no XCFramework found at '/Users/stevenburnett/projects/NoExpoPrettyRandom/ios/Pods/Google-Mobile-Ads-SDK/Frameworks/GoogleMobileAdsFramework-Current/GoogleMobileAds.xcframework'.

**Comment by dylancom** [comment]
Clearly an issue with updating your pods.
