### ISSUE TITLE
[📚] Connecting Google Ad Manager

### ISSUE THREAD

**Issue by MicahDavid** [invertase/react-native-google-mobile-ads#469]
### Documentation Feedback

I don't see any documentation on how to connect Google Ad Manager. I see how you can add the Google Ad Manager banner, referencing the ad unit id from Ad Manager, but not connect to the Ad Manager account itself. Am I missing something?  Is there are auto connection through Ad Mob?

**Comment by focux** [comment]
Did you find out how to connect it?

**Comment by MicahDavid** [comment]
I did not figure how to connect Ad Manager.  I had to go around Ad Manager for managing ads on react-native. I just use Ad Mob, and for my direct sales ad campaigns and have to add them to Ad Manager for web, and then create another campaign for native on Ad Mob.
