### ISSUE TITLE
[🐛] ads:compileDebugKotlin Error 

### ISSUE THREAD

**Issue by cnahmetcn** [invertase/react-native-google-mobile-ads#480]
### What happened?

I installed the plugin, but when I run it, I get the error Execution failed for task ':react-native-google-mobile-ads:compileDebugKotlin'. I also added the following blocks to the plugin's build.gradle file.
compileOptions {
     sourceCompatibility = '1.8'
     targetCompatibility = '1.8'
}
kotlinOptions {
     jvmTarget = '1.8'
}
However, I get the error compileSdkVersion is not specified. Please add it to build.gradle gave error. I added compileSdkVersion 33 but I still get the same error. I cannot display the ad at all. My app is not working.

In general, all the errors I get when I make some changes are;

1. Execution failed for task ':react-native-google-mobile-ads:compileDebugKotlin'
2. compileSdkVersion is not specified
3. turbomoduleregistry.getenforcing(...) 'rngooglempbileadsmobile' could not be found
4. Plugin with id 'com.google.gms.google-services' not found.

### Platforms

Only on Android

### React Native Info

```Shell
System:
  OS: macOS 14.1
  CPU: (8) arm64 Apple M2
  Memory: 723.80 MB / 24.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.8.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 10.1.0
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.09.18.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.13.0
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10811636
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.18
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.5
    wanted: 0.72.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Are your using Typescript?

- [ ] My project is using Typescript

### package.json

```JSON
{
  "name": "mani",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.19.3",
    "@react-native-picker/picker": "^2.5.1",
    "@react-navigation/bottom-tabs": "^6.5.8",
    "@react-navigation/drawer": "^6.6.3",
    "@react-navigation/material-bottom-tabs": "^6.2.17",
    "@react-navigation/native": "^6.1.7",
    "@react-navigation/native-stack": "^6.9.13",
    "@react-navigation/stack": "^6.3.17s",
    "axios": "^1.5.1",
    "cheerio": "^1.0.0-rc.12",
    "lottie-react-native": "^6.3.1",
    "metro-config": "^0.77.0",
    "react": "18.2.0",
    "react-native": "0.72.5",
    "react-native-dropdown-picker": "^5.4.6",
    "react-native-gesture-handler": "^2.12.0",
    "react-native-google-mobile-ads": "^12.3.0",
    "react-native-paper": "^5.10.6",
    "react-native-picker-select": "^8.1.0",
    "react-native-reanimated": "^3.3.0",
    "react-native-safe-area-context": "^4.7.0",
    "react-native-screens": "^3.22.1",
    "react-native-vector-icons": "^10.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/eslint-config": "^0.72.2",
    "@react-native/metro-config": "^0.72.11",
    "@tsconfig/react-native": "^3.0.0",
    "@types/react": "^18.0.24",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.2.1",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.76.8",
    "prettier": "^2.4.1",
    "react-test-renderer": "18.2.0",
    "typescript": "4.8.4"
  },
  "engines": {
    "node": ">=16"
  }
}
```

### app.json

```JSON
{
  "name": "mani",
  "displayName": "mani",
  "react-native-google-mobile-ads": {
    "android_app_id": "ca-app-pub-1416813895909014~6413025833",
    "ios_app_id": "ca-app-pub-1416813895909014~6413025833"
  }
}
```

### android/build.gradle

```Groovy
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33
        kotlinVersion = "1.9.0"

        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
    }
    repositories {
        google()
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.0"
    }
}
```

### android/app/build.gradle

```Groovy
apply plugin: "com.android.application"
apply plugin: "com.facebook.react"


project.ext.vectoricons = [
    iconFontNames: [ 'MaterialCommunityIcons.ttf', 'FontAwesome.ttf' ] // Name of the font files you want to copy
]

apply from: file("../../node_modules/react-native-vector-icons/fonts.gradle");


/**
 * This is the configuration block to customize your React Native Android app.
 * By default you don't need to apply any configuration, just uncomment the lines you need.
 */
react {
    /* Folders */
    //   The root of your project, i.e. where "package.json" lives. Default is '..'
    // root = file("../")
    //   The folder where the react-native NPM package is. Default is ../node_modules/react-native
    // reactNativeDir = file("../node_modules/react-native")
    //   The folder where the react-native Codegen package is. Default is ../node_modules/@react-native/codegen
    // codegenDir = file("../node_modules/@react-native/codegen")
    //   The cli.js file which is the React Native CLI entrypoint. Default is ../node_modules/react-native/cli.js
    // cliFile = file("../node_modules/react-native/cli.js")

    /* Variants */
    //   The list of variants to that are debuggable. For those we're going to
    //   skip the bundling of the JS bundle and the assets. By default is just 'debug'.
    //   If you add flavors like lite, prod, etc. you'll have to list your debuggableVariants.
    // debuggableVariants = ["liteDebug", "prodDebug"]

    /* Bundling */
    //   A list containing the node command and its flags. Default is just 'node'.
    // nodeExecutableAndArgs = ["node"]
    //
    //   The command to run when bundling. By default is 'bundle'
    // bundleCommand = "ram-bundle"
    //
    //   The path to the CLI configuration file. Default is empty.
    // bundleConfig = file(../rn-cli.config.js)
    //
    //   The name of the generated asset file containing your JS bundle
    // bundleAssetName = "MyApplication.android.bundle"
    //
    //   The entry file for bundle generation. Default is 'index.android.js' or 'index.js'
    // entryFile = file("../js/MyApplication.android.js")
    //
    //   A list of extra flags to pass to the 'bundle' commands.
    //   See https://github.com/react-native-community/cli/blob/main/docs/commands.md#bundle
    // extraPackagerArgs = []

    /* Hermes Commands */
    //   The hermes compiler command to run. By default it is 'hermesc'
    // hermesCommand = "$rootDir/my-custom-hermesc/bin/hermesc"
    //
    //   The list of flags to pass to the Hermes compiler. By default is "-O", "-output-source-map"
    // hermesFlags = ["-O", "-output-source-map"]
}

/**
 * Set this to true to Run Proguard on Release builds to minify the Java bytecode.
 */
def enableProguardInReleaseBuilds = false

/**
 * The preferred build flavor of JavaScriptCore (JSC)
 *
 * For example, to use the international variant, you can use:
 * `def jscFlavor = 'org.webkit:android-jsc-intl:+'`
 *
 * The international variant includes ICU i18n library and necessary data
 * allowing to use e.g. `Date.toLocaleString` and `String.localeCompare` that
 * give correct results when using with locales other than en-US. Note that
 * this variant is about 6MiB larger per architecture than default.
 */
def jscFlavor = 'org.webkit:android-jsc:+'

android {
    ndkVersion rootProject.ext.ndkVersion

    compileSdkVersion rootProject.ext.compileSdkVersion

    namespace "com.mani"
    defaultConfig {
        applicationId "com.mani"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
    }
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
}

dependencies {
    // The version of react-native is set by the React Native Gradle Plugin
    implementation("com.facebook.react:react-android")

    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}")
    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.squareup.okhttp3', module:'okhttp'
    }

    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}")
    if (hermesEnabled.toBoolean()) {
        implementation("com.facebook.react:hermes-android")
    } else {
        implementation jscFlavor
    }
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
```

### android/settings.gradle

```Groovy
rootProject.name = 'mani'
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':app'
includeBuild('../node_modules/@react-native/gradle-plugin')
```

### AndroidManifest.xml

```XML
<manifest xmlns:android="http://schemas.android.com/apk/res/android">

    <uses-permission android:name="android.permission.INTERNET" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|screenSize|smallestScreenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize"
        android:exported="true">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
    </application>
</manifest>
```

**Comment by mikehardy** [comment]
With apologies, something is wrong with your local native java setup and I won't have time to help debug it

I recommend you prove things *can* work by doing a `npx react-native init TestApp` in a temporary directory and test-integrating react-native-google-mobile-ads. Our example refresh script does that exact thing and I just tested it today. It works fine, so this is a local integration for you and won't cause a change in the repo here, so it is not actionable here

https://github.com/invertase/react-native-google-mobile-ads/blob/main/refresh-example.sh

**Comment by cnahmetcn** [comment]
> With apologies, something is wrong with your local native java setup and I won't have time to help debug it
> 
> I recommend you prove things _can_ work by doing a `npx react-native init TestApp` in a temporary directory and test-integrating react-native-google-mobile-ads. Our example refresh script does that exact thing and I just tested it today. It works fine, so this is a local integration for you and won't cause a change in the repo here, so it is not actionable here
> 
> https://github.com/invertase/react-native-google-mobile-ads/blob/main/refresh-example.sh

If I create a fresh application and install this plugin, it shows ads. However, if I add a few more plugins, it doesn't work. Shouldn't it give errors in those applications too?

**Comment by mikehardy** [comment]
What I heard was "your module works great, but there are problems with other plugins"
That is, it is not actionable in this repository, and you should pursue solutions in those other repositories.

**Comment by cnahmetcn** [comment]
Ok. I'll try. Thank you

**Comment by jihokim2** [comment]
I discovered   kotlinVersion = "1.9.X" not worked. Only In KotlinVersion = "1.8.X" If you want to work, you could change 1.8.X @mikehardy Can you help us?

**Comment by mikehardy** [comment]
Is there some feature in kotlin 1.9.x you need right now? Is there some PR you would propose?

**Comment by jihokim2** [comment]
I just discovered this. But I don't know reason yet.

**Comment by cnahmetcn** [comment]
Yes. For react-native-gesture-handler, I had to use the kotlin version in build.gradle. That's why I used version 1.9, but react-native-google-mobile-ads was using 1.8, so I downgraded the version and it worked.

**Comment by CaptainHaider** [comment]
buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33
        kotlinVersion = "1.8.22"
        ndkVersion = "23.1.7779620"
        googlePlayServicesAuthVersion = "19.2.0"
        
      I still see same error, not sure what I am doing wrong. Can someone please help?

**Comment by furkanuzundev** [comment]
Here is how i fixed the problem:
1 - Update the `kotlinVersion` from **android/build.gradle** to `1.9.21`
2 - Navigate to the `/android` folder and run ./gradlew clean
3 - Uninstall the app from **emulator**
4 - Then run `npx react-native run-android`

**Comment by pckz** [comment]
thanks @furkanuzundev !

**Comment by Samuel-Fipps** [comment]
I am also running into this issue. This seems to be a common issue as I have found multiple people posting about this. 
This no longer seems to work, " Update the kotlinVersion from android/build.gradle to 1.9.21" What version are you using? For the app? @furkanuzundev

**Comment by Samuel-Fipps** [comment]
downgrading to "    "react-native-google-mobile-ads": "14.7.2",
fixed the issue.

**Comment by mikehardy** [comment]
@Samuel-Fipps and yet our example, which is built programmatically, works fine.

Script that builds it: https://github.com/invertase/react-native-google-mobile-ads/blob/main/refresh-example.sh

Example https://github.com/invertase/react-native-google-mobile-ads/tree/main/RNGoogleMobileAdsExample

**Comment by Samuel-Fipps** [comment]
@mikehardy i don't doubt it does, but I had a kotlinVersion that was incompatible 1.8.0, and 1.9.21. For 1.9.21 to work i needed to downgrade to "react-native-google-mobile-ads": "14.7.2"

I probably could have updated my kotlinVersion, but I didn't know if that would cause issues with other libs.

**Comment by mikehardy** [comment]
Looks like 1.9.24 works 🤷 

https://github.com/search?q=repo%3Ainvertase%2Freact-native-google-mobile-ads%20kotlinVersion&type=code

I dunno - specifying a kotlinVersion that we require is a bit fiddly and it's something else to keep track of. 

All I know is the typical thing I do when I run into a problem "Okay, let's update everything to current versions before logging an issue or making a PR anywhere" seems like it would result in things working

**Comment by amresh-singh-qbs** [comment]
> downgrading to " "react-native-google-mobile-ads": "14.7.2", fixed the issue.

This works for me 
Thanks @Samuel-Fipps

**Comment by summerkiflain** [comment]
Only thing that worked for me downgrading to 14.7.2, I tried all the above mentioned `kotlinVersion`s.

**Comment by alejandroacho** [comment]
This worked for me:
1 - Update the `kotlinVersion` from `android/build.gradle` to `1.9.21`
2 - Set the `react-native-google-mobile-ads` version to `14.7.2`
3 - Reinstall dependencies with `npm i`
4 - Navigate to the `/android` folder and run `./gradlew clean`
5 - Uninstall the app from emulator
6 - Then run `expo start -c --android`

**Comment by mikehardy** [comment]
@alejandroacho glad you are unblocked, however recommending anything other than the current version here - which is v14.8.1 right now - is not a great solution as it leaves people stuck on an old version.

We need solutions that work for everyone on current versions if possible

**Comment by luiz-vinholi** [comment]
> downgrading to " "react-native-google-mobile-ads": "14.7.2", fixed the issue.

thank you, man! Your comment was my salvation.
