### ISSUE TITLE
[🐛] Does it support dynamic app IDs?

### ISSUE THREAD

**Issue by achigo16** [invertase/react-native-google-mobile-ads#490]
### What happened?

Hello,
The app I'm currently working on has various product flavors corresponding to different countries. This means my app will have more than one `app_id`. However, based on the documentation, it seems that the `app_id` can only be filled in the `app.json`.

So, does it support dynamic app IDs, or is there a possibility to make it dynamic?

### Platforms

Android and iOS

### React Native Info

```Shell
N/A
```

### Are your using Typescript?

- [ ] My project is using Typescript

### package.json

```JSON
N/A
```

### app.json

```JSON
N/A
```

### ios/Podfile

```Ruby
N/A
```

### android/build.gradle

```Groovy
N/A
```

### android/app/build.gradle

```Groovy
N/A
```

### android/settings.gradle

```Groovy
N/A
```

### AndroidManifest.xml

```XML
N/A
```

**Comment by mikehardy** [comment]
The app id is pushed in to your app's Info.plist (iOS) or android/app/src/main/res xml files at build time using a build phase to run a shell script (iOS) or some groovy (android) that turns the values in app.json into the necessary things.

There is no provision in those items for multiple project ids, that I'm aware of, and it seems like you've read the code and come to the same conclusion.

It sounds like for a case like this you may want to either extend the shell script / groovy build time infrastructure to maybe allow it to be per-flavor (that is: parameterize it a little bit such that the default is current behavior, but if it gets parameters then maybe it does a dictionary lookup for app id by flavor name?) or you just want to override that in your project somehow and manually handle your plist / res-xml values

This isn't something anyone has needed in a couple years so I understand that your project needs it but it is objectively a low-usage / niche feature - so you'll have to figure out how to make it work and propose a PR if it makes sense

**Comment by achigo16** [comment]
So, just to clarify, is it still possible to do so? For instance, by placing the `app_id` on per-flavor `android/app/build.gradle` for Android and in the `info.plist` for iOS

**Comment by mikehardy** [comment]
You can - I think - ignore the app.json key/value pairs we helpfully push into the native files for the majority use case and do anything you need to do at the native level. Which is basically a "yes" - you should be able to put things directly in there. Try it and see

**Comment by achigo16** [comment]
Just as an update for this ticket, after several checks and code tests, I've discovered a method to make the app_id dynamic. Just like mention before, shell script (iOS) or groovy (android) pushed app_id into info.plist (iOS) or AndroidManifet.xml (android), So, to ensure it's dynamic, I just directly placed the app_id in the info.plist and AndroidManifest.xml of the main project.

Here some example:

info.plist (iOS)
```
<key>GADApplicationIdentifier</key>
<string>ca-app-pub-xxxx/string>
```

AndroidManifet.xml (android)
```
<meta-data
    tools:replace="android:value"
    android:name="com.google.android.gms.ads.APPLICATION_ID"
    android:value="ca-app-pub-xxxx"/>
```

When I tested it several times, I didn't encounter any issues. But what do you think @mikehardy? are there any possible issue on future when i used this method?

Note:
In the AndroidManifest.xml (android) file, I added `tools:replace="android:value"` to prevent duplication issues with the AndroidManifest.xml in the library.

**Comment by mikehardy** [comment]
I cannot guarantee there will never be issues in the future, but just directly manipulating the IDs in the native file is how the native SDKs direct you to do it in their upstream manuals, so it should work fine.

**Comment by huythao99** [comment]
@achigo16 Can you describe in detail how to do it? I don't understand, if you just add it to the Manifest or Info.plist, it's still a static id

**Comment by achigo16** [comment]
Hi @huythao99, sorry for the late reply. 

What I'm doing is creating multiple info.plist files for each different build (for example, 'A info.plist' for build A, 'B info.plist' for build B, etc.). For each info.plist, I just add the key `GADApplicationIdentifier` with a different value. On the Android side, I'm using `productFlavors` in app/build.gradle and I add the app_id to `manifestPlaceholders`. I think you need to check how to use multiple info.plist files and how to use `manifestPlaceholders` first. 

Hopefully, this can help you!
