### ISSUE TITLE
How to handle EEA & non-EEA user ad requests?

### ISSUE THREAD

**Issue by lachtos** [invertase/react-native-google-mobile-ads#514]
### What happened?

According to some answers I found, we are not allowed to request admob ads for users in EEA who are under the age of consent (because to be able to request an admob ad, user must consent to at least one particular option, and users under 16 cannot be shown consent form, therefore they cannot consent).
What is the correct way to differentiate between EEA and non-EEA users?
Or is it ok to request ads for ALL users and let google handle the checks?
This is really confusing.

### Platforms

Android and iOS

### React Native Info

```Shell
.
```

### Are your using Typescript?

- [ ] My project is using Typescript

### package.json

```JSON
.
```

### app.json

```JSON
.
```

**Comment by lachtos** [comment]
One silly workaround I found is to do it like so:
1. Make sure ATT message is turned off in Admob and handle the ATT message manually.
2. Even if you know the user is under the age of consent, first run the `requestInfoUpdate` without the `tagForUnderAgeOfConsent` flag and check if `privacyOptionsRequirementStatus` is `REQUIRED`. This tells us that the user must be shown the consent form, therefore we _deduce_ that the user is in EEA.
```js
const isEEA = (await AdsConsent.requestInfoUpdate()).privacyOptionsRequirementStatus === AdsConsentStatus.REQUIRED;
```
3. Now we can store the `isEEA` for future use and run `requestInfoUpdate` again, this time with full config.
```js
const consentInfo = await AdsConsent.requestInfoUpdate({ ...config });
```
4. If the user is `in EEA && under the age of consent` OR `not in EEA && any age` this will result in `consentInfo.privacyOptionsRequirementStatus` being `NOT_REQUIRED`. We can request ads only for the latter, so now we use the previously stored `isEEA` to differentiate.

Turning the ATT message on would screw this process up, and possibly in the future other things also will. Is this really the only way?

**Comment by dylancom** [comment]
I just made a PR to add a getGdprApplies method. To understand if youre in EEA. This might help?

**Comment by lachtos** [comment]
> I just made a PR to add a getGdprApplies method. To understand if youre in EEA. This might help?

Thank you, @dylancom 
This seems to be the correct and more robust solution

**Comment by lachtos** [comment]
Unfortunately it looks like the `IABTCF_gdprApplies` value is 0 when `tagForUnderAgeOfConsent` is `true`.
I guess there is not much the library can do then.

**Comment by dylancom** [comment]
You need to make sure to call requestinfoupdate before getting gdprApplies.

**Comment by lachtos** [comment]
> You need to make sure to call requestinfoupdate before getting gdprApplies.


```js
await AdsConsent.requestInfoUpdate();
await AdsConsent.getGdprApplies(); // === true
```

```js
await AdsConsent.requestInfoUpdate({
  tagForUnderAgeOfConsent: true
});
await AdsConsent.getGdprApplies(); // === false
```

**Comment by pritish-thub** [comment]
You can also check [this](https://www.youtube.com/watch?v=eBnmULH250M)
