### ISSUE TITLE
Adaptive banner for large banner (320x100)

### ISSUE THREAD

**Issue by MicahDavid** [invertase/react-native-google-mobile-ads#535]
### Documentation Feedback

It looks to me that the adaptive banner or fluid banner are only available for the 320x50 ad size. I would really like to make a 320x100 be dynamically sized to full screen width.  How can we make this possible?

**Comment by jaure96** [comment]
You can try this:
```
const windowWidth = Math.round(Dimensions.get('screen').width)
...
...
...
<BannerAd
  size={`${windowWidth}x50`}
  unitId={YOUR_ID}
/>
```

**Comment by MicahDavid** [comment]
@jaure96 thanks for the suggestion, but the size has to match the size in AdMob/Ad Manager or the ad won't be returned.

**Comment by BrodaNoel** [comment]
@MicahDavid have you found a way to fix it?
I'm also trying custom heights and ads are not shown.

**Comment by MicahDavid** [comment]
> @MicahDavid have you found a way to fix it? I'm also trying custom heights and ads are not shown.

I am currently serving my ads through the Google Ad Manager, not through Ad Mob.  And through Ad Manager, there is still an issue serving FLUID ads on Android. 

The FLUID banner is intended to allow for full width banners, and this works for iOS, but unfortunately this doesn't work on Android.  The roundabout way that I am handling this for Android is I am creating many banner sizes for the popular screen dimensions and then specifying the exact banner size (ie. 404x106). It sure would be nice if the FLUID banners would work as they were intended to and I didn't have to great lengths to create the full width banners.

**Comment by BrodaNoel** [comment]
@MicahDavid update the library. As far as I remember, the fluid problem in manager, got fixed in the last version

**Comment by MicahDavid** [comment]
> @MicahDavid update the library. As far as I remember, the fluid problem in manager, got fixed in the last version

Works for iOS, not for Android.
