### ISSUE TITLE
[Feature Request] Support the max height option for inline adaptive banners

### ISSUE THREAD

**Issue by markwilcox** [invertase/react-native-google-mobile-ads#541]
### What happened?

Inline adaptive banners are designed for scrolling content. If that content is a feed with fairly consistent cell sizes then the larger sizes of banner available can be terrible for the UX.

The native SDKs support a method to get an inline adaptive banner with a width and max height (rather than just a width) but we can't access this through the React Native SDK.

The standard banners don't work so well in a feed in practice because they always take up their fixed height while loading and the API doesn't provide any feedback on loading unless it fails.

It would be ideal if the `BannerAd` component could take an optional max height that if supplied for an inline adaptive banner would cause the alternative native SDK method to be used and restrict the height. :pray:

### Platforms

Android and iOS

### React Native Info

```Shell
All recent versions
```

### Are your using Typescript?

- [ ] My project is using Typescript

### package.json

```JSON
n/a
```

### app.json

```JSON
n/a
```

**Comment by aybabtu1337** [comment]
We would be happy to review and accept a Pull Request to make this happen!
