### ISSUE TITLE
[📚] Should we also follow the instructions written in admob website when using this library?

### ISSUE THREAD

**Issue by burakkbilginn** [invertase/react-native-google-mobile-ads#573]
### Documentation Feedback

Should we also make the steps written in admob website when using this library?  I mean adding initialization on MainActivity file, adding meta tag in AndroidManifest file etc, as seen on the screenshot I attached. This is not written in the docs, therefore I am asking, thx.

![ss](https://github.com/invertase/react-native-google-mobile-ads/assets/59078874/a968045a-2e52-453c-af0d-d2a00e077415)

**Comment by dylancom** [comment]
No, this library does those things for you.
