### ISSUE TITLE
[🐛] Does not work with RN@0.74, iOS, new arch, bridgeless

### ISSUE THREAD

**Issue by birdofpreyru** [invertase/react-native-google-mobile-ads#575]
### What happened?

![screenshot](https://github.com/invertase/react-native-google-mobile-ads/assets/20144632/808aa37b-dc97-472a-8ed9-10671574cd8b)

### Platforms

Only on iOS

### React Native Info

```Shell
N/A
```

### Are your using Typescript?

- [ ] My project is using Typescript

### package.json

```JSON
N/A
```

### app.json

```JSON
N/A
```

**Comment by dylancom** [comment]
Looks like a duplicate of #532

**Comment by birdofpreyru** [comment]
I'll re-open it for now &mdash; the patch in #532 does solve the problem, but it wasn't applied to the library, with the expectation that the problem will be solved on React Native side in the next RN release. Thus, keeping the issue open, to be visible for anybody encountering the same issue.

**Comment by wired87** [comment]
Any updates since yesterday? :D 

What was the latest version that worked for you?

**Comment by birdofpreyru** [comment]
Not stale. I'll double-check, if it is resolved with the latest RN version, and close the issue if it is.

**Comment by birdofpreyru** [comment]
Tested, the issue is not resolved in RN v0.74.2, the patch is still necessary.
