### ISSUE TITLE
[🐛] MobileAds.setAppVolume and MobileAds.setAppMuted

### ISSUE THREAD

**Issue by tominou** [invertase/react-native-google-mobile-ads#580]
### What happened?

Hi,

Is it possible to use MobileAds.setAppVolume and MobileAds.setAppMuted ?

Thank you in advance

### Platforms

Android and iOS

### React Native Info

```Shell
Not important
```

### Are your using Typescript?

- [ ] My project is using Typescript

### package.json

```JSON
Not important
```

### app.json

```JSON
Not important
```

**Comment by dylancom** [comment]
Currently not included in this lib. Feel free to submit a PR and adding this feature to the lib.
Especially nowadays with ChatGPT etc. it's very easy if you're not used to the native code :).
