### ISSUE TITLE
[📚] Google ad mob with Meta Audiance Network

### ISSUE THREAD

**Issue by vishalsohani27** [invertase/react-native-google-mobile-ads#585]
### Documentation Feedback

Hello, Google ad mob is working fine. But i want to use Meta Audiance Network with Google Ad mob. I will use Google Admob as mediation partner for Meta.
I mapped all placement ids of Meta with Admob account.
But Meta platform is showing ideal (No request)
Is This library is compatibal to show Meta ads using Google admob?
Do i have to make some additional setting?
I Appriciate your Help and suggestion. Thanks in Advance.

**Comment by priyanshu2000** [comment]
> ### Documentation Feedback
> Hello, Google ad mob is working fine. But i want to use Meta Audiance Network with Google Ad mob. I will use Google Admob as mediation partner for Meta. I mapped all placement ids of Meta with Admob account. But Meta platform is showing ideal (No request) Is This library is compatibal to show Meta ads using Google admob? Do i have to make some additional setting? I Appriciate your Help and suggestion. Thanks in Advance.

Hey @vishalsohani27  were you able to make it work?

**Comment by vishalsohani27** [comment]
No Dear, still not working,  Meta Audience Network still showing no Data.
Even Google ad mob is also not showing any request from Mediation partner
Meta.
I think there is something missing, like the adapter version (I may be
Wrong). or this library is only for Admob Not for mediation.
I am expecting someone to clear this...

**Comment by dylancom** [comment]
This is just a wrapper around the Google Mobile Ads SDK, and just a community effort :)
If you want to add mediation partners you have to check their websites how to integrate their SDK.
You probably need to install extra pods.

**Comment by vishalsohani27** [comment]
ok Thank You. But wish this pack support mediation also.😊

**Comment by dylancom** [comment]
Feel free to submit a PR to add extra functionality as the rest of the community does :)
