### ISSUE TITLE
[📚] Expo configuration for SDK 51

### ISSUE THREAD

**Issue by raul-potor** [invertase/react-native-google-mobile-ads#588]
### Documentation Feedback

Hello,

Today I was upgrading my project from Expo SDK 50 to Expo SDK 51, and I had a warning in the console:

```
Warning: Root-level "expo" object found. Ignoring extra key in Expo config: "react-native-google-mobile-ads"
```
This warning was not present on SDK 50, and the key was placed outside the `expo` object as stated in the [docs](https://docs.page/invertase/react-native-google-mobile-ads#appjson-2)

After some research, I found [this post](https://github.com/expo/fyi/blob/main/root-expo-object.md) about the migration from the root `expo` object.

I believe the documentation should be updated in this case, as it still states that the `react-native-google-mobile-ads` should be placed outside the `expo` block:

```
// <project-root>/app.json
{
  "expo": {
    // ...
  },
  "react-native-google-mobile-ads": {
    "android_app_id": "ca-app-pub-xxxxxxxx~xxxxxxxx",
    "ios_app_id": "ca-app-pub-xxxxxxxx~xxxxxxxx"
  }
}
```

**Comment by Lamonarch87** [comment]
Have you ever tried building with that config code inside "extra"?
Because I'm getting an error saying that the app_id is missing.

**Comment by raul-potor** [comment]
Nope, what I ended up doing was removing the root `expo` object from `app.json`

So before it looked like this:

```
{
  "expo": {
    "name: "foo",
    ...
  },
  "react-native-google-mobile-ads": {
    "android_app_id": "ca-app-pub-xxxxxxxx~xxxxxxxx",
    "ios_app_id": "ca-app-pub-xxxxxxxx~xxxxxxxx"
  }
}
```

and now it looks like this

```
{
  "name: "foo",
  ...
  "react-native-google-mobile-ads": {
    "android_app_id": "ca-app-pub-xxxxxxxx~xxxxxxxx",
    "ios_app_id": "ca-app-pub-xxxxxxxx~xxxxxxxx"
  }
}
```

And now the warning is gone and the ads seem to work well (only tested locally with the test units).
Don't know if this is the right way to do it or not on SDK 51

**Comment by dylancom** [comment]
Would be great if you can submit a PR to update the docs!

**Comment by raul-potor** [comment]
Hmm, I actually don't think this is a reliable solution, the `expo-doctor` check fails while validating the `app.json` schema with the following error:

```
• should NOT have additional property 'react-native-google-mobile-ads'.
```
So I actually think the better approach is to keep the `react-native-google-mobile-ads` config inside `extra` as @Lamonarch87 suggested.

I see there is already a PR in progress for that: https://github.com/invertase/react-native-google-mobile-ads/pull/584

**Comment by Lamonarch87** [comment]
> Hmm, I actually don't think this is a reliable solution, the `expo-doctor` check fails while validating the `app.json` schema with the following error:
> 
> ```
> • should NOT have additional property 'react-native-google-mobile-ads'.
> ```
> 
> So I actually think the better approach is to keep the `react-native-google-mobile-ads` config inside `extra` as @Lamonarch87 suggested. I mean, this approach works, the ads are displayed properly, but because o that error I don't think it's a long-term solution for now, just a workaround.
> 
> I see there is already a PR in progress for that: #584

I did not suggested to put inside "extra". It is written in Expo Documentation at the bottom of the link provided by you, but for me it's not working.

Even if expo-doctor is saying that is wrong, putting it outside of "expo" is the only way to build successfully atm.

**Comment by joshkitt** [comment]
I see that this issue is closed, but I'm not clear on what the solution is. Can you please provide a quick example of an app.json file that works for Expo SDK 51?

**Comment by macinjoke** [comment]
In my case, 

this worked.

```
module.exports = {
  expo: {
    // ...
  },
  'react-native-google-mobile-ads': {
    // ...
  }
}
```

This didn't work.

```
module.exports = () => {
  return {
    expo: {
      // ...
    },
    'react-native-google-mobile-ads': {
      // ...
    }
  }
}
```

My environment:

```
expo: ~51.0.8
react-native-google-mobile-ads: 13.6.0
```

**Comment by Lamonarch87** [comment]
> I see that this issue is closed, but I'm not clear on what the solution is. Can you please provide a quick example of an app.json file that works for Expo SDK 51?

In my case that is the last working config (yes, it's a very funny workaround and i don't know why it's working):

```
{
  "expo": {
    ...
    "extra": {
      "react-native-google-mobile-ads": {
        ...
      }
    }
  },
  "react-native-google-mobile-ads": {
    ...
  }
}
```

**Comment by Andreibv** [comment]
Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNGoogleMobileAdsModule' could not be found. on SDK EXPO 52

**Comment by oogunjob** [comment]
Getting the same error @Andreibv , did you figure it out?

**Comment by Andreibv** [comment]
> Getting the same error [@Andreibv](https://github.com/Andreibv) , did you figure it out?

@oogunjob, finally using EAS.

eas build --platform android --local
eas build --platform ios --local

npx expo run:android
arch -x86_64 npx expo run:ios
