### ISSUE TITLE
[📚] Documentation - Clarify the Necessity of Unique Package Names in Setup

### ISSUE THREAD

**Issue by d-swn** [invertase/react-native-google-mobile-ads#607]
### Documentation Feedback

Hello,

I am proposing an update to the documentation to include an important detail: the uniqueness / correct structure of the Android package name (applicationId, specified in build.gradle).

*Context*
During the setup and initialization of a new React Native project, especially when using npx react-native init ProjectName, the autogenerated package name may not always be unique or suitable for production environments or even for developing. This can lead to issues, particularly when integrating with services like Google AdMob, where a unique package name is mandatory to avoid conflicts and operational issues.

This can lead to issues where the request was succesfull but no ads even test ads will be delivered.

*Suggestion*
I suggest adding a section or a note in the initial setup documentation or under the section "Common reasons for ads not showing" explaining the importance of verifying the structure and uniqueness of the package name.

**Comment by DoctorJohn** [comment]
The maintainers of this repo always welcome new PRs and you're the export on this topic right now, so feel free to send one :) Personally I think it would make a great addition to the "Common reasons for ads not showing" page.
