### ISSUE TITLE
[🐛] Jest Setup file is deleting `TurboModuleRegistry.get`, breaking test suites

### ISSUE THREAD

**Issue by rodperottoni** [invertase/react-native-google-mobile-ads#631]
### What happened?

In my Jest Config file, I am adding `./node_modules/react-native-google-mobile-ads/jest.setup.ts` to my `setupFiles` config. This always worked for me until I decided to begin upgrading my libraries. That's when I started getting errors such as this in my test suite:

<img width="604" alt="Screenshot 2024-08-23 at 3 10 21 PM" src="https://github.com/user-attachments/assets/c9b3272f-068c-484e-8c25-d74320d5a1f9">

It took me a long time to find out the culprit, and apparently it's this file under `react-native-google-mobile-adds`. Notice how it assigns `getEnforcing` but not a `get` to the `TurboModulesRegistry` library:

```import * as ReactNative from 'react-native';

jest.doMock('react-native', () => {
  return Object.setPrototypeOf(
    {
      Platform: {
        OS: 'android',
        select: () => {},
      },
      NativeModules: {
        ...ReactNative.NativeModules,
        RNAppModule: {
          addListener: jest.fn(),
          removeListeners: jest.fn(),
          eventsAddListener: jest.fn(),
          eventsNotifyReady: jest.fn(),
        },
        RNGoogleMobileAdsModule: {
          addListener: jest.fn(),
          removeListeners: jest.fn(),
          eventsAddListener: jest.fn(),
          eventsNotifyReady: jest.fn(),
        },
        RNGoogleMobileAdsInterstitialModule: {
          interstitialLoad: jest.fn(),
        },
        RNGoogleMobileAdsRewardedModule: {},
        RNGoogleMobileAdsConsentModule: {},
      },
      TurboModuleRegistry: {
        getEnforcing: () => {
          return {
            initialize: jest.fn(),
            setRequestConfiguration: jest.fn(),
            openAdInspector: jest.fn(),
            openDebugMenu: jest.fn(),
            setAppVolume: jest.fn(),
            setAppMuted: jest.fn(),
          };
        },
      },
    },
    ReactNative,
  );
});
```

I think we need to better document how to setup `react-native-google-mobile-ads` with Jest, as well as fixing this mock for future users.

### Platforms

Android and iOS

### React Native Info

```Shell
Not applicable.
```

### Are your using Typescript?

- [X] My project is using Typescript

### package.json

```JSON
Not applicable.
```

### app.json

```JSON
Not applicable.
```

### ios/Podfile

```Ruby
Not applicable.
```

### android/build.gradle

```Groovy
Not applicable.
```

### android/app/build.gradle

```Groovy
Not applicable.
```

### android/settings.gradle

```Groovy
Not applicable.
```

### AndroidManifest.xml

```XML
Not applicable.
```

**Comment by rodperottoni** [comment]
Not stale

**Comment by mikehardy** [comment]
PRs welcome!

**Comment by mikehardy** [comment]
Just saw this actually *had* a PR 🤦

**Comment by rodperottoni** [comment]
hey @mikehardy, thanks for merging the PR. I didn't even realise someone else had done it.

Apparently the types are broken on 14.2.4:

<img width="1147" alt="Screenshot 2024-10-08 at 8 42 22 AM" src="https://github.com/user-attachments/assets/20b68b06-5855-476f-8d66-d730f7aea5eb">

**Comment by rodperottoni** [comment]
The type issue seems to be caused by #619, but I don't know much about this new `type-test.ts` file and how it could've broken things.

**Comment by mikehardy** [comment]
Hmm I won't have time until tomorrow but maybe @DoctorJohn has an idea?

**Comment by DoctorJohn** [comment]
Didn't see this coming, wow. I'm currently investigating. Looks like the addition of the `type-test.ts` file to the `include` array in the `tsconfig.json` file is causing the issue. Removing it and running `yarn build` generates the expected TypeScript definitions in `lib/typescript`.  I'll create a PR once I'm certain about what's going on.
