### ISSUE TITLE
Example app needs demonstration of consent management

### ISSUE THREAD

**Issue by mikehardy** [invertase/react-native-google-mobile-ads#64]
Looks like example/App.tsx could use a probe of AdConsent vs current documentation to make sure that it is working, as it seems to be broken: 
----

I don't know... I experience something really weird I never saw before: I print `AdsConsent` to console and verify that it is an object, and it has `.requestInfoUpdate()` method. On the very next line I call it, and get the error saying I'm trying to call a method of `null`. Just reverting back to 4.0.2, everything works fine. I guess, there should be something peculiar or wrong with my app setup (just JS by the way) conflicting with some TypeScript changes, but I guess I'll stick with 4.0.2 for now, and come back to trying 4.1.0 later :)

_Originally posted by @birdofpreyru in https://github.com/invertase/react-native-google-mobile-ads/issues/63#issuecomment-1022556563_

**Comment by dylancom** [comment]
It seemed AdsConsent wasn't part of the renaming process yet.

**Comment by mikehardy** [comment]
As long as we have an API that we support, deprecated or not, we should have a test for it. Once an API is removed, remove the associated tests. A simpler test is: a bug was reported with it and did you a) ignore it or b) fix it? You fixed it :-), that means a simple test to make sure it's working should be useful. Would have saved me from forgetting it during the rename at least

**Comment by mikehardy** [comment]
This seems like the best issue to hold the idea we want the example to demonstrate managing consent #82
