### ISSUE TITLE
[📚] Can I "filter" rewarded video ads by length ?

### ISSUE THREAD

**Issue by seba9999** [invertase/react-native-google-mobile-ads#641]
### Documentation Feedback

Is there a way to filter rewarded video by length ?

I mean that a 30sec video for a reward in my app is too long ... And as a user I've already seen some shorter ads ... (Maybe it was "luck" or they didn't use google ad mob ? )

But I can't find this kind of filter in [the RequestOptions](https://github.com/invertase/react-native-google-mobile-ads/blob/b3592926966f4f03c7107807c244ba4673a876c0/src/types/RequestOptions.ts#L24) 

Maybe there's a way on the google ad mob dashboard that I didn't find ?

**Comment by DoctorJohn** [comment]
Neither this library nor Google's upstream SDKs provide such an option. AFAIK, Admob doesn't offer such an option on their dashboard either. Your only hope would be third-party ad networks, which might provide such an option.
