### ISSUE TITLE
[📚] Google Ad Manager

### ISSUE THREAD

**Issue by oromis300** [invertase/react-native-google-mobile-ads#644]
### Documentation Feedback

Hi, I couldn't find in the docs if this lib work with Google Ad manager (https://developers.google.com/ad-manager/mobile-ads-sdk?hl=fr) instead of Admods. The adUnitId look like that /21775744923/example/fixed-size-banner and not like that ca-app-pub-3940256099942544/9214589741
I tried but for now without success. I'm wondering if i'm doing something wrong or if the lib can't display ads with those ids

**Comment by mikehardy** [comment]
https://github.com/search?q=repo%3Ainvertase%2Freact-native-google-mobile-ads%20AdManager&type=code

A quick search shows AdManager support built in to the library

I believe it is supposed to "just work", however there are lots of reasons why things don't show. Unfortunately I'm not aware of any of them that have to do with the implementation here, they mostly seem to resolve to subtle reasons for no-fill from the ad network(s) https://docs.page/invertase/react-native-google-mobile-ads/common-reasons-for-ads-not-showing
