### ISSUE TITLE
When opening this page in debug mode, I am met with these errors:

### ISSUE THREAD

**Issue by SiavashRahimii** [invertase/react-native-google-mobile-ads#649]
When opening this page in debug mode, I am met with these errors:

<img width="908" alt="Screen Shot 2019-09-12 at 11 48 08" src="https://user-images.githubusercontent.com/17879993/64778057-3635ad00-d553-11e9-8c53-63e596b48cfc.png">

_Originally posted by @24dev in https://github.com/invertase/react-native-firebase/issues/2562#issuecomment-530771250_

**Comment by mikehardy** [comment]
No context, no indication this is a problem here vs just a misconfiguration in your app
This looks like a misconfiguration
