### ISSUE TITLE
[🐛] Bug Report Title - googleMobileAds/null-activity

### ISSUE THREAD

**Issue by DarshanSavaliyaGitHub** [invertase/react-native-google-mobile-ads#668]
### What happened?

Hello,
 I've implemented _react-native-google-mobile-ads_ lib in my react native application, in which we have integrated app-open Ads but in that we are getting **_googleMobileAds/null-activity_**  error.
 
 I want to know why it's logging in mix-panel events and if possible then please provide all errors and causing of that error.

### Platforms

Android and iOS

### React Native Info

```Shell
-  "react-native": "0.73.1",
-   "react": "^18.2.0",
```

### Are your using Typescript?

- [ ] My project is using Typescript

### package.json

```JSON
 "react-native-admob-native-ads": "^0.7.6",

```

**Comment by mikehardy** [comment]
wrong repo
