### ISSUE TITLE
[🐛] Bug Report Title - Error with expo sdk 52 - 'RNGoogleMobileAdsModule' could not be found.

### ISSUE THREAD

**Issue by Andreibv** [invertase/react-native-google-mobile-ads#676]
### What happened?

Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNGoogleMobileAdsModule' could not be found.

    "react-native": "0.76.5",
    "react-native-google-mobile-ads": "^14.7.2",
    "expo": "~52.0.19",

### Platforms

Android and iOS

### React Native Info

```Shell
Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNGoogleMobileAdsModule' could not be found. Verify that a module by this name is registered in the native binary.
```

### Are your using Typescript?

- [ ] My project is using Typescript

### package.json

```JSON
"react-native": "0.76.5",
    "react-native-google-mobile-ads": "^14.7.2",
    "expo": "~52.0.19",
```

### app.json

```JSON
[
        "react-native-google-mobile-ads",
        {
          "androidAppId": "ca-app-pub-abc~cde",
          "iosAppId": "ca-app-pub-efg~hij"
        }
      ]
```

**Comment by mikehardy** [comment]
I read:

"I am using Expo and my app doesn't properly load this custom native module I am trying to use"

Which is probably the most common expo issue logged in github repositories for custom native modules.

You need to read up on the Expo documentation related to building your app when you are integrating custom native modules and make absolutely completely totally certain you know all the subtleties around building your app on to your device such that the custom native module is included. A good word to search for is probably "prebuild", but from what I understand as a non-Expo user there are like 4 little subtle things that could go wrong with caching or wrong command invocation and such.

All I can tell you is that the module works and if you build it correctly into the app and then install that app on your device it will work

**Comment by FranklysG** [comment]
THIS WORK FOR ME
```yml
{
  "expo": {
      "extra": {
            "react-native-google-mobile-ads": {
              "androidAppId": "ca-app-pub-000000~999999",
              "iosAppId": "ca-app-pub-000000~999999",
              "userTrackingUsageDescription": "Este identificador será usado para entregar anúncios personalizados para você."
            }
          }
      },
    "react-native-google-mobile-ads": {
        "android_app_id": "ca-app-pub-000000~999999",
        "ios_app_id": "ca-app-pub-000000~999999"
      }
}

**Comment by mikehardy** [comment]
@FranklysG seems pretty strange that it needs to be duplicated? That's unexpected

**Comment by FranklysG** [comment]
>  seems pretty strange that it needs to be duplicated? That's unexpected

yes, but if you look closely, the keys are different, only the values ​​are the same

**Comment by ssommelet21** [comment]
I use EXPO with react-native-google-mobile-ads without problem.

No need to duplicated :

{
  "expo": {
      "extra": {
            "react-native-google-mobile-ads": {
              "androidAppId": "ca-app-pub-000000~999999",
              "iosAppId": "ca-app-pub-000000~999999",
              "userTrackingUsageDescription": "Este identificador será usado para entregar anúncios personalizados para você."
            }
          }
      },
    "react-native-google-mobile-ads": {
        "android_app_id": "ca-app-pub-000000~999999",
        "ios_app_id": "ca-app-pub-000000~999999"
      }
}

This is not in extra

**Comment by dylancom** [comment]
Expo users should make use of the Expo plugin and read our [docs](https://docs.page/invertase/react-native-google-mobile-ads#installation):
```
// <project-root>/app.json
{
  "expo": {
    "plugins": [
      [
        "react-native-google-mobile-ads",
        {
          "androidAppId": "ca-app-pub-xxxxxxxx~xxxxxxxx",
          "iosAppId": "ca-app-pub-xxxxxxxx~xxxxxxxx"
        }
      ]
    ]
  }
}
```

**Comment by Andreibv** [comment]
Thank you all for recomendations.
The real problem was with Expo Go, my workspace had problems with Pods.
Using EAS 'Development build' all is good.

npm install -g eas-cli
eas login
eas build:configure
eas build -p android --profile development || eas build -p ios --profile development

More details here: https://coding-lilac.vercel.app/blog/adding_google_maps_to_react_native_app

**Comment by dylancom** [comment]
![image](https://github.com/user-attachments/assets/282ca61e-58d3-4227-823a-c87c95cf74c0)

**Comment by yeeydu** [comment]
Hi, I manage to build my app after many building attempts. using expo eas cli "eas build --platform android".


This is my app.json admob code. the build shows a warning about the code outside the expo braces { } but it still works.
"Warning: Root-level "expo" object found. Ignoring extra keys in Expo config:  "react-native-google-mobile-ads"
 

 "expo": "^52.0.26",
 "react-native": "0.76.6",
"react-native-google-mobile-ads": "^14.8.0",

must of the packages must be updated to a compatible version.

I hope this helps!!

    "plugins": [
      [
        "expo-build-properties",
        {
          "android": {
            "extraProguardRules": "-keep class com.google.android.gms.internal.consent_sdk.** { *; }",
            "compileSdkVersion": 35,  // it still works with sdk 34
            "targetSdkVersion": 35,  // it still works with sdk 34
            "buildToolsVersion": "34.0.0"
          }
        }
      ],
      [
        "react-native-admob-native-ads",
        {
          "androidAppId": "ca-app-pub-1234567890987654321~123456789",
 
        }
      ],
    ]
  },
  "react-native-google-mobile-ads": {
    "android_app_id": "ca-app-pub-1234567890987654321~123456789",
    "user_tracking_usage_description": "This identifier will be used to deliver personalized ads to you.",
    "delay_app_measurement_init": true
  }
}

**Comment by Andreibv** [comment]
> Thank you all for recomendations. The real problem was with Expo Go, my workspace had problems with Pods. Using EAS 'Development build' all is good.
> 
> npm install -g eas-cli eas login eas build:configure eas build -p android --profile development || eas build -p ios --profile development
> 
> More details here: https://coding-lilac.vercel.app/blog/adding_google_maps_to_react_native_app

Another way to run easier is with these commands:

    npx expo run:ios
    npx expo run:android

**Comment by webodhonzi-create** [comment]
It is very uncommon, but had same problem for over 4h. Than I uninstall whole apk, used:
```
// <project-root>/app.json
{
  "expo": {
    "plugins": [
      [
        "react-native-google-mobile-ads",
        {
          "androidAppId": "ca-app-pub-xxxxxxxx~xxxxxxxx",
          "iosAppId": "ca-app-pub-xxxxxxxx~xxxxxxxx"
        }
      ]
    ]
  }
}
```
build it through eas and installed latest build. Problem than solved.
