### ISSUE TITLE
Change TestIds to real Ad Unit Id but ad not working

### ISSUE THREAD

**Issue by jossifelefteriadis** [invertase/react-native-google-mobile-ads#70]
I've made my app work as I want with Interstitial ads but when I change

```
const rewarded = RewardedAd.createForAdRequest(TestIds.INTERSTITIAL, {
  requestNonPersonalizedAdsOnly: true,
});
```
to
```
const rewarded = RewardedAd.createForAdRequest('ca-app-pub-3940256099942544/1033173712', {
...
```
it's not showing.

Is there anything that needs to setup differently when using a real ad unit id?

**Comment by dylancom** [comment]
Could be multiple things.
- You haven't setup an app-ads.txt https://developers.google.com/admob/ios/app-ads
- The ad unit is too new. (just created)

Also testing on a real device could make a difference.

**Comment by jossifelefteriadis** [comment]
I noticed the link is for ios, I'm creating this for android, is there something similar?
It's been a couple of days since I created it but I think I read it might take up to 2 weeks?

**Comment by dylancom** [comment]
https://developers.google.com/admob/android/app-ads

**Comment by jossifelefteriadis** [comment]
I'll set that up, but that couldn't be the reason my ads aren't showing, could it?

**Comment by dylancom** [comment]
Did you test it on a real device?

**Comment by jossifelefteriadis** [comment]
Yes, through internal testing on play store. No ads was showing

**Comment by dylancom** [comment]
So, is your app-ads.txt verified within the AdMob dashboard?

**Comment by dylancom** [comment]
> I'll set that up, but that couldn't be the reason my ads aren't showing, could it?

That can be the reason that real ad units don't show up, yes.

**Comment by dylancom** [comment]
Also see: https://support.google.com/admob/thread/58334122/why-my-ad-not-showing-on-any-android-device?hl=en

**Comment by jossifelefteriadis** [comment]
So I just got an email saying my admob account was approved. So I'm using my App Id and Ad Unit Id in Android Studio and I can see a 'real' ad but it still says 'Test Ad' on top. Will that label be automatically removed when it's on a real device and not in Android Studio?

**Comment by dylancom** [comment]
Yes that will show up in a "release" version of your app. Under "development" it shows "Test Ad".

**Comment by jossifelefteriadis** [comment]
So testing on my phone (Internal testing) - without changing anything since the last comment - it works and shows the ads without the 'Test Ad' label on top. So I assume everything is up and running.

Maybe there's a way of doublechecking this with analytics somehow?

**Comment by mikehardy** [comment]
@dylancom - your links and this information is gold! I am actually new to google mobile ads myself, and I would never have known this stuff. Maybe we need a section of the readme that is either "why is my ad not showing up?" or that is "best practices to get ads to fill" or whatever title makes sense, but that has an entry for each of these things (the ads .txt file, the emulator vs real device differences, the time frames for approval, etc etc). It will probably save hours of replying to issues in the future, but I'm not qualified to write it :sweat_smile:

**Comment by dylancom** [comment]
Totally! There is still a “documentation” issue open where I’m addressing that we need this! This is very common so we indeed need an extra section in the docs.

Verstuurd vanaf mijn iPhone

**Comment by jossifelefteriadis** [comment]
Would def make life easier. I'm sure I'm not the only one that got stuck with this. Let me know if you'd need my help with inputs or similar based on my recent experience.

**Comment by dylancom** [comment]
Added a PR: https://github.com/invertase/react-native-google-mobile-ads/pull/71. Let me know if this would have helped good enough in your case :)
