### ISSUE TITLE
Ads Mediation Help needed

### ISSUE THREAD

**Issue by sonivaibhav27** [invertase/react-native-google-mobile-ads#78]
Hi ,  I want to use Facebook with Admob ads bidding , But i am not sure is it possible in the library? If it is possible , can you help me how to implement the same. Thank you

**Comment by dylancom** [comment]
The `initialize` method returns a promise with all adapterStatuses and will inform you which ad network adapters are all connected.

**Comment by sonivaibhav27** [comment]
Thank you so much @TaylorDale @dylancom for your work on the library and also for your answers.

**Comment by dylancom** [comment]
You're welcome!

**Comment by Robiullah2244** [comment]
Hi, I followed the steps. But I am getting the error: "Unity ads requires an activity context to load ads". Do you know how I can solve this? Please help me.
