### ISSUE TITLE
:fire: [Feature/info request] GAMBannerView plans?

### ISSUE THREAD

**Issue by aidan-24com** [invertase/react-native-google-mobile-ads#81]
## Issue

Hello,

Our requirements (see below) need the `GAM…` variants (Banner views, requests, etc) and currently only `GAD…` appears to be implemented in this package.

Are there any plans going forward to include `GAM…`? If so, any timelines (I know, not a great question to ask)?

If there are no plans currently (or they are beyond the next week), would you guys possibly accept a PR with `GAM…` functionality included _(or is `GAM…` excluded for a specific reason)_?

Apologies for filing this as an "issue", but I wasn't sure where else to ask.

Requirements (amongst others):
- `validAdSizes` https://developers.google.com/ad-manager/mobile-ads-sdk/ios/api/reference/Classes/GAMBannerView#validadsizes
- `ppid` https://support.google.com/admanager/answer/2880055?hl=en

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `admob.json`:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

```ruby
# N/A
```

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 131.54 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: 1.12.0 => 1.12.0 
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **Are you using `TypeScript`?**
  - `Y` & `4.2.2`

</p>
</details>

---

- 👉 Check out [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
It looks like a recent change actually started pulling in GAM... items: https://github.com/invertase/react-native-google-mobile-ads/pull/76/files#diff-0d4f5e6263b5f524a6d42378d8d0564e270ee6b02b4b402ce64c49782f4a6579

I'm not aware of any current plans in the area however we are definitely open to any reasonable PR, and if it's backwards compatible it's usually a matter of saying "Yep, looks good..." then merge+release

**Comment by aidan-24com** [comment]
amazing, thank you

**Comment by birgernass** [comment]
@aidan-24com what are your plans here exactly? I am also interested in bringing Ad Manager to this repository.

Colleagues and I started to work on a public react-native Google Ad Manager library but decided long since to continue our work in private to speed things up. Now that I had an introduction into this code base by working on the UMP integration I think this might be a good time to switch back to open source.

The code is in Swift and Java and uses the RCTViewManager and ViewGroupManager respectively to handle the BannerView attachment and load from JS, as we encountered performance issues when using many banner ads in FlatLists directly and waiting with the ad load for a user to stop scrolling or only attaching banner views while they are in viewport helped. I'm not yet sure how to decouple our Amazon Publisher Services and Prebid integrations exactly, but maybe someone here would have an idea, if all of this sounds interesting in the first place.

@mikehardy What are your general thoughts on this idea? And are there any issues with adding Swift code to this project?

**Comment by mikehardy** [comment]
I was thinking, separately, that it's probably time for most/all of my repos to go Kotlin/swift. So, no objections at all. Could do one mass conversion of existing code using available tooling, stabilize/polish that with a release then move forward with new stuff?

**Comment by mikehardy** [comment]
I don't think either gradle or swift is widely used in the react-native ecosystem but in my experience running a native app (https://github.com/ankidroid/Anki-Android) that is fairly conservative, even we are converting to Kotlin now. There are a few modules already using it (react-native-webview and detox for kotlin, firebase using swift) which means inter-operation / build kinks have already been worked out as far as I know though, so we won't be first or last - which usually means pain of trailblazing or pain of limited compatibility, just a medium-early adopter I think which should be pretty pain-free.

So I don't feel really strongly (ecosystem hasn't really started using it yet) but I do think it's inevitable and right now the only outstanding pull request is yours so it won't be disruptive as normally PR disruption is the problem.

As you *do* have a PR outstanding though, probably makes sense to work that one through, then try an auto-conversion? Both represent breaking changes, could perhaps stack them up in one major version from a release engineering perspective, or could just do two major versions kind-of back to back with a note for the kotlin/swift conversion that nothing *should* change but we're marking it major just in case.

Fairly far afield from the title "GAMBannerView plans" but hopefully answers the direct question.
