### ISSUE TITLE
[📚] Displaying Ads reference to banneradsize is 404 / how to link to ref typedocs?

### ISSUE THREAD

**Issue by sdb1228** [invertase/react-native-google-mobile-ads#83]
## Documentation Feedback

Please describe your documentation issue or suggested improvement in detail here and provide links to any pre-existing/relevant documentation and screenshots if necessary:

The link on https://docs.page/invertase/react-native-google-mobile-ads/displaying-ads that references banneradsize is 404ing https://docs.page/invertase/react-native-google-mobile-ads/reference/admob/banneradsize. Not entirely sure where you want it to lead to but happy to update that if you have a specific place!

---

- 👉 Check out [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Seems like we need to do typedoc generation if possible, then reference that.
I think docs.page handles it but not entirely sure @Ehesp do you know that off-hand?

**Comment by cabljac** [comment]
docs.page doesn't handle typedoc yet, we were going to look at that as a feature at some point

**Comment by mikehardy** [comment]
Ah okay - thanks @cabljac - then I think the best path forward for the moment is simply to take what *would* have been in the reference and put the example inline. This may be necessary for other references as well, so a quick grep through for similar references (and putting a quick note in their place containing the important information) would be a huge help

**Comment by duggster** [comment]
I came here looking for the possible values of BannerAdSize. Found it here: https://github.com/invertase/react-native-google-mobile-ads/blob/main/src/BannerAdSize.ts
Posting in case it helps someone else.
