### ISSUE TITLE
[🐛] need a build time error message if app ids are not loaded from app.json 🔥

### ISSUE THREAD

**Issue by aguglie** [invertase/react-native-google-mobile-ads#84]
Hello,
Thank you for you super work;

## Issue

I'm trying to migrate from `@react-native-firebase/admob` to this library; I'm experiencing some trouble with the app crashing while reporting the following message in `locgcat`:

```
    ******************************************************************************
    * Invalid application ID. Follow instructions here:                          *
    * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
    * to find your app ID.                                                       *
    ******************************************************************************
    
```

I checked the generated manifest in `out/AndroidManifest.xml` and, as the crash states, it does not contain the app ID:
```
        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="" />
        <meta-data
            android:name="com.google.android.gms.ads.DELAY_APP_MEASUREMENT_INIT"
            android:value="true" />
```

My `app.json`, in the project root, seems correctly filled as follows:
```json
{
  "name": "my-app",
  "displayName": "my-app",
  "react-native-google-mobile-ads": {
    "admob_android_app_id": "ca-app-pub-663628667XXXXXX~55273YYYYYY",
    "admob_ios_app_id": "ca-app-pub-663628667XXXXXXXX~9302YYYYYYY",
    "delay_app_measurement_init": true,
    "user_tracking_usage_description": "This identifier is used..."
  }
}

```

I've tried to trace the issue but I can't get the reason why the app.json is not included.
Looking into [app-json.gradle](https://github.com/invertase/react-native-google-mobile-ads/blob/v4.2.0/android/app-json.gradle) file, I would expect some sort of log when the app is built, but no line refers to `app.json´

```
> Configure project :react-native-google-mobile-ads
:react-native-google-mobile-ads package.json found at /Users/andrea/peronal/my-app/node_modules/react-native-google-mobile-ads/package.json
:react-native-google-mobile-ads:ads.consent using default value: 1.0.6
:react-native-google-mobile-ads package.json found at /Users/andrea/peronal/my-app/node_modules/react-native-google-mobile-ads/package.json
:react-native-google-mobile-ads:version set from package.json: 4.2.0 (4,2,0 - 4002000)
:react-native-google-mobile-ads:android.compileSdk using custom value: 31
:react-native-google-mobile-ads:android.targetSdk using custom value: 29
:react-native-google-mobile-ads:android.minSdk using custom value: 21
:react-native-google-mobile-ads:reactNativeAndroidDir /Users/andrea/peronal/my-app/node_modules/react-native/android

```

Any help is appreciated,
Thanks

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "name": "my-app",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "17.0.1",
    "react-native": "0.64.0",
    "@react-native-firebase/analytics": "^14.5.0",
    "@react-native-firebase/app": "^14.5.0",
    "@react-native-firebase/auth": "^14.5.0",
    "@react-native-firebase/crashlytics": "^14.5.0",
    "@react-native-firebase/dynamic-links": "^14.5.0",
    "@react-native-firebase/messaging": "^14.5.0",
    "react-native-google-mobile-ads": "^4.2.0"
....
  },
  "devDependencies": {
.....
  }
}

```

#### `admob.json`:

```json
# N/A
```

</details>

### iOS

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
  Binaries:
    Node: 14.19.0 - ~/.nvm/versions/node/v14.19.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.19.0/bin/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v14.19.0/bin/npm
    Watchman: 2022.01.31.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 23, 29, 30, 31
      Build Tools: 29.0.2, 30.0.2
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8139111
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14 - /Users/andrea/.sdkman/candidates/java/current/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ X ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **Are you using `TypeScript`?**
  - `N` 

</p>
</details>

---

**Comment by mikehardy** [comment]
This may boil down to a documentation issue, or the need for a better error message somewhere / somehow but I think it's just that your app.json has the wrong keys

You may consult the example app to see how it is supposed to work, note the different key names:

https://github.com/invertase/react-native-google-mobile-ads/blob/fa88240d937499b4a570c40914f06054dfa31b89/example/app.json#L5

**Comment by aguglie** [comment]
Oops, 

Thank you @mikehardy, you made my day (well, actually, night 😄 )
I was checking since hours :)

**Comment by mikehardy** [comment]
I'm really glad that helped! Okay since that appears to be the root cause, and it's an app crash if the variable is not found, I'm going to reopen this as there *must* be a good build time error we can kick out during the android build (and likely the iOS build too!) when these critical items are not found in app.json

**Comment by ertandrn** [comment]
@mikehardy  Hi, I'm getting the same error testing the release build. Could it be because Admob approval status is "require review"? If so how can I ignore it for release?

**Comment by mikehardy** [comment]
@ertandrn I don't really trust statements like "I'm getting the same error" sorry - too many followups containing something like "except..." or "oh but" :sweat_smile: 

So let me just state, if your native logs contain this error message above about "Invalid application ID", with a crash, then this has nothing to do with approval status. This is just incorrect module integration somehow. The app ID is somehow either not in app.json *or* for some reason not being interpolated into the final merged AndroidManifest.xml via this module's gradle scripts + manifest placeholders.

**Comment by foloinfo** [comment]
I was in the same situation that I didn't have the correct key in `app.json`. This issue helped me solve that.
I had to look for the native error logs to find out `Invalid application ID` was casing the crash.

I don't think it's a bug, but I do think it is more helpful to raise an error during or before the build, since it's easier and faster to find what's wrong.
