### ISSUE TITLE
App performance tanks during and after displaying a rewarded ad on Android

### ISSUE THREAD

**Issue by evelant** [invertase/react-native-google-mobile-ads#92]
I'm seeing a major drop in app performance during and after playing a full screen rewarded ad on Android. The ad video tends to stutter while playing but after the ad is complete the entire UI stutters and lags for 10+ seconds. It seems likely this could be a bug in the underlying Google ads SDK and not this library but I wanted to check here first to see if there's anything that can be done from the react-native side.

```
"react-native": "^0.67.1",
"react-native-google-mobile-ads": "^5.0.0",
```

Tested on a release build on a Galaxy s9+. Some users have also reported that the app crashes during an ad view. Other users have reported that the app becomes permanently laggy until it is killed and restarted after viewing an ad.

**Comment by mikehardy** [comment]
My goodness, that's the opposite of a reward isn't it. I don't have rewarded ads integrated in any of my apps so I can't say even anecdotally.
Are you able to reproduce this with any modifications to the example app here? (just as a hopefully-quick way to check if it's project-specific or general)
Failing that then the next step is to check the android native docs / examples to see if a quick repro happens there (or if there is already something noted in their issues list)? https://developers.google.com/admob/android/sdk / https://github.com/googleads/googleads-mobile-android-examples

**Comment by evelant** [comment]
@mikehardy I've been really crunched trying to get the next release of my app out so I haven't had time to try to make a reproduction yet but I can provide a bit more detail about the behavior. Here's what I've observed:

* `const rewarededAd = RewardedAd.createForAdRequest(AD_UNIT_HERE)` and `rewardedAd.load()`
* Observe a several second wait for ad to load before `onAdEvent` fires
* Call `rewardAd.show()`
* Ad plays seemingly without issue
* Close ad 
* App stutters heavily for several seconds including animations with `useNativeDriver: true` so it's not just JS thread blocking
* After this the app continues to stutter every ~1000ms or so forever, including stuttering native animations

This leads me to believe that the problem is on the native side since `useNativeDriver: true` animations are stuttering as well. I'll try to find time to dig in more soon.

**Comment by evelant** [comment]
Turns out it was a conflict with a library in our app. We're using UXCam to analyze user sessions and it starts behaving very badly for whatever reason when an ad is shown. Not an issue with this excellent library!

**Comment by mikehardy** [comment]
Ah ha! Thanks for coming back and explaining + closing it out, glad it wasn't this module 😅
