### ISSUE TITLE
🔥  BannerAd sound keeps playing even if the screen that contains this component is unmount

### ISSUE THREAD

**Issue by kamilianek** [invertase/react-native-google-mobile-ads#93]
## Issue

First of all, thanks a lot! I think you are doing great job and I really appreciate your contribution.

Our application that uses this library is live now and doing well. To give a context I will elaborate on how `BannerAd` is used within application. Generally we have comic images gallery that user can swipe horizontally (horizontal `FlatList` with paging enabled and appropriate styling to show one image at once). After 3rd image, instead of next comic image, banner ad of the same size as comic image, is displayed. Of course this banner ad is displayed only if successfully loaded (`onAdLoaded()` callback), if not, 4th comic image is shown normally.

Basic usage is like this:

```js
import { BannerAd as AdmobBanner } from '@invertase/react-native-google-ads';
```

```js
<AdmobBanner
  unitId={adId}
  size={size || defaultBannerSize}
  onAdFailedToLoad={() => {
    setLoaded(false);
  }}
  onAdLoaded={() => {
    onLoaded?.();
    setLoaded(true);
  }}
/>
```

If it comes to the initialization, default ad configuration is used, and initialization looks like this (run once on app start):

```js
admob()
  .initialize()
  .then(() => {
    initialized = true;
});
```

It works really nice! Nevertheless, we experienced strange behavior using this ad of `BannerAd` type. Namely, some of ads has sound (that's good and normal, I think), and this **sound keeps playing even if the screen that contains `BannerAd` component is unmount** (potential issue). As a result, when you open that screen once again and another ad with sound is displayed, there will be another "layer" of sound - as a result two different sounds are played at once. You can repeat it again and again, every time another sound is played in parallel with others. What's more, when app is in background, sounds still keep playing. The only way to stop those banner ad sounds is killing application.

What we noticed is that this issue does not occur for every banner ad with sound or device. One of us experiences it every time but another had different ad with different sound, on different device, and cannot reproduce the issue (sound stops playing for him even when he swipes from banner ad to 4th image in the `FlatList`).

Unfortunately I cannot share whole files suggested in the issue template. So, if you notice that I missed something relevant, please let me know I will try to provide crucial resources as soon as possible.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
"name": "AppName",
  "version": "1.1.1",
  "private": true,
  "dependencies": {
    "react-native": "0.66.3",
    "@invertase/react-native-google-ads": "4.0.2",
    // some other dependencies
  }
```

#### `<project-root>/app.json`:

```json
{
  "name": "AppName",
  "displayName": "AppName",
  "react-native-google-ads": {
    "android_app_id": "ca-app-pub-xxxxxxxxxxxxxxxx~xxxxxxxxxx",
    "ios_app_id": "ca-app-pub-xxxxxxxxxxxxxxxx~xxxxxxxxxx"
  }
}
```
</p>
</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

```ruby
# N/A
```

</p>
</details>
---

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
buildscript {
    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 23
        compileSdkVersion = 29
        targetSdkVersion = 30
        glideVersion = "4.11.0"
        ndkVersion = "22.1.7171670"
        androidXCore = "1.1.0"
        firebaseBomVersion = "28.0.1"
    }

    // [...]
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 11.6.1
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 406.48 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.6.2 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 7.20.3 - /usr/local/bin/npm
    Watchman: 2021.08.02.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3
      System Images: android-28 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-31 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.3 => 0.66.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [X] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **Are you using `TypeScript`?**
  - `N0`

</p>
</details>

---

- 👉 Check out [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Fascinating! Sounds really irritating if you are an effected user!
Can you share details on devices where it happens reliably? Sounds like android for sure. Can you get it to happen with android emulators? That would help a lot with reproduction

**Comment by kamilianek** [comment]
Yeah! Anyway still hope that it's rather an edge case (specific ad or device). Additional info:

- It has been reproduced many times on `OnePlus 7t Pro HD1913`, with `Android 11`
- We have not experienced issue on `Xiaomi Mi 10T Pro` with `Android 11`
- We have not experienced issue on `iPhone`s so far

I'll try to reproduce the issue on emulator and let you know 👏

**Comment by mikehardy** [comment]
I have a OnePlus 6t w/Android 11, may be close enough - a reproduction here will be gold, even if you could cook up an App.js we could drop in the example app perhaps, anything to reproduce it would help
