### ISSUE TITLE
Ads consent with the new UMP SDK implementation

### ISSUE THREAD

**Issue by birdofpreyru** [invertase/react-native-google-mobile-ads#96]
Sorry for not following the issue template, I am just trying to migrate my projects to v5 of this library, and need some place to record issues I encounter on the way :)

- Docs: [European User Consent](https://docs.page/invertase/react-native-google-mobile-ads/european-user-consent) page should mention that configuration is required in AdMob web console, at https://apps.admob.com/v2/privacymessaging. Right now it can be figured out from the link at [Installation](https://docs.page/invertase/react-native-google-mobile-ads#european-user-consent) page, but not on EUC page itself. Also, in my current understanding, it is not necessary for the library user to read entire [Obtaining Consent with the User Messaging Platform](https://developers.google.com/admob/ump/android/quick-start) document, for purposes of setting up.

- I am suspecting a bug in the library. I am creating GDPR form with three options (Consent / Do not consent / Manage options). It seems to work as expected when I do consent (including banner / interstitial ads being shown as expected, at the first glance). However, when I choose to **not consent** in the form, I am still getting `{"status": "OBTAINED"}` result from the **.showForm()** call (although no ads are served in that case).

**Comment by birgernass** [comment]
Not receiving ads with the consent status being obtained is not a bug. You can find a bit more information about the change and how to get the consent information on the [migration page](https://docs.page/invertase/react-native-google-mobile-ads/migrating-to-v5) of the docs.

**Comment by birdofpreyru** [comment]
@birgernass My main point was that I was getting `{"status": "OBTAINED"}` from **.showForm()** when I declined the consent in the form. I see, in the migration page it mentions that this status in this case just means the user have seen the form already and it is necessary to

> You can read the IABTCF_TCString key from standardUserDefaults / SharedPreferences and decode it with a library like [@iabtcf/core](https://github.com/InteractiveAdvertisingBureau/iabtcf-es/tree/master/modules/core#iabtcfcore) though.

It is however different from what is written in the main docs (https://docs.page/invertase/react-native-google-mobile-ads/european-user-consent#gathering-user-consent), and also IMHO counter-intuitive... why not return `{"status": "REQUIRED"}` if the consent requried, but user denied it in the form?

**Comment by birgernass** [comment]
The interfaces tries to stick as close to the native implementation as possible. Required means that the user has not yet seen the modal and that you should show it.

**Comment by birdofpreyru** [comment]
Ok. But then if I need the actual content status (doesn't look a rare edge-case to me) I need to implement it myself, instead of just getting it from this library. I believe, one way or another it should be exposed by this library.

**Comment by mikehardy** [comment]
I think it is reasonable to be "opinionated" and select a default consent form and maintain it, since it really will be used by everyone. I am a huge fan of libraries like @birdofpreyru suggests that take things everyone needs to do and just gets them done. I will say I am a big "no" on making the opinion mandatory - so ideally it would be zero-code / maybe-just-a-little-config for a general consent form, but you could swap in a different one if you wanted.

I'm not free to code this myself right now, but that's my $0.02 on usefulness and things I'd like, for whatever that is worth.

If there is any documentation shortcoming at all please please :pray: please post up a PR anywhere that seems useful in the docs, you've seen us merge those like lightning.

**Comment by birdofpreyru** [comment]
Not sure when I'll have time to contribute either... though, it seems I have figured out how to make it work for me, on Android at least, so what do you think of the following:

We can add dependency on https://github.com/kevinresol/react-native-default-preference and https://www.npmjs.com/package/react-native-device-info, and use them in JS layer to read all IABTCF_* keys from default shared app preferences and return them to the user from a new method of AdsConsent? I'd also add an option to get a simple flag / enum with the actual consent status, probably adding it as an extra field(s) to the result of .showForm() / .requestInfoUpdate(), I am not sure though what is the correct / easy way to deduce that from IABTCF_* values? My current best guess is that if either `IABTCF_VendorConsents` or `IABTCF_PublisherConsent` equals `"0"` then user rejected to give his consent and no ads can be served to him, otherwise at least some ads can / will be shown?

**Comment by birgernass** [comment]
I'm willing to work on exposing the consent information. Might take a few days though, don't want to promise any time frame.

**Comment by mikehardy** [comment]
Open source means no promises, no worries ;-)
I'm okay with adding dependencies, but if it's just to get/set a value I'm not sure if full deps like that make sense? And I'm actually the react-native-device-info maintainer :sweat_smile: so I'm arguing against including my own package.

I guess stated differently, the native code required might be pretty small, and we could just take the tiny snips we need from the other packages. In general I try not to tie multiple libraries together if it can be avoided

**Comment by birgernass** [comment]
Everything needed is already in place from the looks of it and only needs to be tied together. This project has quite some helpful utility already in place 👍 And yes, the code would be very minimal anyway. [@iabtcf/core](https://github.com/InteractiveAdvertisingBureau/iabtcf-es/tree/master/modules/core#iabtcfcore) should be the only additional dependency necessary.

**Comment by scaralfred** [comment]
If this library could integrate a way to check the minimum consent to show at least the non-personalized ads, that would be awesome!

**Comment by birdofpreyru** [comment]
Another nuance related to the new consent implementation: code shrinking with Proguard for Android makes the app crash upon `.showForm()` call. I have little knowledge about it, but I guess some changes in implementation should help to fix it, or at least the docs should mention what to add to proguard rules to avoid the problem (I'm still trying to figure out what :)

**Comment by mikehardy** [comment]
oh my - that is really subtle. Usually when code shrinking necessitates a proguard change they document it - really bad form if they haven't done so?

It appears to be somewhat known, but not fully addressed - we are using the current SDK release yes? This appears to be the discussion and the SDK team is responsive in this forum but does not think they have an actionable item: https://groups.google.com/g/google-admob-ads-sdk/c/VPUtbIGgEYw/m/bmsT20EeAwAJ

Perhaps they need an up to date repro?

**Comment by mikehardy** [comment]
In the meantime this could use a PR to the install docs here or others will crash, release mode crashes are *the worst* too because they are subtle if you don't know Android development (though you appear to have just nailed it quickly @birdofpreyru 😆 )

**Comment by birgernass** [comment]
> oh my - that is really subtle. Usually when code shrinking necessitates a proguard change they document it - really bad form if they haven't done so?
> 
> It appears to be somewhat known, but not fully addressed - we are using the current SDK release yes? This appears to be the discussion and the SDK team is responsive in this forum but does not think they have an actionable item: https://groups.google.com/g/google-admob-ads-sdk/c/VPUtbIGgEYw/m/bmsT20EeAwAJ

At least I didn't come across any documentation. And yes, version 2.0.0 is still the latest.

**Comment by mikehardy** [comment]
@birdofpreyru we have version 5.1.0 out with the consent string exposed now - I was wondering if you could help me out by summarizing what the current state of this issue is? It seems like there are multiple things at once and I want to be certain what is still a problem and what is not. For instance, I think we need to add a doc note about proguard, and there are other items as well I think?

**Comment by birdofpreyru** [comment]
@mikehardy Great to have 5.1.0 released, I'll give it a try once I have a time!

I guess, I still want to do a PR with a bunch of minor updates in consent-related docs in this library, clarifying everything that wasn't obvious for me just from reading these docs. Though, I got completely distracted from it for a couple of weeks, and don't exactly remember now all updates I had in mind. Also, I never arrived to try it on iOS. So, it will likely take me some more weeks to do any PR.

**Comment by mikehardy** [comment]
Never any pressure, I appreciate that you're testing it and using it, and whenever you get docs updates together I'm sure they'll help. Cheers
