### ISSUE TITLE
[🐛]  [Error: [googleMobileAds/error-code-no-fill] 

### ISSUE THREAD

**Issue by Ivandeclei** [invertase/react-native-google-mobile-ads#98]
## Issue

Describe your issue here

hello guys I've been using this library but I'm getting the error below. I couldn't identify the reason for this to occur, I followed the steps in the documentation.

 [Error: [googleMobileAds/error-code-no-fill] The ad request was successful, but no ad was returned due to lack of ad inventory.]

<BannerAd
                            unitId={TestIds.BANNER} 
                            size={BannerAdSize.ADAPTIVE_BANNER}
                            requestOptions={{
                            requestNonPersonalizedAdsOnly: true,}}
                            onAdLoaded={() => {
                            console.log('ok');}}
                            onAdFailedToLoad={(error) => {
                            console.error('Error: ', error);}}
                            

                        />
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `admob.json`:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

```ruby
# N/A
```

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
These should help: https://docs.page/invertase/react-native-google-mobile-ads/common-reasons-for-ads-not-showing

Please let us know if you have a specific issue
https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/minimal-reproducible-example

**Comment by AndrewKirkovski** [comment]
Shouldn't Test ids show up always?

I have an issue with `TestIds.BANNER` working with `requestNonPersonalizedAdsOnly: false` but failing to `[Error: [googleMobileAds/error-code-no-fill] The ad request was successful, but no ad was returned due to lack of ad inventory.]` with `requestNonPersonalizedAdsOnly: true`

Same happens to production ads. They were working fine with `requestNonPersonalizedAdsOnly: true` when I was using firebase admob

**Comment by mikehardy** [comment]
Strange, as this works for me always https://github.com/invertase/react-native-google-mobile-ads/blob/5d2048b530b798740c9fed392772568f909dd6b2/RNGoogleMobileAdsExample/App.tsx#L163-L175

**Comment by AndrewKirkovski** [comment]
@mikehardy seems my issue is with consent UMP, but still figuring if it's related to UMP config or RN lib

Basically if I unselect Personal Ads consent (all the rest turned on, including basic ad) ads disappear completely. Even for `TestIds.BANNER`

This happens regardless of `requestNonPersonalizedAdsOnly` value, even if I completely remove it.

Using with just `requestNonPersonalizedAdsOnly` and with no consent requested from UMP works fine.

**Comment by mikehardy** [comment]
@AndrewKirkovski that's really interesting information, you might log that as a separate / fresh issue with full details and a little App.js that exposes the problem? It's not something I personally have tested (and it's not in our little example / test app) so it could be something here that we just haven't surfaced

**Comment by AndrewKirkovski** [comment]
I'm still not sure that's RN lib problem or how UMP is working by design, so will do some research first

Basically I found out following:

When user clicks manages consent, ALL consent flags are off. 

So to get non-personalized ads user needs to turn at least "store info on device" at least what google claims ( https://support.google.com/admob/answer/9760862?ref_topic=10303737 )

Full consent in Shared Prefs looks like this:

````
{
  "IABTCF_CmpSdkID": 300,
  "IABTCF_PurposeLegitimateInterests": "0111111111",
  "IABTCF_UserConsentRecordId": "19B3C821-1CB6-43B5-877F-6F0DCA5FDFD1",
  "IABTCF_PolicyVersion": 2,
  "IABTCF_AddtlConsent": "1~2072.70.89.93.108.122.149.2202.162.167.196.2253.241.2299.259.2357.311.317.323.2373.338.358.2415.415.440.449.2506.2526.482.486.494.495.2568.2571.2575.540.574.2677.817.827.864.981.1048.1051.1095.1097.1127.1201.1205.1211.1276.1301.1365.1415.1449.1570.1577.1651.1716.1753.1765.1870.1878.1889",
  "debug_http_host": "10.0.2.2:8081",
  "IABTCF_TCString": "CPawTEgPawTEgEsABBENCTCoAP_AAH_AACiQHQpB7T7FbSFCyP55bLsAMAhXRkCEAqQAAASBAmABQAKQIAQCkkAQFASgBAACAAAgICZBAQIMCAgACUABQABAAAEEAAAABAAIIAAAgAEAAAAIAAACAIAAAAAIAAAAEAAAmQhAAIIACAAABAAAAAAAAAAAAAAAAgdCgHsLsVtIUJI_GksswAgCFdGQIQCoAAAAIECYAAAApAgBAKQQBAABKAAAAIAACAgJgEBAggACAABQAFAAEAAAAAAAAAAAAggAACAAQAAAAgAAAIAgAAAAAgAAAAAAACBCEAAggAIAAAAAAAAAAAAAAAAAAACAAA.cCgAAAAAAAA",
  "IABTCF_CmpSdkVersion": 1,
  "IABTCF_UseNonStandardStacks": 0,
  "IABTCF_PurposeConsents": "1111111111",
  "IABTCF_PublisherLegitimateInterests": "0",
  "IABTCF_idfaFlowControl": 2,
  "IABTCF_PublisherConsent": "1000000101",
  "IABTCF_VendorConsents": "10010000011110110100111110110001010110110100100001010000101100100011111110011110010110110010111011000000000011000000001000010101110100011001000000100001000000001010100100000000000000000000000100100000010000001001100000000000010100000000000010100100000010000000000100000000101001001001000000000100000001010000000100101000000000010000000000000000100000000000000000001000000010000000100110010000010000000100000010000011000000100000001000000000000000100101000000000000010100000000000000010000000000000000000001000001000000000000000000000000000000010000000000000010000010000000000000000000001000000000000001000000000000000000000000000010000000000000000000000000100000000010000000000000000000000000000000000010000000000000000000000000000001000000000000000000001001100100001000010000000000000010000010000000000000100000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001",
  "IABTCF_VendorLegitimateInterests": "10000000011110110000101110110001010110110100100001010000100100100011111100011010010010110010110011000000000010000000001000010101110100011001000000100001000000001010100000000000000000000000000000100000010000001001100000000000000000000000000010100100000010000000000100000000101001000001000000000100000000000000000100101000000000000000000000000000100000000000000000001000000010000000100110000000010000000100000010000010000000000000001000000000000000000101000000000000010100000000000000010000000000000000000000000000000000000000000000000000000000000000000000000010000010000000000000000000001000000000000001000000000000000000000000000010000000000000000000000000100000000010000000000000000000000000000000000010000000000000000000000000000000000000000000000000001000000100001000010000000000000010000010000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001",
  "remote_js_debug": false,
  "IABTCF_SpecialFeaturesOptIns": "1",
  "IABTCF_PublisherCC": "US",
  "IABTCF_gdprApplies": 1,
  "IABTCF_PurposeOneTreatment": 0
}
````

When I select all purposed but "personal ads" in manage consent it looks like this

```
{
  "IABTCF_CmpSdkID": 300,
  "IABTCF_PurposeLegitimateInterests": "0111111111",
  "IABTCF_UserConsentRecordId": "243BBED1-CBCF-4C67-9C07-9CDB3E0A3761",
  "IABTCF_PolicyVersion": 2,
  "IABTCF_AddtlConsent": "1~",
  "debug_http_host": "10.0.2.2:8081",
  "IABTCF_TCString": "CPawTEgPawTEgEsABCENCTCoAO_AAH_AACiQAAAOhQD2F2K2kKEkfjSWWYAQBCujIEIBUAAAAECBMAAAAUgQAgFIIAgAAlAAAAEAABAQEwCAgQQABAAAoACgACAAAAAAAAAAAAQQAABAAIAAAAQAAAEAQAAAAAQAAAAAAABAhCAAQQAEAAAAAAAAAAAAAAAAAAABAAA.cCgAAAAAAAA",
  "IABTCF_CmpSdkVersion": 1,
  "IABTCF_UseNonStandardStacks": 0,
  "IABTCF_PurposeConsents": "1110111111",
  "IABTCF_PublisherLegitimateInterests": "0",
  "IABTCF_idfaFlowControl": 2,
  "IABTCF_PublisherConsent": "1000000101",
  "IABTCF_VendorConsents": "0",
  "IABTCF_VendorLegitimateInterests": "10000000011110110000101110110001010110110100100001010000100100100011111100011010010010110010110011000000000010000000001000010101110100011001000000100001000000001010100000000000000000000000000000100000010000001001100000000000000000000000000010100100000010000000000100000000101001000001000000000100000000000000000100101000000000000000000000000000100000000000000000001000000010000000100110000000010000000100000010000010000000000000001000000000000000000101000000000000010100000000000000010000000000000000000000000000000000000000000000000000000000000000000000000010000010000000000000000000001000000000000001000000000000000000000000000010000000000000000000000000100000000010000000000000000000000000000000000010000000000000000000000000000000000000000000000000001000000100001000010000000000000010000010000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001",
  "remote_js_debug": false,
  "IABTCF_SpecialFeaturesOptIns": "1",
  "IABTCF_PublisherCC": "US",
  "IABTCF_gdprApplies": 1,
  "IABTCF_PurposeOneTreatment": 0
}
````

The problem here is `"IABTCF_VendorConsents": "0",` seems to make TestIds.BANNER not to fill

I'm not sure if google REALLY expects for user to go deeper and manually consent to list of hundred of vendors or if that's a bug. If it's by google design, it's basically "ads off" switch, nobody will bother to turn these consents manually

When I consent manually to purposes AND vendors, TestIds.BANNER starts to fill properly

**Comment by GreenGraphicx1** [comment]
Hello, so how do I resolve this, `The ads request was successful, but no ad was returned due to lack of ad inventory. [googleMobileAds/error-code-no-fill],` i'm using ``import { BannerAd, BannerAdSize, TestIds, useForeground } from 'react-native-google-mobile-ads'; const adUnitId = __DEV__ ? TestIds.ADAPTIVE_BANNER : 'ca-app-pub-7649388502096236/2483560701'; `` from the link   @mikehardy shared, mean I have to wait for a week? to get my app ready to start showing ads?

**Comment by mikehardy** [comment]
This repository has no ability to solve no-fill issues. The job of this module is to make sure the first part of your statement is true - "the ad request was successful".
