### ISSUE TITLE
Is the SDK intialization a mandatory method ot not?

### ISSUE THREAD

**Issue by scaralfred** [invertase/react-native-google-mobile-ads#99]
Hello and thanks for this wonderful library.
I'm just a bit confused about the SDK initialization. 
Is it mandatory o not? Why ads can be shown even if we don't call the method "mobileAds().initialize()"?

I also need to use the property "delay_app_measurement_init": true, so I need to understand the right steps for the right flow.

Thanks in advance for your clarification.

**Comment by dylancom** [comment]
Our docs explain this.
You can also read upon why you need initialization in the official SDK docs:
https://developers.google.com/admob/ios/quick-start#initialize_the_mobile_ads_sdk
https://developers.google.com/admob/android/quick-start#initialize_the_mobile_ads_sdk
